#!/bin/sh
set -euo pipefail

RUN_PARAMS="${RUN_PARAMS:-}"

if [[ -f "${CONF_PATH:-}" ]]; then
  RUN_PARAMS="${RUN_PARAMS} --config \"${CONF_PATH}\""
else
  ./farmer setup
fi

if [ -n "$SATELLITE_ADDR" ]; then
	RUN_PARAMS="${RUN_PARAMS} --kademlia.bootstrap-addr $SATELLITE_ADDR"
fi

exec ./farmer run $RUN_PARAMS "$@"
