// Copyright (C) 2019 Storj Labs, Inc.
// See LICENSE for copying information.

export const NOTIFICATION_MUTATIONS = {
    ADD: 'ADD_NOTIFICATION',
    DELETE: 'DELETE_NOTIFICATION',
    PAUSE: 'PAUSE_NOTIFICATION',
    RESUME: 'RESUME_NOTIFICATION',
    CLEAR: 'CLEAR_NOTIFICATIONS',
};

export const APP_STATE_MUTATIONS = {
    TOGGLE_SUCCESSFUL_PASSWORD_RESET: 'TOGGLE_SUCCESSFUL_PASSWORD_RESET',
    TOGGLE_HAS_JUST_LOGGED_IN: 'TOGGLE_HAS_JUST_LOGGED_IN',
    CLEAR: 'CLEAR_APPSTATE',
    CLOSE_BILLING_NOTIFICATION: 'closeBillingNotification',
    CHANGE_FETCH_STATE: 'CHANGE_FETCH_STATE',
    SET_SATELLITE_NAME: 'SET_SATELLITE_NAME',
    SET_PARTNERED_SATELLITES: 'SET_PARTNERED_SATELLITES',
    SET_SATELLITE_STATUS: 'SET_SATELLITE_STATUS',
    SET_COUPON_CODE_BILLING_UI_STATUS: 'SET_COUPON_CODE_BILLING_UI_STATUS',
    SET_COUPON_CODE_SIGNUP_UI_STATUS: 'SET_COUPON_CODE_SIGNUP_UI_STATUS',
    SET_ONB_AG_NAME_STEP_BACK_ROUTE: 'SET_ONB_AG_NAME_STEP_BACK_ROUTE',
    SET_ONB_API_KEY_STEP_BACK_ROUTE: 'SET_ONB_API_KEY_STEP_BACK_ROUTE',
    SET_ONB_API_KEY: 'SET_ONB_API_KEY',
    SET_ONB_CLEAN_API_KEY: 'SET_ONB_CLEAN_API_KEY',
    SET_ONB_OS: 'SET_ONB_OS',
    SET_MANAGE_PASSPHRASE_STEP: 'SET_MANAGE_PASSPHRASE_STEP',
    TOGGLE_ACTIVE_DROPDOWN: 'TOGGLE_ACTIVE_DROPDOWN',
    UPDATE_ACTIVE_MODAL: 'UPDATE_ACTIVE_MODAL',
    REMOVE_ACTIVE_MODAL: 'REMOVE_ACTIVE_MODAL',
    SET_PRICING_PLAN: 'SET_PRICING_PLAN',
    SET_CONFIG: 'SET_CONFIG',
};
