
@startuml

S3Client -> Gateway: PUT /bucket/dest?uploads

Gateway -> Uplink: BeginUpload (multipart)
note left
    Bucket
    Key
    Expires
end note

Uplink -> Satellite: BeginObjectRequest

Uplink <-- Satellite: BeginObjectResponse
note right
    StreamID
end note

Gateway <-- Uplink: BeginUpload return
note right
    StreamID
end note

S3Client <-- Gateway: 200 response
note right
    <UploadId />
end note

group loop for every part
    S3Client -> Gateway: PUT /bucket/dest?partNumber=1&uploadId=7tKsLOJgNs

    Gateway -> Uplink: UploadPart
    note left
        Bucket
        Key
        UploadID
        PartNumber
    end note

    Gateway -> Uplink: UploadPart.write

    group loop for every segment

        Uplink -> Satellite: SegmentBeginRequest
        note left
            StreamID
            Position
        end note

        Uplink <-- Satellite: SegmentBeginResponse
        note right
            SegmentID              
            OrderLimits
            PiecePrivateKey
        end note

        collections StorageNodes

        Uplink -> StorageNodes: PieceUploadRequest
        Uplink <-- StorageNodes: PieceUploadResponse

        Uplink -> Satellite: SegmentCommitRequest
        note left
            SegmentID
            EncryptedKey
            Size
            []SegmentPieceUploadResult
        end note

        Uplink <-- Satellite: SegmentCommitResponse

    else if inline
        Uplink -> Satellite: SegmentMakeInlineRequest
        Uplink <-- Satellite: SegmentMakeInlineResponse
    end

    Gateway <-- Uplink: UploadPart return

    S3Client <-- Gateway: 200 response
end

S3Client -> Gateway: POST /bucket/dest?uploadId=7tKsLOJgNs

Gateway -> Uplink: CommitUpload
note left
    Bucket
    Key
    UploadID
    CustomMetadata
end note

Uplink -> Satellite: ObjectCommitRequest
note left
    StreamID
    CustomMetadata //encypted//
end note
note right #lightgreen
    Change object status from 
    pending to committed
end note

Uplink <-- Satellite: ObjectCommitResponse

Gateway <-- Uplink: CommitUpload return

S3Client <-- Gateway: 200 response

@enduml
