// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inspector.proto

package internalpb

import (
	fmt "fmt"
	math "math"
	time "time"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsRequest) Reset()         { *m = StatsRequest{} }
func (m *StatsRequest) String() string { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()    {}
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a07d9034b2dd9d26, []int{0}
}
func (m *StatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsRequest.Unmarshal(m, b)
}
func (m *StatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsRequest.Marshal(b, m, deterministic)
}
func (m *StatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsRequest.Merge(m, src)
}
func (m *StatsRequest) XXX_Size() int {
	return xxx_messageInfo_StatsRequest.Size(m)
}
func (m *StatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatsRequest proto.InternalMessageInfo

type StatSummaryResponse struct {
	UsedSpace            int64    `protobuf:"varint,1,opt,name=used_space,json=usedSpace,proto3" json:"used_space,omitempty"`
	AvailableSpace       int64    `protobuf:"varint,2,opt,name=available_space,json=availableSpace,proto3" json:"available_space,omitempty"`
	UsedIngress          int64    `protobuf:"varint,3,opt,name=used_ingress,json=usedIngress,proto3" json:"used_ingress,omitempty"`
	UsedEgress           int64    `protobuf:"varint,4,opt,name=used_egress,json=usedEgress,proto3" json:"used_egress,omitempty"`
	UsedBandwidth        int64    `protobuf:"varint,5,opt,name=used_bandwidth,json=usedBandwidth,proto3" json:"used_bandwidth,omitempty"`
	AvailableBandwidth   int64    `protobuf:"varint,6,opt,name=available_bandwidth,json=availableBandwidth,proto3" json:"available_bandwidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatSummaryResponse) Reset()         { *m = StatSummaryResponse{} }
func (m *StatSummaryResponse) String() string { return proto.CompactTextString(m) }
func (*StatSummaryResponse) ProtoMessage()    {}
func (*StatSummaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a07d9034b2dd9d26, []int{1}
}
func (m *StatSummaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatSummaryResponse.Unmarshal(m, b)
}
func (m *StatSummaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatSummaryResponse.Marshal(b, m, deterministic)
}
func (m *StatSummaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatSummaryResponse.Merge(m, src)
}
func (m *StatSummaryResponse) XXX_Size() int {
	return xxx_messageInfo_StatSummaryResponse.Size(m)
}
func (m *StatSummaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatSummaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatSummaryResponse proto.InternalMessageInfo

func (m *StatSummaryResponse) GetUsedSpace() int64 {
	if m != nil {
		return m.UsedSpace
	}
	return 0
}

func (m *StatSummaryResponse) GetAvailableSpace() int64 {
	if m != nil {
		return m.AvailableSpace
	}
	return 0
}

func (m *StatSummaryResponse) GetUsedIngress() int64 {
	if m != nil {
		return m.UsedIngress
	}
	return 0
}

func (m *StatSummaryResponse) GetUsedEgress() int64 {
	if m != nil {
		return m.UsedEgress
	}
	return 0
}

func (m *StatSummaryResponse) GetUsedBandwidth() int64 {
	if m != nil {
		return m.UsedBandwidth
	}
	return 0
}

func (m *StatSummaryResponse) GetAvailableBandwidth() int64 {
	if m != nil {
		return m.AvailableBandwidth
	}
	return 0
}

type DashboardRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DashboardRequest) Reset()         { *m = DashboardRequest{} }
func (m *DashboardRequest) String() string { return proto.CompactTextString(m) }
func (*DashboardRequest) ProtoMessage()    {}
func (*DashboardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a07d9034b2dd9d26, []int{2}
}
func (m *DashboardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashboardRequest.Unmarshal(m, b)
}
func (m *DashboardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashboardRequest.Marshal(b, m, deterministic)
}
func (m *DashboardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardRequest.Merge(m, src)
}
func (m *DashboardRequest) XXX_Size() int {
	return xxx_messageInfo_DashboardRequest.Size(m)
}
func (m *DashboardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardRequest proto.InternalMessageInfo

type DashboardResponse struct {
	NodeId               NodeID               `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3,customtype=NodeID" json:"node_id"`
	NodeConnections      int64                `protobuf:"varint,2,opt,name=node_connections,json=nodeConnections,proto3" json:"node_connections,omitempty"`
	BootstrapAddress     string               `protobuf:"bytes,3,opt,name=bootstrap_address,json=bootstrapAddress,proto3" json:"bootstrap_address,omitempty"` // Deprecated: Do not use.
	InternalAddress      string               `protobuf:"bytes,4,opt,name=internal_address,json=internalAddress,proto3" json:"internal_address,omitempty"`
	ExternalAddress      string               `protobuf:"bytes,5,opt,name=external_address,json=externalAddress,proto3" json:"external_address,omitempty"`
	DashboardAddress     string               `protobuf:"bytes,6,opt,name=dashboard_address,json=dashboardAddress,proto3" json:"dashboard_address,omitempty"`
	Stats                *StatSummaryResponse `protobuf:"bytes,7,opt,name=stats,proto3" json:"stats,omitempty"`
	Uptime               string               `protobuf:"bytes,8,opt,name=uptime,proto3" json:"uptime,omitempty"`
	LastPinged           time.Time            `protobuf:"bytes,9,opt,name=last_pinged,json=lastPinged,proto3,stdtime" json:"last_pinged"`
	LastQueried          time.Time            `protobuf:"bytes,10,opt,name=last_queried,json=lastQueried,proto3,stdtime" json:"last_queried"`
	LastPingFromId       *NodeID              `protobuf:"bytes,11,opt,name=last_ping_from_id,json=lastPingFromId,proto3,customtype=NodeID" json:"last_ping_from_id,omitempty"`
	LastPingFromAddress  string               `protobuf:"bytes,12,opt,name=last_ping_from_address,json=lastPingFromAddress,proto3" json:"last_ping_from_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DashboardResponse) Reset()         { *m = DashboardResponse{} }
func (m *DashboardResponse) String() string { return proto.CompactTextString(m) }
func (*DashboardResponse) ProtoMessage()    {}
func (*DashboardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a07d9034b2dd9d26, []int{3}
}
func (m *DashboardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashboardResponse.Unmarshal(m, b)
}
func (m *DashboardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashboardResponse.Marshal(b, m, deterministic)
}
func (m *DashboardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardResponse.Merge(m, src)
}
func (m *DashboardResponse) XXX_Size() int {
	return xxx_messageInfo_DashboardResponse.Size(m)
}
func (m *DashboardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardResponse proto.InternalMessageInfo

func (m *DashboardResponse) GetNodeConnections() int64 {
	if m != nil {
		return m.NodeConnections
	}
	return 0
}

// Deprecated: Do not use.
func (m *DashboardResponse) GetBootstrapAddress() string {
	if m != nil {
		return m.BootstrapAddress
	}
	return ""
}

func (m *DashboardResponse) GetInternalAddress() string {
	if m != nil {
		return m.InternalAddress
	}
	return ""
}

func (m *DashboardResponse) GetExternalAddress() string {
	if m != nil {
		return m.ExternalAddress
	}
	return ""
}

func (m *DashboardResponse) GetDashboardAddress() string {
	if m != nil {
		return m.DashboardAddress
	}
	return ""
}

func (m *DashboardResponse) GetStats() *StatSummaryResponse {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *DashboardResponse) GetUptime() string {
	if m != nil {
		return m.Uptime
	}
	return ""
}

func (m *DashboardResponse) GetLastPinged() time.Time {
	if m != nil {
		return m.LastPinged
	}
	return time.Time{}
}

func (m *DashboardResponse) GetLastQueried() time.Time {
	if m != nil {
		return m.LastQueried
	}
	return time.Time{}
}

func (m *DashboardResponse) GetLastPingFromAddress() string {
	if m != nil {
		return m.LastPingFromAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*StatsRequest)(nil), "storagenode.inspector.StatsRequest")
	proto.RegisterType((*StatSummaryResponse)(nil), "storagenode.inspector.StatSummaryResponse")
	proto.RegisterType((*DashboardRequest)(nil), "storagenode.inspector.DashboardRequest")
	proto.RegisterType((*DashboardResponse)(nil), "storagenode.inspector.DashboardResponse")
}

func init() { proto.RegisterFile("inspector.proto", fileDescriptor_a07d9034b2dd9d26) }

var fileDescriptor_a07d9034b2dd9d26 = []byte{
	// 598 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x97, 0x6d, 0xed, 0xd6, 0xb7, 0xa5, 0x7f, 0x5c, 0x31, 0x45, 0x95, 0x50, 0x47, 0xd1,
	0xd4, 0x01, 0x52, 0x22, 0x6d, 0xe2, 0x0e, 0x65, 0x03, 0xf5, 0x82, 0x46, 0xca, 0x69, 0x97, 0xe2,
	0xd4, 0xef, 0x32, 0xa3, 0x36, 0xce, 0x6c, 0x87, 0x3f, 0xdf, 0x82, 0x8f, 0xc5, 0x9d, 0x1b, 0x87,
	0xf1, 0x19, 0x38, 0x72, 0x43, 0x76, 0xea, 0xac, 0xaa, 0x06, 0x68, 0xb7, 0xf8, 0x79, 0x7f, 0xaf,
	0xed, 0x3c, 0xef, 0x63, 0x68, 0xf1, 0x54, 0x65, 0x38, 0xd3, 0x42, 0x06, 0x99, 0x14, 0x5a, 0x90,
	0xfb, 0x4a, 0x0b, 0x49, 0x13, 0x4c, 0x05, 0xc3, 0xa0, 0x2c, 0xf6, 0x20, 0x11, 0x89, 0x28, 0x90,
	0x5e, 0x3f, 0x11, 0x22, 0x99, 0x63, 0x68, 0x57, 0x71, 0x7e, 0x11, 0x6a, 0xbe, 0x40, 0xa5, 0xe9,
	0x22, 0x2b, 0x80, 0x41, 0x13, 0x1a, 0x13, 0x4d, 0xb5, 0x8a, 0xf0, 0x2a, 0x47, 0xa5, 0x07, 0xbf,
	0x3d, 0xe8, 0x1a, 0x61, 0x92, 0x2f, 0x16, 0x54, 0x7e, 0x89, 0x50, 0x65, 0x22, 0x55, 0x48, 0x1e,
	0x00, 0xe4, 0x0a, 0xd9, 0x54, 0x65, 0x74, 0x86, 0xbe, 0xb7, 0xef, 0x1d, 0x6e, 0x45, 0x35, 0xa3,
	0x4c, 0x8c, 0x40, 0x86, 0xd0, 0xa2, 0x1f, 0x29, 0x9f, 0xd3, 0x78, 0x8e, 0x4b, 0x66, 0xd3, 0x32,
	0xcd, 0x52, 0x2e, 0xc0, 0x87, 0xd0, 0xb0, 0xfb, 0xf0, 0x34, 0x91, 0xa8, 0x94, 0xbf, 0x65, 0xa9,
	0xba, 0xd1, 0xc6, 0x85, 0x44, 0xfa, 0x60, 0x97, 0x53, 0x2c, 0x88, 0x6d, 0x4b, 0xd8, 0xd3, 0x4f,
	0x0b, 0xe0, 0x00, 0x9a, 0x16, 0x88, 0x69, 0xca, 0x3e, 0x71, 0xa6, 0x2f, 0xfd, 0x8a, 0x65, 0xee,
	0x19, 0x75, 0xe4, 0x44, 0x12, 0x42, 0xf7, 0xe6, 0x4e, 0x37, 0x6c, 0xd5, 0xb2, 0xa4, 0x2c, 0x95,
	0x0d, 0x03, 0x02, 0xed, 0x13, 0xaa, 0x2e, 0x63, 0x41, 0x25, 0x73, 0x7e, 0xfc, 0xda, 0x86, 0xce,
	0x8a, 0xb8, 0x74, 0x63, 0x08, 0x3b, 0xc6, 0xf4, 0x29, 0x67, 0xd6, 0x8a, 0xc6, 0xa8, 0xf9, 0xed,
	0xba, 0xbf, 0xf1, 0xe3, 0xba, 0x5f, 0x7d, 0x23, 0x18, 0x8e, 0x4f, 0xa2, 0xaa, 0x29, 0x8f, 0x19,
	0x79, 0x0c, 0x6d, 0x0b, 0xce, 0x44, 0x9a, 0xe2, 0x4c, 0x73, 0x91, 0xaa, 0xa5, 0x31, 0x2d, 0xa3,
	0xbf, 0xbc, 0x91, 0x49, 0x08, 0x9d, 0x58, 0x08, 0xad, 0xb4, 0xa4, 0xd9, 0x94, 0x32, 0x56, 0xda,
	0x53, 0x1b, 0x6d, 0xfa, 0x5e, 0xd4, 0x2e, 0x8b, 0x2f, 0x8a, 0x9a, 0xd9, 0x9b, 0xa7, 0x1a, 0x65,
	0x4a, 0xe7, 0x25, 0x6f, 0xcc, 0xaa, 0x45, 0x2d, 0xa7, 0xaf, 0xa0, 0xf8, 0x79, 0x0d, 0xad, 0x14,
	0xa8, 0xd3, 0x1d, 0xfa, 0x14, 0x3a, 0xcc, 0xfd, 0x6f, 0xc9, 0x56, 0x2d, 0xdb, 0x2e, 0x0b, 0x0e,
	0x7e, 0x0e, 0x15, 0x65, 0xd2, 0xe3, 0xef, 0xec, 0x7b, 0x87, 0xf5, 0xa3, 0x27, 0xc1, 0xad, 0x89,
	0x0c, 0x6e, 0x09, 0x54, 0x54, 0x34, 0x92, 0x3d, 0xa8, 0xe6, 0x99, 0x09, 0xa5, 0xbf, 0x6b, 0xcf,
	0x58, 0xae, 0xc8, 0x29, 0xd4, 0xe7, 0x54, 0xe9, 0x69, 0xc6, 0xd3, 0x04, 0x99, 0x5f, 0xb3, 0xfb,
	0xf7, 0x82, 0x22, 0xce, 0x81, 0x8b, 0x73, 0xf0, 0xce, 0xc5, 0x79, 0xb4, 0x6b, 0x26, 0xf0, 0xf5,
	0x67, 0xdf, 0x8b, 0xc0, 0x34, 0x9e, 0xd9, 0x3e, 0xf2, 0x1a, 0x1a, 0x76, 0x9b, 0xab, 0x1c, 0x25,
	0x47, 0xe6, 0xc3, 0x1d, 0xf6, 0xb1, 0x17, 0x78, 0x5b, 0x34, 0x92, 0x67, 0xd0, 0x29, 0xef, 0x33,
	0xbd, 0x90, 0x62, 0x61, 0x66, 0x5f, 0xb7, 0xb3, 0x87, 0x95, 0xb9, 0x37, 0xdd, 0xd9, 0xaf, 0xa4,
	0x58, 0x8c, 0x19, 0x39, 0x86, 0xbd, 0xb5, 0x36, 0x67, 0x69, 0xc3, 0xfe, 0x6e, 0x77, 0x95, 0x5f,
	0xba, 0x7a, 0xf4, 0xdd, 0x83, 0xee, 0x19, 0xc7, 0x19, 0x4e, 0xb4, 0x90, 0x38, 0x76, 0x36, 0x92,
	0x73, 0xa8, 0xd8, 0xb7, 0x4a, 0x1e, 0xfd, 0xc3, 0x67, 0xf7, 0x92, 0x7b, 0x77, 0x18, 0xc6, 0x60,
	0x83, 0xbc, 0x87, 0x5a, 0x19, 0x73, 0x32, 0xfc, 0x4b, 0xeb, 0xfa, 0xeb, 0xe8, 0x1d, 0xfe, 0x1f,
	0x74, 0x27, 0x8c, 0x86, 0xe7, 0x07, 0x06, 0xfe, 0x10, 0x70, 0x11, 0xda, 0x8f, 0x70, 0xa5, 0x37,
	0x74, 0x89, 0xcd, 0xe2, 0xb8, 0x6a, 0xa7, 0x72, 0xfc, 0x27, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x0f,
	0xce, 0xb4, 0xf0, 0x04, 0x00, 0x00,
}
