#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CURRENTDIR="$(pwd)"

vgo build -o piece-store-server $DIR"/../server/main.go"
$CURRENTDIR"/piece-store-server" 8080 &
$CURRENTDIR"/piece-store-server" 8081 &
$CURRENTDIR"/piece-store-server" 8082 &
$CURRENTDIR"/piece-store-server" 8083 &
$CURRENTDIR"/piece-store-server" 8084 &
$CURRENTDIR"/piece-store-server" 8085 &
$CURRENTDIR"/piece-store-server" 8086 &
$CURRENTDIR"/piece-store-server" 8087 &
$CURRENTDIR"/piece-store-server" 8088 &
$CURRENTDIR"/piece-store-server" 8089 &
