#!/bin/sh
set -euo pipefail

RUN_PARAMS="${RUN_PARAMS:-} --overlay.database-url redis://:${REDIS_PASSWORD}@${REDIS_ADDRESS}/?db=${REDIS_DB} --debug.addr=${HTTP_PORT} --identity.address=${OVERLAY_PORT}"

if [[ -f "${CONF_PATH:-}" ]]; then
  RUN_PARAMS="${RUN_PARAMS} --config \"${CONF_PATH}\""
else
  ./hc setup
fi

if [[ -n "${API_KEY}" ]]; then
	RUN_PARAMS="${RUN_PARAMS} --pointer-db.auth.api-key ${API_KEY}"
fi

exec ./hc run $RUN_PARAMS "$@"
