apiVersion: v1
kind: Service
metadata:
  name: hc
  labels:
    app: hc
spec:
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
  - name: http
    port: 8081
    targetPort: 8081
  - name: kademlia
    protocol: UDP
    port: 8080
    target: 8080
  selector:
    app: hc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hc
  labels:
    app: hc
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: hc
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: "docker.io/storjlabs/hc"
        imagePullPolicy: Always
        name: hc
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
        env:
          - name: REDIS_ADDRESS
            value: "35.184.203.66:6379"
          - name: REDIS_PASSWORD
            value: ""
          - name: REDIS_DB
            value: "1"
          - name: OVERLAY_PORT
            value: "7070"
          - name: HTTP_PORT
            value: "8081"
        ports:
        - name: grpc
          containerPort: 8080
        - name: http
          containerPort: 8081
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
