// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: jobqueue.proto

package internalpb

import (
	fmt "fmt"
	math "math"
	time "time"

	proto "github.com/gogo/protobuf/proto"

	_ "storj.io/common/pb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RepairJob struct {
	StreamId             []byte     `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Position             uint64     `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Health               float64    `protobuf:"fixed64,3,opt,name=health,proto3" json:"health,omitempty"`
	InsertedAt           *time.Time `protobuf:"bytes,4,opt,name=inserted_at,json=insertedAt,proto3,stdtime" json:"inserted_at,omitempty"`
	LastAttemptedAt      *time.Time `protobuf:"bytes,5,opt,name=last_attempted_at,json=lastAttemptedAt,proto3,stdtime" json:"last_attempted_at,omitempty"`
	NumAttempts          int32      `protobuf:"varint,6,opt,name=num_attempts,json=numAttempts,proto3" json:"num_attempts,omitempty"`
	Placement            int32      `protobuf:"varint,7,opt,name=placement,proto3" json:"placement,omitempty"`
	NumMissing           int32      `protobuf:"varint,8,opt,name=num_missing,json=numMissing,proto3" json:"num_missing,omitempty"`
	NumOutOfPlacement    int32      `protobuf:"varint,9,opt,name=num_out_of_placement,json=numOutOfPlacement,proto3" json:"num_out_of_placement,omitempty"`
	UpdatedAt            *time.Time `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3,stdtime" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RepairJob) Reset()         { *m = RepairJob{} }
func (m *RepairJob) String() string { return proto.CompactTextString(m) }
func (*RepairJob) ProtoMessage()    {}
func (*RepairJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{0}
}
func (m *RepairJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepairJob.Unmarshal(m, b)
}
func (m *RepairJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepairJob.Marshal(b, m, deterministic)
}
func (m *RepairJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepairJob.Merge(m, src)
}
func (m *RepairJob) XXX_Size() int {
	return xxx_messageInfo_RepairJob.Size(m)
}
func (m *RepairJob) XXX_DiscardUnknown() {
	xxx_messageInfo_RepairJob.DiscardUnknown(m)
}

var xxx_messageInfo_RepairJob proto.InternalMessageInfo

func (m *RepairJob) GetStreamId() []byte {
	if m != nil {
		return m.StreamId
	}
	return nil
}

func (m *RepairJob) GetPosition() uint64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *RepairJob) GetHealth() float64 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *RepairJob) GetInsertedAt() *time.Time {
	if m != nil {
		return m.InsertedAt
	}
	return nil
}

func (m *RepairJob) GetLastAttemptedAt() *time.Time {
	if m != nil {
		return m.LastAttemptedAt
	}
	return nil
}

func (m *RepairJob) GetNumAttempts() int32 {
	if m != nil {
		return m.NumAttempts
	}
	return 0
}

func (m *RepairJob) GetPlacement() int32 {
	if m != nil {
		return m.Placement
	}
	return 0
}

func (m *RepairJob) GetNumMissing() int32 {
	if m != nil {
		return m.NumMissing
	}
	return 0
}

func (m *RepairJob) GetNumOutOfPlacement() int32 {
	if m != nil {
		return m.NumOutOfPlacement
	}
	return 0
}

func (m *RepairJob) GetUpdatedAt() *time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type JobQueuePushRequest struct {
	Job                  *RepairJob `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JobQueuePushRequest) Reset()         { *m = JobQueuePushRequest{} }
func (m *JobQueuePushRequest) String() string { return proto.CompactTextString(m) }
func (*JobQueuePushRequest) ProtoMessage()    {}
func (*JobQueuePushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{1}
}
func (m *JobQueuePushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueuePushRequest.Unmarshal(m, b)
}
func (m *JobQueuePushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueuePushRequest.Marshal(b, m, deterministic)
}
func (m *JobQueuePushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueuePushRequest.Merge(m, src)
}
func (m *JobQueuePushRequest) XXX_Size() int {
	return xxx_messageInfo_JobQueuePushRequest.Size(m)
}
func (m *JobQueuePushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueuePushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueuePushRequest proto.InternalMessageInfo

func (m *JobQueuePushRequest) GetJob() *RepairJob {
	if m != nil {
		return m.Job
	}
	return nil
}

type JobQueuePushResponse struct {
	NewlyInserted        bool     `protobuf:"varint,1,opt,name=newly_inserted,json=newlyInserted,proto3" json:"newly_inserted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueuePushResponse) Reset()         { *m = JobQueuePushResponse{} }
func (m *JobQueuePushResponse) String() string { return proto.CompactTextString(m) }
func (*JobQueuePushResponse) ProtoMessage()    {}
func (*JobQueuePushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{2}
}
func (m *JobQueuePushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueuePushResponse.Unmarshal(m, b)
}
func (m *JobQueuePushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueuePushResponse.Marshal(b, m, deterministic)
}
func (m *JobQueuePushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueuePushResponse.Merge(m, src)
}
func (m *JobQueuePushResponse) XXX_Size() int {
	return xxx_messageInfo_JobQueuePushResponse.Size(m)
}
func (m *JobQueuePushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueuePushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueuePushResponse proto.InternalMessageInfo

func (m *JobQueuePushResponse) GetNewlyInserted() bool {
	if m != nil {
		return m.NewlyInserted
	}
	return false
}

type JobQueuePushBatchRequest struct {
	Jobs                 []*RepairJob `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *JobQueuePushBatchRequest) Reset()         { *m = JobQueuePushBatchRequest{} }
func (m *JobQueuePushBatchRequest) String() string { return proto.CompactTextString(m) }
func (*JobQueuePushBatchRequest) ProtoMessage()    {}
func (*JobQueuePushBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{3}
}
func (m *JobQueuePushBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueuePushBatchRequest.Unmarshal(m, b)
}
func (m *JobQueuePushBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueuePushBatchRequest.Marshal(b, m, deterministic)
}
func (m *JobQueuePushBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueuePushBatchRequest.Merge(m, src)
}
func (m *JobQueuePushBatchRequest) XXX_Size() int {
	return xxx_messageInfo_JobQueuePushBatchRequest.Size(m)
}
func (m *JobQueuePushBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueuePushBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueuePushBatchRequest proto.InternalMessageInfo

func (m *JobQueuePushBatchRequest) GetJobs() []*RepairJob {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type JobQueuePushBatchResponse struct {
	NewlyInserted        []bool   `protobuf:"varint,1,rep,packed,name=newly_inserted,json=newlyInserted,proto3" json:"newly_inserted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueuePushBatchResponse) Reset()         { *m = JobQueuePushBatchResponse{} }
func (m *JobQueuePushBatchResponse) String() string { return proto.CompactTextString(m) }
func (*JobQueuePushBatchResponse) ProtoMessage()    {}
func (*JobQueuePushBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{4}
}
func (m *JobQueuePushBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueuePushBatchResponse.Unmarshal(m, b)
}
func (m *JobQueuePushBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueuePushBatchResponse.Marshal(b, m, deterministic)
}
func (m *JobQueuePushBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueuePushBatchResponse.Merge(m, src)
}
func (m *JobQueuePushBatchResponse) XXX_Size() int {
	return xxx_messageInfo_JobQueuePushBatchResponse.Size(m)
}
func (m *JobQueuePushBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueuePushBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueuePushBatchResponse proto.InternalMessageInfo

func (m *JobQueuePushBatchResponse) GetNewlyInserted() []bool {
	if m != nil {
		return m.NewlyInserted
	}
	return nil
}

type JobQueuePopRequest struct {
	IncludedPlacements   []int32  `protobuf:"varint,1,rep,packed,name=included_placements,json=includedPlacements,proto3" json:"included_placements,omitempty"`
	ExcludedPlacements   []int32  `protobuf:"varint,2,rep,packed,name=excluded_placements,json=excludedPlacements,proto3" json:"excluded_placements,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueuePopRequest) Reset()         { *m = JobQueuePopRequest{} }
func (m *JobQueuePopRequest) String() string { return proto.CompactTextString(m) }
func (*JobQueuePopRequest) ProtoMessage()    {}
func (*JobQueuePopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{5}
}
func (m *JobQueuePopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueuePopRequest.Unmarshal(m, b)
}
func (m *JobQueuePopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueuePopRequest.Marshal(b, m, deterministic)
}
func (m *JobQueuePopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueuePopRequest.Merge(m, src)
}
func (m *JobQueuePopRequest) XXX_Size() int {
	return xxx_messageInfo_JobQueuePopRequest.Size(m)
}
func (m *JobQueuePopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueuePopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueuePopRequest proto.InternalMessageInfo

func (m *JobQueuePopRequest) GetIncludedPlacements() []int32 {
	if m != nil {
		return m.IncludedPlacements
	}
	return nil
}

func (m *JobQueuePopRequest) GetExcludedPlacements() []int32 {
	if m != nil {
		return m.ExcludedPlacements
	}
	return nil
}

type JobQueuePopResponse struct {
	Job                  *RepairJob `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JobQueuePopResponse) Reset()         { *m = JobQueuePopResponse{} }
func (m *JobQueuePopResponse) String() string { return proto.CompactTextString(m) }
func (*JobQueuePopResponse) ProtoMessage()    {}
func (*JobQueuePopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{6}
}
func (m *JobQueuePopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueuePopResponse.Unmarshal(m, b)
}
func (m *JobQueuePopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueuePopResponse.Marshal(b, m, deterministic)
}
func (m *JobQueuePopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueuePopResponse.Merge(m, src)
}
func (m *JobQueuePopResponse) XXX_Size() int {
	return xxx_messageInfo_JobQueuePopResponse.Size(m)
}
func (m *JobQueuePopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueuePopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueuePopResponse proto.InternalMessageInfo

func (m *JobQueuePopResponse) GetJob() *RepairJob {
	if m != nil {
		return m.Job
	}
	return nil
}

type JobQueuePeekRequest struct {
	Placement            int32    `protobuf:"varint,1,opt,name=placement,proto3" json:"placement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueuePeekRequest) Reset()         { *m = JobQueuePeekRequest{} }
func (m *JobQueuePeekRequest) String() string { return proto.CompactTextString(m) }
func (*JobQueuePeekRequest) ProtoMessage()    {}
func (*JobQueuePeekRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{7}
}
func (m *JobQueuePeekRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueuePeekRequest.Unmarshal(m, b)
}
func (m *JobQueuePeekRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueuePeekRequest.Marshal(b, m, deterministic)
}
func (m *JobQueuePeekRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueuePeekRequest.Merge(m, src)
}
func (m *JobQueuePeekRequest) XXX_Size() int {
	return xxx_messageInfo_JobQueuePeekRequest.Size(m)
}
func (m *JobQueuePeekRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueuePeekRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueuePeekRequest proto.InternalMessageInfo

func (m *JobQueuePeekRequest) GetPlacement() int32 {
	if m != nil {
		return m.Placement
	}
	return 0
}

type JobQueuePeekResponse struct {
	Job                  *RepairJob `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JobQueuePeekResponse) Reset()         { *m = JobQueuePeekResponse{} }
func (m *JobQueuePeekResponse) String() string { return proto.CompactTextString(m) }
func (*JobQueuePeekResponse) ProtoMessage()    {}
func (*JobQueuePeekResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{8}
}
func (m *JobQueuePeekResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueuePeekResponse.Unmarshal(m, b)
}
func (m *JobQueuePeekResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueuePeekResponse.Marshal(b, m, deterministic)
}
func (m *JobQueuePeekResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueuePeekResponse.Merge(m, src)
}
func (m *JobQueuePeekResponse) XXX_Size() int {
	return xxx_messageInfo_JobQueuePeekResponse.Size(m)
}
func (m *JobQueuePeekResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueuePeekResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueuePeekResponse proto.InternalMessageInfo

func (m *JobQueuePeekResponse) GetJob() *RepairJob {
	if m != nil {
		return m.Job
	}
	return nil
}

type JobQueueLengthRequest struct {
	Placement            int32    `protobuf:"varint,1,opt,name=placement,proto3" json:"placement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueueLengthRequest) Reset()         { *m = JobQueueLengthRequest{} }
func (m *JobQueueLengthRequest) String() string { return proto.CompactTextString(m) }
func (*JobQueueLengthRequest) ProtoMessage()    {}
func (*JobQueueLengthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{9}
}
func (m *JobQueueLengthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueLengthRequest.Unmarshal(m, b)
}
func (m *JobQueueLengthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueLengthRequest.Marshal(b, m, deterministic)
}
func (m *JobQueueLengthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueLengthRequest.Merge(m, src)
}
func (m *JobQueueLengthRequest) XXX_Size() int {
	return xxx_messageInfo_JobQueueLengthRequest.Size(m)
}
func (m *JobQueueLengthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueLengthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueLengthRequest proto.InternalMessageInfo

func (m *JobQueueLengthRequest) GetPlacement() int32 {
	if m != nil {
		return m.Placement
	}
	return 0
}

type JobQueueLengthResponse struct {
	RepairLength         int64    `protobuf:"varint,1,opt,name=repair_length,json=repairLength,proto3" json:"repair_length,omitempty"`
	RetryLength          int64    `protobuf:"varint,2,opt,name=retry_length,json=retryLength,proto3" json:"retry_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueueLengthResponse) Reset()         { *m = JobQueueLengthResponse{} }
func (m *JobQueueLengthResponse) String() string { return proto.CompactTextString(m) }
func (*JobQueueLengthResponse) ProtoMessage()    {}
func (*JobQueueLengthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{10}
}
func (m *JobQueueLengthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueLengthResponse.Unmarshal(m, b)
}
func (m *JobQueueLengthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueLengthResponse.Marshal(b, m, deterministic)
}
func (m *JobQueueLengthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueLengthResponse.Merge(m, src)
}
func (m *JobQueueLengthResponse) XXX_Size() int {
	return xxx_messageInfo_JobQueueLengthResponse.Size(m)
}
func (m *JobQueueLengthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueLengthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueLengthResponse proto.InternalMessageInfo

func (m *JobQueueLengthResponse) GetRepairLength() int64 {
	if m != nil {
		return m.RepairLength
	}
	return 0
}

func (m *JobQueueLengthResponse) GetRetryLength() int64 {
	if m != nil {
		return m.RetryLength
	}
	return 0
}

type JobQueueTruncateRequest struct {
	Placement            int32    `protobuf:"varint,1,opt,name=placement,proto3" json:"placement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueueTruncateRequest) Reset()         { *m = JobQueueTruncateRequest{} }
func (m *JobQueueTruncateRequest) String() string { return proto.CompactTextString(m) }
func (*JobQueueTruncateRequest) ProtoMessage()    {}
func (*JobQueueTruncateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{11}
}
func (m *JobQueueTruncateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueTruncateRequest.Unmarshal(m, b)
}
func (m *JobQueueTruncateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueTruncateRequest.Marshal(b, m, deterministic)
}
func (m *JobQueueTruncateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueTruncateRequest.Merge(m, src)
}
func (m *JobQueueTruncateRequest) XXX_Size() int {
	return xxx_messageInfo_JobQueueTruncateRequest.Size(m)
}
func (m *JobQueueTruncateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueTruncateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueTruncateRequest proto.InternalMessageInfo

func (m *JobQueueTruncateRequest) GetPlacement() int32 {
	if m != nil {
		return m.Placement
	}
	return 0
}

type JobQueueTruncateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueueTruncateResponse) Reset()         { *m = JobQueueTruncateResponse{} }
func (m *JobQueueTruncateResponse) String() string { return proto.CompactTextString(m) }
func (*JobQueueTruncateResponse) ProtoMessage()    {}
func (*JobQueueTruncateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{12}
}
func (m *JobQueueTruncateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueTruncateResponse.Unmarshal(m, b)
}
func (m *JobQueueTruncateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueTruncateResponse.Marshal(b, m, deterministic)
}
func (m *JobQueueTruncateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueTruncateResponse.Merge(m, src)
}
func (m *JobQueueTruncateResponse) XXX_Size() int {
	return xxx_messageInfo_JobQueueTruncateResponse.Size(m)
}
func (m *JobQueueTruncateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueTruncateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueTruncateResponse proto.InternalMessageInfo

type JobQueueAddPlacementQueueRequest struct {
	Placement            int32    `protobuf:"varint,1,opt,name=placement,proto3" json:"placement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueueAddPlacementQueueRequest) Reset()         { *m = JobQueueAddPlacementQueueRequest{} }
func (m *JobQueueAddPlacementQueueRequest) String() string { return proto.CompactTextString(m) }
func (*JobQueueAddPlacementQueueRequest) ProtoMessage()    {}
func (*JobQueueAddPlacementQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{13}
}
func (m *JobQueueAddPlacementQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueAddPlacementQueueRequest.Unmarshal(m, b)
}
func (m *JobQueueAddPlacementQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueAddPlacementQueueRequest.Marshal(b, m, deterministic)
}
func (m *JobQueueAddPlacementQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueAddPlacementQueueRequest.Merge(m, src)
}
func (m *JobQueueAddPlacementQueueRequest) XXX_Size() int {
	return xxx_messageInfo_JobQueueAddPlacementQueueRequest.Size(m)
}
func (m *JobQueueAddPlacementQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueAddPlacementQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueAddPlacementQueueRequest proto.InternalMessageInfo

func (m *JobQueueAddPlacementQueueRequest) GetPlacement() int32 {
	if m != nil {
		return m.Placement
	}
	return 0
}

type JobQueueAddPlacementQueueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueueAddPlacementQueueResponse) Reset()         { *m = JobQueueAddPlacementQueueResponse{} }
func (m *JobQueueAddPlacementQueueResponse) String() string { return proto.CompactTextString(m) }
func (*JobQueueAddPlacementQueueResponse) ProtoMessage()    {}
func (*JobQueueAddPlacementQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{14}
}
func (m *JobQueueAddPlacementQueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueAddPlacementQueueResponse.Unmarshal(m, b)
}
func (m *JobQueueAddPlacementQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueAddPlacementQueueResponse.Marshal(b, m, deterministic)
}
func (m *JobQueueAddPlacementQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueAddPlacementQueueResponse.Merge(m, src)
}
func (m *JobQueueAddPlacementQueueResponse) XXX_Size() int {
	return xxx_messageInfo_JobQueueAddPlacementQueueResponse.Size(m)
}
func (m *JobQueueAddPlacementQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueAddPlacementQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueAddPlacementQueueResponse proto.InternalMessageInfo

type JobQueueDestroyPlacementQueueRequest struct {
	Placement            int32    `protobuf:"varint,1,opt,name=placement,proto3" json:"placement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueueDestroyPlacementQueueRequest) Reset()         { *m = JobQueueDestroyPlacementQueueRequest{} }
func (m *JobQueueDestroyPlacementQueueRequest) String() string { return proto.CompactTextString(m) }
func (*JobQueueDestroyPlacementQueueRequest) ProtoMessage()    {}
func (*JobQueueDestroyPlacementQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{15}
}
func (m *JobQueueDestroyPlacementQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueDestroyPlacementQueueRequest.Unmarshal(m, b)
}
func (m *JobQueueDestroyPlacementQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueDestroyPlacementQueueRequest.Marshal(b, m, deterministic)
}
func (m *JobQueueDestroyPlacementQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueDestroyPlacementQueueRequest.Merge(m, src)
}
func (m *JobQueueDestroyPlacementQueueRequest) XXX_Size() int {
	return xxx_messageInfo_JobQueueDestroyPlacementQueueRequest.Size(m)
}
func (m *JobQueueDestroyPlacementQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueDestroyPlacementQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueDestroyPlacementQueueRequest proto.InternalMessageInfo

func (m *JobQueueDestroyPlacementQueueRequest) GetPlacement() int32 {
	if m != nil {
		return m.Placement
	}
	return 0
}

type JobQueueDestroyPlacementQueueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueueDestroyPlacementQueueResponse) Reset()         { *m = JobQueueDestroyPlacementQueueResponse{} }
func (m *JobQueueDestroyPlacementQueueResponse) String() string { return proto.CompactTextString(m) }
func (*JobQueueDestroyPlacementQueueResponse) ProtoMessage()    {}
func (*JobQueueDestroyPlacementQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{16}
}
func (m *JobQueueDestroyPlacementQueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueDestroyPlacementQueueResponse.Unmarshal(m, b)
}
func (m *JobQueueDestroyPlacementQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueDestroyPlacementQueueResponse.Marshal(b, m, deterministic)
}
func (m *JobQueueDestroyPlacementQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueDestroyPlacementQueueResponse.Merge(m, src)
}
func (m *JobQueueDestroyPlacementQueueResponse) XXX_Size() int {
	return xxx_messageInfo_JobQueueDestroyPlacementQueueResponse.Size(m)
}
func (m *JobQueueDestroyPlacementQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueDestroyPlacementQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueDestroyPlacementQueueResponse proto.InternalMessageInfo

type JobQueueInspectRequest struct {
	StreamId             []byte   `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Position             uint64   `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Placement            int32    `protobuf:"varint,3,opt,name=placement,proto3" json:"placement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueueInspectRequest) Reset()         { *m = JobQueueInspectRequest{} }
func (m *JobQueueInspectRequest) String() string { return proto.CompactTextString(m) }
func (*JobQueueInspectRequest) ProtoMessage()    {}
func (*JobQueueInspectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{17}
}
func (m *JobQueueInspectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueInspectRequest.Unmarshal(m, b)
}
func (m *JobQueueInspectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueInspectRequest.Marshal(b, m, deterministic)
}
func (m *JobQueueInspectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueInspectRequest.Merge(m, src)
}
func (m *JobQueueInspectRequest) XXX_Size() int {
	return xxx_messageInfo_JobQueueInspectRequest.Size(m)
}
func (m *JobQueueInspectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueInspectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueInspectRequest proto.InternalMessageInfo

func (m *JobQueueInspectRequest) GetStreamId() []byte {
	if m != nil {
		return m.StreamId
	}
	return nil
}

func (m *JobQueueInspectRequest) GetPosition() uint64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *JobQueueInspectRequest) GetPlacement() int32 {
	if m != nil {
		return m.Placement
	}
	return 0
}

type JobQueueInspectResponse struct {
	Job                  *RepairJob `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JobQueueInspectResponse) Reset()         { *m = JobQueueInspectResponse{} }
func (m *JobQueueInspectResponse) String() string { return proto.CompactTextString(m) }
func (*JobQueueInspectResponse) ProtoMessage()    {}
func (*JobQueueInspectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{18}
}
func (m *JobQueueInspectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueInspectResponse.Unmarshal(m, b)
}
func (m *JobQueueInspectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueInspectResponse.Marshal(b, m, deterministic)
}
func (m *JobQueueInspectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueInspectResponse.Merge(m, src)
}
func (m *JobQueueInspectResponse) XXX_Size() int {
	return xxx_messageInfo_JobQueueInspectResponse.Size(m)
}
func (m *JobQueueInspectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueInspectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueInspectResponse proto.InternalMessageInfo

func (m *JobQueueInspectResponse) GetJob() *RepairJob {
	if m != nil {
		return m.Job
	}
	return nil
}

type JobQueueCleanRequest struct {
	Placement            int32     `protobuf:"varint,1,opt,name=placement,proto3" json:"placement,omitempty"`
	UpdatedBefore        time.Time `protobuf:"bytes,2,opt,name=updated_before,json=updatedBefore,proto3,stdtime" json:"updated_before"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JobQueueCleanRequest) Reset()         { *m = JobQueueCleanRequest{} }
func (m *JobQueueCleanRequest) String() string { return proto.CompactTextString(m) }
func (*JobQueueCleanRequest) ProtoMessage()    {}
func (*JobQueueCleanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{19}
}
func (m *JobQueueCleanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueCleanRequest.Unmarshal(m, b)
}
func (m *JobQueueCleanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueCleanRequest.Marshal(b, m, deterministic)
}
func (m *JobQueueCleanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueCleanRequest.Merge(m, src)
}
func (m *JobQueueCleanRequest) XXX_Size() int {
	return xxx_messageInfo_JobQueueCleanRequest.Size(m)
}
func (m *JobQueueCleanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueCleanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueCleanRequest proto.InternalMessageInfo

func (m *JobQueueCleanRequest) GetPlacement() int32 {
	if m != nil {
		return m.Placement
	}
	return 0
}

func (m *JobQueueCleanRequest) GetUpdatedBefore() time.Time {
	if m != nil {
		return m.UpdatedBefore
	}
	return time.Time{}
}

type JobQueueCleanResponse struct {
	RemovedSegments      int32    `protobuf:"varint,1,opt,name=removed_segments,json=removedSegments,proto3" json:"removed_segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueueCleanResponse) Reset()         { *m = JobQueueCleanResponse{} }
func (m *JobQueueCleanResponse) String() string { return proto.CompactTextString(m) }
func (*JobQueueCleanResponse) ProtoMessage()    {}
func (*JobQueueCleanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{20}
}
func (m *JobQueueCleanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueCleanResponse.Unmarshal(m, b)
}
func (m *JobQueueCleanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueCleanResponse.Marshal(b, m, deterministic)
}
func (m *JobQueueCleanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueCleanResponse.Merge(m, src)
}
func (m *JobQueueCleanResponse) XXX_Size() int {
	return xxx_messageInfo_JobQueueCleanResponse.Size(m)
}
func (m *JobQueueCleanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueCleanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueCleanResponse proto.InternalMessageInfo

func (m *JobQueueCleanResponse) GetRemovedSegments() int32 {
	if m != nil {
		return m.RemovedSegments
	}
	return 0
}

type JobQueueTrimRequest struct {
	Placement            int32    `protobuf:"varint,1,opt,name=placement,proto3" json:"placement,omitempty"`
	HealthGreaterThan    float64  `protobuf:"fixed64,2,opt,name=health_greater_than,json=healthGreaterThan,proto3" json:"health_greater_than,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueueTrimRequest) Reset()         { *m = JobQueueTrimRequest{} }
func (m *JobQueueTrimRequest) String() string { return proto.CompactTextString(m) }
func (*JobQueueTrimRequest) ProtoMessage()    {}
func (*JobQueueTrimRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{21}
}
func (m *JobQueueTrimRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueTrimRequest.Unmarshal(m, b)
}
func (m *JobQueueTrimRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueTrimRequest.Marshal(b, m, deterministic)
}
func (m *JobQueueTrimRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueTrimRequest.Merge(m, src)
}
func (m *JobQueueTrimRequest) XXX_Size() int {
	return xxx_messageInfo_JobQueueTrimRequest.Size(m)
}
func (m *JobQueueTrimRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueTrimRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueTrimRequest proto.InternalMessageInfo

func (m *JobQueueTrimRequest) GetPlacement() int32 {
	if m != nil {
		return m.Placement
	}
	return 0
}

func (m *JobQueueTrimRequest) GetHealthGreaterThan() float64 {
	if m != nil {
		return m.HealthGreaterThan
	}
	return 0
}

type JobQueueTrimResponse struct {
	RemovedSegments      int32    `protobuf:"varint,1,opt,name=removed_segments,json=removedSegments,proto3" json:"removed_segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobQueueTrimResponse) Reset()         { *m = JobQueueTrimResponse{} }
func (m *JobQueueTrimResponse) String() string { return proto.CompactTextString(m) }
func (*JobQueueTrimResponse) ProtoMessage()    {}
func (*JobQueueTrimResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91545a11ba4fffbe, []int{22}
}
func (m *JobQueueTrimResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobQueueTrimResponse.Unmarshal(m, b)
}
func (m *JobQueueTrimResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobQueueTrimResponse.Marshal(b, m, deterministic)
}
func (m *JobQueueTrimResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobQueueTrimResponse.Merge(m, src)
}
func (m *JobQueueTrimResponse) XXX_Size() int {
	return xxx_messageInfo_JobQueueTrimResponse.Size(m)
}
func (m *JobQueueTrimResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobQueueTrimResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobQueueTrimResponse proto.InternalMessageInfo

func (m *JobQueueTrimResponse) GetRemovedSegments() int32 {
	if m != nil {
		return m.RemovedSegments
	}
	return 0
}

func init() {
	proto.RegisterType((*RepairJob)(nil), "jobqueue.RepairJob")
	proto.RegisterType((*JobQueuePushRequest)(nil), "jobqueue.JobQueuePushRequest")
	proto.RegisterType((*JobQueuePushResponse)(nil), "jobqueue.JobQueuePushResponse")
	proto.RegisterType((*JobQueuePushBatchRequest)(nil), "jobqueue.JobQueuePushBatchRequest")
	proto.RegisterType((*JobQueuePushBatchResponse)(nil), "jobqueue.JobQueuePushBatchResponse")
	proto.RegisterType((*JobQueuePopRequest)(nil), "jobqueue.JobQueuePopRequest")
	proto.RegisterType((*JobQueuePopResponse)(nil), "jobqueue.JobQueuePopResponse")
	proto.RegisterType((*JobQueuePeekRequest)(nil), "jobqueue.JobQueuePeekRequest")
	proto.RegisterType((*JobQueuePeekResponse)(nil), "jobqueue.JobQueuePeekResponse")
	proto.RegisterType((*JobQueueLengthRequest)(nil), "jobqueue.JobQueueLengthRequest")
	proto.RegisterType((*JobQueueLengthResponse)(nil), "jobqueue.JobQueueLengthResponse")
	proto.RegisterType((*JobQueueTruncateRequest)(nil), "jobqueue.JobQueueTruncateRequest")
	proto.RegisterType((*JobQueueTruncateResponse)(nil), "jobqueue.JobQueueTruncateResponse")
	proto.RegisterType((*JobQueueAddPlacementQueueRequest)(nil), "jobqueue.JobQueueAddPlacementQueueRequest")
	proto.RegisterType((*JobQueueAddPlacementQueueResponse)(nil), "jobqueue.JobQueueAddPlacementQueueResponse")
	proto.RegisterType((*JobQueueDestroyPlacementQueueRequest)(nil), "jobqueue.JobQueueDestroyPlacementQueueRequest")
	proto.RegisterType((*JobQueueDestroyPlacementQueueResponse)(nil), "jobqueue.JobQueueDestroyPlacementQueueResponse")
	proto.RegisterType((*JobQueueInspectRequest)(nil), "jobqueue.JobQueueInspectRequest")
	proto.RegisterType((*JobQueueInspectResponse)(nil), "jobqueue.JobQueueInspectResponse")
	proto.RegisterType((*JobQueueCleanRequest)(nil), "jobqueue.JobQueueCleanRequest")
	proto.RegisterType((*JobQueueCleanResponse)(nil), "jobqueue.JobQueueCleanResponse")
	proto.RegisterType((*JobQueueTrimRequest)(nil), "jobqueue.JobQueueTrimRequest")
	proto.RegisterType((*JobQueueTrimResponse)(nil), "jobqueue.JobQueueTrimResponse")
}

func init() { proto.RegisterFile("jobqueue.proto", fileDescriptor_91545a11ba4fffbe) }

var fileDescriptor_91545a11ba4fffbe = []byte{
	// 967 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x46, 0x71, 0x7e, 0xec, 0xe3, 0x24, 0x25, 0x9b, 0xb6, 0x18, 0xd1, 0x62, 0x47, 0x21, 0x53,
	0x03, 0x33, 0xf6, 0x4c, 0x3a, 0x0c, 0x37, 0x30, 0x53, 0x3b, 0xed, 0x40, 0x4a, 0xa1, 0xa9, 0xf0,
	0x15, 0x37, 0x42, 0xb2, 0x4f, 0x6c, 0xa5, 0xd2, 0xae, 0xaa, 0x5d, 0x95, 0xe6, 0x92, 0x37, 0xe0,
	0x92, 0x47, 0xe2, 0x86, 0x57, 0x80, 0x57, 0xe9, 0x68, 0xb5, 0x2b, 0xd9, 0xb1, 0xec, 0xda, 0xb9,
	0xb3, 0xce, 0xf9, 0xbe, 0x73, 0xbe, 0xdd, 0x73, 0xf6, 0x33, 0xec, 0x5f, 0x31, 0xef, 0x4d, 0x82,
	0x09, 0x76, 0xa2, 0x98, 0x09, 0x46, 0xaa, 0xfa, 0xdb, 0x84, 0x31, 0x1b, 0xb3, 0x2c, 0x6a, 0x36,
	0xc7, 0x8c, 0x8d, 0x03, 0xec, 0xca, 0x2f, 0x2f, 0xb9, 0xec, 0x0a, 0x3f, 0x44, 0x2e, 0xdc, 0x30,
	0xca, 0x00, 0xd6, 0xbf, 0x15, 0xa8, 0xd9, 0x18, 0xb9, 0x7e, 0xfc, 0x9c, 0x79, 0xe4, 0x33, 0xa8,
	0x71, 0x11, 0xa3, 0x1b, 0x3a, 0xfe, 0xa8, 0x61, 0xb4, 0x8c, 0xf6, 0xae, 0x5d, 0xcd, 0x02, 0xe7,
	0x23, 0x62, 0x42, 0x35, 0x62, 0xdc, 0x17, 0x3e, 0xa3, 0x8d, 0x8d, 0x96, 0xd1, 0xde, 0xb4, 0xf3,
	0x6f, 0x72, 0x1f, 0xb6, 0x27, 0xe8, 0x06, 0x62, 0xd2, 0xa8, 0xb4, 0x8c, 0xb6, 0x61, 0xab, 0x2f,
	0xf2, 0x0c, 0xea, 0x3e, 0xe5, 0x18, 0x0b, 0x1c, 0x39, 0xae, 0x68, 0x6c, 0xb6, 0x8c, 0x76, 0xfd,
	0xd4, 0xec, 0x64, 0xaa, 0x3a, 0x5a, 0x55, 0x67, 0xa0, 0x55, 0xf5, 0xab, 0xff, 0xfc, 0xd7, 0x34,
	0xfe, 0xfa, 0xbf, 0x69, 0xd8, 0xa0, 0x89, 0x3d, 0x41, 0x2e, 0xe0, 0x20, 0x70, 0xb9, 0x70, 0x5c,
	0x21, 0x30, 0x8c, 0x54, 0xb1, 0xad, 0x35, 0x8a, 0xdd, 0x49, 0xe9, 0x3d, 0xcd, 0xee, 0x09, 0x72,
	0x04, 0xbb, 0x34, 0x09, 0x75, 0x41, 0xde, 0xd8, 0x6e, 0x19, 0xed, 0x2d, 0xbb, 0x4e, 0x93, 0x50,
	0xa1, 0x38, 0x79, 0x00, 0xb5, 0x28, 0x70, 0x87, 0x18, 0x22, 0x15, 0x8d, 0x1d, 0x99, 0x2f, 0x02,
	0xa4, 0x09, 0x29, 0xd8, 0x09, 0x7d, 0xce, 0x7d, 0x3a, 0x6e, 0x54, 0x65, 0x1e, 0x68, 0x12, 0xfe,
	0x9c, 0x45, 0x48, 0x17, 0xee, 0xa6, 0x00, 0x96, 0x08, 0x87, 0x5d, 0x3a, 0x45, 0xa5, 0x9a, 0x44,
	0x1e, 0xd0, 0x24, 0x7c, 0x99, 0x88, 0x97, 0x97, 0x17, 0x79, 0xc5, 0x33, 0x80, 0x24, 0x1a, 0xb9,
	0xea, 0x74, 0xb0, 0xc6, 0xe9, 0x6a, 0x8a, 0xd7, 0x13, 0xd6, 0x77, 0x70, 0xf8, 0x9c, 0x79, 0xaf,
	0xd2, 0x45, 0xb8, 0x48, 0xf8, 0xc4, 0xc6, 0x37, 0x09, 0x72, 0x41, 0x4e, 0xa0, 0x72, 0xc5, 0x3c,
	0x39, 0xd2, 0xfa, 0xe9, 0x61, 0x27, 0xdf, 0x9d, 0x7c, 0xf4, 0x76, 0x9a, 0xb7, 0xbe, 0x87, 0xbb,
	0xb3, 0x6c, 0x1e, 0x31, 0xca, 0x91, 0x9c, 0xc0, 0x3e, 0xc5, 0x3f, 0x82, 0x6b, 0x47, 0xcf, 0x44,
	0x56, 0xaa, 0xda, 0x7b, 0x32, 0x7a, 0xae, 0x82, 0xd6, 0x19, 0x34, 0xa6, 0xe9, 0x7d, 0x57, 0x0c,
	0x73, 0x05, 0x8f, 0x60, 0xf3, 0x8a, 0x79, 0xbc, 0x61, 0xb4, 0x2a, 0x8b, 0x24, 0x48, 0x80, 0xd5,
	0x87, 0x4f, 0x4b, 0x8a, 0x2c, 0x11, 0x52, 0x99, 0x17, 0xf2, 0x16, 0x48, 0x5e, 0x83, 0x45, 0x5a,
	0x42, 0x17, 0x0e, 0x7d, 0x3a, 0x0c, 0x92, 0x11, 0x8e, 0x8a, 0x79, 0x64, 0x8a, 0xb6, 0x6c, 0xa2,
	0x53, 0xf9, 0x40, 0x78, 0x4a, 0xc0, 0x77, 0xf3, 0x84, 0x8d, 0x8c, 0xa0, 0x53, 0x05, 0x61, 0xe6,
	0xf6, 0xd3, 0xbe, 0xb9, 0xea, 0x95, 0x6e, 0xff, 0xf1, 0x14, 0x1b, 0xf1, 0xb5, 0x96, 0x3d, 0xb3,
	0x87, 0xc6, 0x8d, 0x3d, 0x9c, 0x19, 0x99, 0x24, 0xad, 0xd7, 0xf3, 0x1b, 0xb8, 0xa7, 0xe9, 0x2f,
	0x90, 0x8e, 0xc5, 0x64, 0xb5, 0xae, 0xbf, 0xc3, 0xfd, 0x9b, 0x34, 0xd5, 0xf7, 0x18, 0xf6, 0x62,
	0xd9, 0xc2, 0x09, 0x64, 0x42, 0x72, 0x2b, 0xf6, 0x6e, 0x16, 0xcc, 0xc0, 0xe9, 0xeb, 0x8b, 0x51,
	0xc4, 0xd7, 0x1a, 0xb3, 0x21, 0x31, 0x75, 0x19, 0xcb, 0x20, 0xd6, 0xb7, 0xf0, 0x89, 0xee, 0x30,
	0x88, 0x13, 0x3a, 0x74, 0x05, 0xae, 0x26, 0xcd, 0x2c, 0x96, 0xb0, 0x20, 0x66, 0xe2, 0xac, 0x27,
	0xd0, 0xd2, 0xb9, 0xde, 0xa8, 0x18, 0x9c, 0x0c, 0xac, 0x56, 0xfd, 0x18, 0x8e, 0x96, 0x54, 0x50,
	0x6d, 0x9e, 0xc2, 0x17, 0x1a, 0xf4, 0x14, 0xb9, 0x88, 0xd9, 0xf5, 0x6d, 0x5a, 0x3d, 0x82, 0x93,
	0x0f, 0x54, 0x51, 0xed, 0x58, 0x31, 0x8c, 0x73, 0xca, 0x23, 0x1c, 0x0a, 0xdd, 0xe0, 0xd6, 0x7e,
	0x3e, 0xa3, 0xac, 0x72, 0x53, 0xd9, 0x93, 0x62, 0x36, 0x79, 0xc3, 0xf5, 0xd6, 0xee, 0x4f, 0xa3,
	0x58, 0xdb, 0xb3, 0x00, 0x5d, 0xba, 0xd2, 0x95, 0x90, 0x9f, 0x60, 0x5f, 0x5b, 0xa4, 0x87, 0x97,
	0x2c, 0x46, 0x29, 0xfc, 0xc3, 0x36, 0xf9, 0x91, 0xb4, 0xc9, 0x3d, 0xc5, 0xed, 0x4b, 0xaa, 0xd5,
	0x2f, 0x56, 0x5f, 0x49, 0x50, 0x67, 0xf8, 0x12, 0x3e, 0x8e, 0x31, 0x64, 0x6f, 0x71, 0xe4, 0x70,
	0x1c, 0x6b, 0x93, 0x48, 0xa5, 0xdc, 0x51, 0xf1, 0x5f, 0x55, 0xd8, 0x1a, 0x16, 0x4f, 0x76, 0x10,
	0xfb, 0xe1, 0x6a, 0xa7, 0xe8, 0xc0, 0x61, 0xf6, 0xf7, 0xe8, 0x8c, 0x63, 0x74, 0x05, 0xc6, 0x8e,
	0x98, 0xb8, 0xd9, 0x0c, 0x0c, 0xfb, 0x20, 0x4b, 0xfd, 0x90, 0x65, 0x06, 0x13, 0x97, 0x5a, 0xbd,
	0xe2, 0xae, 0xb2, 0x26, 0x6b, 0xeb, 0x3c, 0xfd, 0x7b, 0x07, 0xaa, 0xba, 0x06, 0x79, 0x06, 0x9b,
	0xa9, 0xb3, 0x92, 0x87, 0xc5, 0x78, 0x4a, 0xfe, 0x33, 0xcc, 0xcf, 0x17, 0xa5, 0x55, 0xfb, 0x01,
	0xd4, 0x72, 0x83, 0x26, 0x56, 0x39, 0x78, 0xfa, 0x2f, 0xc0, 0x3c, 0x5e, 0x8a, 0x51, 0x55, 0xfb,
	0x50, 0xb9, 0x60, 0x11, 0x79, 0x50, 0x82, 0xcd, 0x9d, 0xdc, 0x7c, 0xb8, 0x20, 0xab, 0x6a, 0xa4,
	0x07, 0x44, 0x7c, 0x5d, 0x7a, 0xc0, 0xc2, 0x58, 0x4b, 0x0f, 0x38, 0x6d, 0xa1, 0x3f, 0x42, 0xe5,
	0x05, 0x52, 0xd2, 0x9c, 0x87, 0xcd, 0x58, 0xa5, 0xd9, 0x5a, 0x0c, 0x50, 0x95, 0x7e, 0x81, 0x1d,
	0xf5, 0x50, 0x48, 0x09, 0x78, 0xf6, 0xd1, 0x9a, 0x47, 0x4b, 0x10, 0xaa, 0xde, 0x2b, 0xa8, 0x6a,
	0x6f, 0x23, 0x25, 0xf0, 0x1b, 0x86, 0x69, 0x5a, 0xcb, 0x20, 0xaa, 0x64, 0x00, 0x07, 0x73, 0x86,
	0x46, 0xbe, 0x9a, 0x27, 0x2e, 0xf2, 0x4d, 0xf3, 0xeb, 0x95, 0xb0, 0xaa, 0xdb, 0x3b, 0xb8, 0x57,
	0xea, 0x69, 0xa4, 0x33, 0x5f, 0x65, 0x99, 0x85, 0x9a, 0xdd, 0x95, 0xf1, 0xf9, 0x50, 0xb7, 0xe4,
	0x6b, 0x27, 0x25, 0xd3, 0x9f, 0x76, 0x22, 0xb3, 0xb9, 0x30, 0x5f, 0x6c, 0x59, 0xfa, 0x1c, 0xcb,
	0xb6, 0x6c, 0xca, 0x0b, 0xca, 0xb6, 0x6c, 0xfa, 0x15, 0xf7, 0x4f, 0x7e, 0x3b, 0xe6, 0x82, 0xc5,
	0x57, 0x1d, 0x9f, 0x75, 0xe5, 0x8f, 0x2e, 0x77, 0x05, 0x06, 0x81, 0x2f, 0xb0, 0xeb, 0x53, 0x81,
	0x31, 0x75, 0x83, 0xc8, 0xf3, 0xb6, 0xa5, 0xb5, 0x3d, 0x7e, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x4f,
	0x49, 0x81, 0x28, 0xf8, 0x0b, 0x00, 0x00,
}
