// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metabase.proto

package internalpb

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"

	pb "storj.io/common/pb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BucketTags struct {
	Tags                 []*pb.BucketTag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BucketTags) Reset()         { *m = BucketTags{} }
func (m *BucketTags) String() string { return proto.CompactTextString(m) }
func (*BucketTags) ProtoMessage()    {}
func (*BucketTags) Descriptor() ([]byte, []int) {
	return fileDescriptor_f844e5807e1b0d2d, []int{0}
}
func (m *BucketTags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketTags.Unmarshal(m, b)
}
func (m *BucketTags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketTags.Marshal(b, m, deterministic)
}
func (m *BucketTags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketTags.Merge(m, src)
}
func (m *BucketTags) XXX_Size() int {
	return xxx_messageInfo_BucketTags.Size(m)
}
func (m *BucketTags) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketTags.DiscardUnknown(m)
}

var xxx_messageInfo_BucketTags proto.InternalMessageInfo

func (m *BucketTags) GetTags() []*pb.BucketTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ObjectChecksum struct {
	Algorithm            pb.ObjectChecksumAlgorithm `protobuf:"varint,1,opt,name=algorithm,proto3,enum=metainfo.ObjectChecksumAlgorithm" json:"algorithm,omitempty"`
	IsComposite          bool                       `protobuf:"varint,2,opt,name=is_composite,json=isComposite,proto3" json:"is_composite,omitempty"`
	EncryptedValue       []byte                     `protobuf:"bytes,3,opt,name=encrypted_value,json=encryptedValue,proto3" json:"encrypted_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ObjectChecksum) Reset()         { *m = ObjectChecksum{} }
func (m *ObjectChecksum) String() string { return proto.CompactTextString(m) }
func (*ObjectChecksum) ProtoMessage()    {}
func (*ObjectChecksum) Descriptor() ([]byte, []int) {
	return fileDescriptor_f844e5807e1b0d2d, []int{1}
}
func (m *ObjectChecksum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectChecksum.Unmarshal(m, b)
}
func (m *ObjectChecksum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectChecksum.Marshal(b, m, deterministic)
}
func (m *ObjectChecksum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectChecksum.Merge(m, src)
}
func (m *ObjectChecksum) XXX_Size() int {
	return xxx_messageInfo_ObjectChecksum.Size(m)
}
func (m *ObjectChecksum) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectChecksum.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectChecksum proto.InternalMessageInfo

func (m *ObjectChecksum) GetAlgorithm() pb.ObjectChecksumAlgorithm {
	if m != nil {
		return m.Algorithm
	}
	return pb.ObjectChecksumAlgorithm_NONE
}

func (m *ObjectChecksum) GetIsComposite() bool {
	if m != nil {
		return m.IsComposite
	}
	return false
}

func (m *ObjectChecksum) GetEncryptedValue() []byte {
	if m != nil {
		return m.EncryptedValue
	}
	return nil
}

func init() {
	proto.RegisterType((*BucketTags)(nil), "satellite.metabase.BucketTags")
	proto.RegisterType((*ObjectChecksum)(nil), "satellite.metabase.ObjectChecksum")
}

func init() { proto.RegisterFile("metabase.proto", fileDescriptor_f844e5807e1b0d2d) }

var fileDescriptor_f844e5807e1b0d2d = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x06, 0x60, 0xd6, 0x8a, 0xe8, 0xb6, 0x44, 0x58, 0x2f, 0xc1, 0x53, 0x5a, 0x91, 0xe6, 0x94,
	0x40, 0xc5, 0xb3, 0xd8, 0x3e, 0x80, 0x10, 0xc4, 0x83, 0x97, 0xb2, 0x59, 0xc7, 0x74, 0xda, 0x4d,
	0x26, 0xec, 0x4c, 0x04, 0x1f, 0xc6, 0x77, 0x15, 0x23, 0x49, 0xe9, 0x6d, 0xf8, 0xe7, 0x9b, 0x39,
	0xfc, 0x3a, 0xaa, 0x41, 0x6c, 0x69, 0x19, 0xb2, 0x36, 0x90, 0x90, 0x31, 0x6c, 0x05, 0xbc, 0x47,
	0x81, 0x6c, 0xd8, 0xdc, 0xf6, 0x06, 0x9b, 0x4f, 0xfa, 0x37, 0x8b, 0x47, 0xad, 0xd7, 0x9d, 0x3b,
	0x80, 0xbc, 0xda, 0x8a, 0xcd, 0x52, 0x9f, 0x8b, 0xad, 0x38, 0x56, 0xc9, 0x24, 0x9d, 0xae, 0x6e,
	0xb2, 0x11, 0x8f, 0xa6, 0xe8, 0xc1, 0xe2, 0x47, 0xe9, 0xe8, 0xa5, 0xdc, 0x83, 0x93, 0xcd, 0x0e,
	0xdc, 0x81, 0xbb, 0xda, 0x3c, 0xe9, 0x2b, 0xeb, 0x2b, 0x0a, 0x28, 0xbb, 0x3a, 0x56, 0x89, 0x4a,
	0xa3, 0xd5, 0xfc, 0xf8, 0xe0, 0x14, 0x3f, 0x0f, 0xb0, 0x38, 0xde, 0x98, 0xb9, 0x9e, 0x21, 0x6f,
	0x1d, 0xd5, 0x2d, 0x31, 0x0a, 0xc4, 0x67, 0x89, 0x4a, 0x2f, 0x8b, 0x29, 0xf2, 0x66, 0x88, 0xcc,
	0x52, 0x5f, 0x43, 0xe3, 0xc2, 0x77, 0x2b, 0xf0, 0xb1, 0xfd, 0xb2, 0xbe, 0x83, 0x78, 0x92, 0xa8,
	0x74, 0x56, 0x44, 0x63, 0xfc, 0xf6, 0x97, 0xae, 0xef, 0xdf, 0xef, 0x58, 0x28, 0xec, 0x33, 0xa4,
	0xbc, 0x1f, 0xf2, 0xb1, 0x8b, 0x1c, 0x1b, 0x81, 0xd0, 0x58, 0xdf, 0x96, 0xe5, 0x45, 0x5f, 0xc2,
	0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x63, 0xc7, 0x4e, 0x3a, 0x01, 0x00, 0x00,
}
