#!/bin/sh
set -euo pipefail

if [[ ! -f "${CONF_PATH}/config.yaml" ]]; then
	./gateway setup
fi

RUN_PARAMS="${RUN_PARAMS:-} --config-dir ${CONF_PATH}"

if [[ -n "${API_KEY:-}" ]]; then
	RUN_PARAMS="${RUN_PARAMS} --client.api-key ${API_KEY}"
fi

if [ -n "${SATELLITE_ADDR:-}" ]; then
	RUN_PARAMS="${RUN_PARAMS} --client.overlay-addr $SATELLITE_ADDR"
	RUN_PARAMS="${RUN_PARAMS} --client.pointer-db-addr $SATELLITE_ADDR"
fi

exec ./gateway run $RUN_PARAMS "$@"
