# syntax=docker/dockerfile:1.4-labs
ARG GO_VERSION="1.25.6"

# ca-cert downloads certificates in a separate stage to
# avoid needing to download it for different target platforms.
# Similarly, it avoids the apt cache.
FROM --platform=$BUILDPLATFORM debian:trixie-slim AS ca-cert

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates
RUN update-ca-certificates

FROM debian:trixie-slim

ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

COPY --from=ca-cert /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

COPY --from=storj-up /${TARGETOS}_${TARGETARCH}/storj-up /usr/local/bin/storj-up
COPY --from=delve    /${TARGETOS}_${TARGETARCH}/dlv      /usr/local/bin/dlv

COPY --from=binaries /${TARGETOS}_${TARGETARCH}/storagenode /app/storagenode
COPY --from=binaries /${TARGETOS}_${TARGETARCH}/identity /app/identity
COPY --from=ui / /app/static

COPY cmd/storagenode/entrypoint /app/entrypoint

ENTRYPOINT ["/app/entrypoint"]
