ARG DOCKER_ARCH
ARG GO_VERSION=1.24
# Storagenode UI static asset generation
FROM node:24.11.1 as ui
WORKDIR /app
COPY web/storagenode/ /app
RUN ./build.sh

# Fetch ca-certificates file for arch independent builds below
FROM debian:buster-slim as ca-cert
RUN echo "deb http://archive.debian.org/debian buster main\ndeb http://archive.debian.org/debian-security buster/updates main\ndeb http://archive.debian.org/debian buster-updates main " >/etc/apt/sources.list
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates
RUN update-ca-certificates

# Install storj-up helper (for local/dev runs)
FROM --platform=$TARGETPLATFORM golang:$GO_VERSION AS storjup
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod  \
    CGO_ENABLED=0 go install storj.io/storj-up@latest

# Install dlv (for local/dev runs)
FROM --platform=$TARGETPLATFORM golang:$GO_VERSION AS dlv
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod  \
    go install github.com/go-delve/delve/cmd/dlv@latest

FROM ${DOCKER_ARCH:-amd64}/debian:buster-slim
ARG TAG
ARG GOARCH
ENV GOARCH ${GOARCH}
ENV PATH=$PATH:/app
WORKDIR /app
COPY --from=ui /app/static /app/static
COPY --from=ca-cert /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY release/${TAG}/storagenode_linux_${GOARCH:-amd64} /app/storagenode
COPY release/${TAG}/identity_linux_${GOARCH:-amd64} /app/identity
COPY --from=storjup /go/bin/storj-up /usr/local/bin/storj-up
COPY --from=dlv /go/bin/dlv /usr/local/bin/dlv
COPY cmd/storagenode/entrypoint /entrypoint
ENTRYPOINT ["/entrypoint"]
