ARG DOCKER_ARCH

FROM ${DOCKER_ARCH:-amd64}/alpine:3.15
RUN apk --no-cache -U add ca-certificates supervisor
RUN mkdir -p /var/log/supervisor /app
COPY cmd/storagenode/docker-base/ /
RUN chmod a+rw /etc/supervisor/supervisord.conf /app