// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nodereputation.proto

package nodereputation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryStatus int32

const (
	QueryStatus_NODE_FOUND     QueryStatus = 0
	QueryStatus_NODE_NOT_FOUND QueryStatus = 1
)

var QueryStatus_name = map[int32]string{
	0: "NODE_FOUND",
	1: "NODE_NOT_FOUND",
}
var QueryStatus_value = map[string]int32{
	"NODE_FOUND":     0,
	"NODE_NOT_FOUND": 1,
}

func (x QueryStatus) String() string {
	return proto.EnumName(QueryStatus_name, int32(x))
}
func (QueryStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{0}
}

type ConstraintStatus int32

const (
	ConstraintStatus_LIMIT_MEET     ConstraintStatus = 0
	ConstraintStatus_LIMIT_NOT_MEET ConstraintStatus = 1
)

var ConstraintStatus_name = map[int32]string{
	0: "LIMIT_MEET",
	1: "LIMIT_NOT_MEET",
}
var ConstraintStatus_value = map[string]int32{
	"LIMIT_MEET":     0,
	"LIMIT_NOT_MEET": 1,
}

func (x ConstraintStatus) String() string {
	return proto.EnumName(ConstraintStatus_name, int32(x))
}
func (ConstraintStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{1}
}

type UpdateStatus int32

const (
	UpdateStatus_UPDATE_SUCCESS UpdateStatus = 0
	UpdateStatus_UPDATE_FAILED  UpdateStatus = 1
)

var UpdateStatus_name = map[int32]string{
	0: "UPDATE_SUCCESS",
	1: "UPDATE_FAILED",
}
var UpdateStatus_value = map[string]int32{
	"UPDATE_SUCCESS": 0,
	"UPDATE_FAILED":  1,
}

func (x UpdateStatus) String() string {
	return proto.EnumName(UpdateStatus_name, int32(x))
}
func (UpdateStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{2}
}

type Feature int32

const (
	Feature_UPTIME                Feature = 0
	Feature_AUDIT                 Feature = 1
	Feature_LATENCY               Feature = 2
	Feature_AMOUNT_OF_DATA_STORED Feature = 3
	Feature_FALSE_CLAIMS          Feature = 4
	Feature_SHARDS_MODIFIED       Feature = 5
)

var Feature_name = map[int32]string{
	0: "UPTIME",
	1: "AUDIT",
	2: "LATENCY",
	3: "AMOUNT_OF_DATA_STORED",
	4: "FALSE_CLAIMS",
	5: "SHARDS_MODIFIED",
}
var Feature_value = map[string]int32{
	"UPTIME":                0,
	"AUDIT":                 1,
	"LATENCY":               2,
	"AMOUNT_OF_DATA_STORED": 3,
	"FALSE_CLAIMS":          4,
	"SHARDS_MODIFIED":       5,
}

func (x Feature) String() string {
	return proto.EnumName(Feature_name, int32(x))
}
func (Feature) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{3}
}

type UpdateRepValue int32

const (
	UpdateRepValue_NEGATIVE_ONE               UpdateRepValue = 0
	UpdateRepValue_NEGATIVE_POINT_FIVE        UpdateRepValue = 1
	UpdateRepValue_NEGATIVE_POINT_TWENTY_FIVE UpdateRepValue = 2
	UpdateRepValue_ZERO                       UpdateRepValue = 3
	UpdateRepValue_POINT_TWENTY_FIVE          UpdateRepValue = 4
	UpdateRepValue_POINT_FIVE                 UpdateRepValue = 5
	UpdateRepValue_ONE                        UpdateRepValue = 6
)

var UpdateRepValue_name = map[int32]string{
	0: "NEGATIVE_ONE",
	1: "NEGATIVE_POINT_FIVE",
	2: "NEGATIVE_POINT_TWENTY_FIVE",
	3: "ZERO",
	4: "POINT_TWENTY_FIVE",
	5: "POINT_FIVE",
	6: "ONE",
}
var UpdateRepValue_value = map[string]int32{
	"NEGATIVE_ONE":               0,
	"NEGATIVE_POINT_FIVE":        1,
	"NEGATIVE_POINT_TWENTY_FIVE": 2,
	"ZERO":              3,
	"POINT_TWENTY_FIVE": 4,
	"POINT_FIVE":        5,
	"ONE":               6,
}

func (x UpdateRepValue) String() string {
	return proto.EnumName(UpdateRepValue_name, int32(x))
}
func (UpdateRepValue) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{4}
}

type Parameter int32

const (
	Parameter_GOOD_RECALL        Parameter = 0
	Parameter_BAD_RECALL         Parameter = 1
	Parameter_WEIGHT_DENOMINATOR Parameter = 2
)

var Parameter_name = map[int32]string{
	0: "GOOD_RECALL",
	1: "BAD_RECALL",
	2: "WEIGHT_DENOMINATOR",
}
var Parameter_value = map[string]int32{
	"GOOD_RECALL":        0,
	"BAD_RECALL":         1,
	"WEIGHT_DENOMINATOR": 2,
}

func (x Parameter) String() string {
	return proto.EnumName(Parameter_name, int32(x))
}
func (Parameter) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{5}
}

type BetaStateCols int32

const (
	BetaStateCols_FEATURE_COUNTER           BetaStateCols = 0
	BetaStateCols_CUMULATIVE_SUM_REPUTATION BetaStateCols = 1
	BetaStateCols_CURRENT_REPUTATION        BetaStateCols = 2
)

var BetaStateCols_name = map[int32]string{
	0: "FEATURE_COUNTER",
	1: "CUMULATIVE_SUM_REPUTATION",
	2: "CURRENT_REPUTATION",
}
var BetaStateCols_value = map[string]int32{
	"FEATURE_COUNTER":           0,
	"CUMULATIVE_SUM_REPUTATION": 1,
	"CURRENT_REPUTATION":        2,
}

func (x BetaStateCols) String() string {
	return proto.EnumName(BetaStateCols_name, int32(x))
}
func (BetaStateCols) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{6}
}

type Operand int32

const (
	Operand_EQUAL_TO              Operand = 0
	Operand_GREATER_THAN          Operand = 1
	Operand_GREATER_THAN_EQUAL_TO Operand = 2
	Operand_LESS_THAN             Operand = 3
	Operand_LESS_THAN_EQUAL_TO    Operand = 4
	Operand_NOT_EQUAL_TO          Operand = 5
)

var Operand_name = map[int32]string{
	0: "EQUAL_TO",
	1: "GREATER_THAN",
	2: "GREATER_THAN_EQUAL_TO",
	3: "LESS_THAN",
	4: "LESS_THAN_EQUAL_TO",
	5: "NOT_EQUAL_TO",
}
var Operand_value = map[string]int32{
	"EQUAL_TO":              0,
	"GREATER_THAN":          1,
	"GREATER_THAN_EQUAL_TO": 2,
	"LESS_THAN":             3,
	"LESS_THAN_EQUAL_TO":    4,
	"NOT_EQUAL_TO":          5,
}

func (x Operand) String() string {
	return proto.EnumName(Operand_name, int32(x))
}
func (Operand) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{7}
}

// GetRequest is a list of node ids
type GetRequest struct {
	Nodes                []string `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{0}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// GetResponse is a list of (node id, status, scores)
type GetResponse struct {
	Records              []*NodeReputationQueryStatus `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{1}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetRecords() []*NodeReputationQueryStatus {
	if m != nil {
		return m.Records
	}
	return nil
}

// MatchRequest is a request with a limit of node ids to return, ranked order of features, and node ids not to select
type MatchRequest struct {
	Limit                int64     `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	FeatureOrdering      []Feature `protobuf:"varint,2,rep,packed,name=featureOrdering,enum=nodereputation.Feature" json:"featureOrdering,omitempty"`
	Excluding            []string  `protobuf:"bytes,3,rep,name=excluding" json:"excluding,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MatchRequest) Reset()         { *m = MatchRequest{} }
func (m *MatchRequest) String() string { return proto.CompactTextString(m) }
func (*MatchRequest) ProtoMessage()    {}
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{2}
}
func (m *MatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchRequest.Unmarshal(m, b)
}
func (m *MatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchRequest.Marshal(b, m, deterministic)
}
func (dst *MatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchRequest.Merge(dst, src)
}
func (m *MatchRequest) XXX_Size() int {
	return xxx_messageInfo_MatchRequest.Size(m)
}
func (m *MatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MatchRequest proto.InternalMessageInfo

func (m *MatchRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *MatchRequest) GetFeatureOrdering() []Feature {
	if m != nil {
		return m.FeatureOrdering
	}
	return nil
}

func (m *MatchRequest) GetExcluding() []string {
	if m != nil {
		return m.Excluding
	}
	return nil
}

// MatchRepsonse tells if the limit was meet and node ids that have the "best" features
type MatchResponse struct {
	Status               ConstraintStatus `protobuf:"varint,1,opt,name=status,enum=nodereputation.ConstraintStatus" json:"status,omitempty"`
	Nodes                []string         `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MatchResponse) Reset()         { *m = MatchResponse{} }
func (m *MatchResponse) String() string { return proto.CompactTextString(m) }
func (*MatchResponse) ProtoMessage()    {}
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{3}
}
func (m *MatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchResponse.Unmarshal(m, b)
}
func (m *MatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchResponse.Marshal(b, m, deterministic)
}
func (dst *MatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchResponse.Merge(dst, src)
}
func (m *MatchResponse) XXX_Size() int {
	return xxx_messageInfo_MatchResponse.Size(m)
}
func (m *MatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MatchResponse proto.InternalMessageInfo

func (m *MatchResponse) GetStatus() ConstraintStatus {
	if m != nil {
		return m.Status
	}
	return ConstraintStatus_LIMIT_MEET
}

func (m *MatchResponse) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// UpdateRequest is a list of node and features
type UpdateRequest struct {
	Update               []*NodeReputationUpdate `protobuf:"bytes,1,rep,name=update" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{4}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUpdate() []*NodeReputationUpdate {
	if m != nil {
		return m.Update
	}
	return nil
}

// UpdateResponse list of successful/failed updates for node feature pairs
type UpdateResponse struct {
	Update               []*NodeReputationUpdateStatus `protobuf:"bytes,1,rep,name=update" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{5}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(dst, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetUpdate() []*NodeReputationUpdateStatus {
	if m != nil {
		return m.Update
	}
	return nil
}

// NodeReputationQueryStatus tells if a node id was found (status), if so the scores for all the features
type NodeReputationQueryStatus struct {
	NodeId               string               `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	Status               QueryStatus          `protobuf:"varint,2,opt,name=status,enum=nodereputation.QueryStatus" json:"status,omitempty"`
	Scores               []*FeatureReputation `protobuf:"bytes,3,rep,name=scores" json:"scores,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NodeReputationQueryStatus) Reset()         { *m = NodeReputationQueryStatus{} }
func (m *NodeReputationQueryStatus) String() string { return proto.CompactTextString(m) }
func (*NodeReputationQueryStatus) ProtoMessage()    {}
func (*NodeReputationQueryStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{6}
}
func (m *NodeReputationQueryStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeReputationQueryStatus.Unmarshal(m, b)
}
func (m *NodeReputationQueryStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeReputationQueryStatus.Marshal(b, m, deterministic)
}
func (dst *NodeReputationQueryStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeReputationQueryStatus.Merge(dst, src)
}
func (m *NodeReputationQueryStatus) XXX_Size() int {
	return xxx_messageInfo_NodeReputationQueryStatus.Size(m)
}
func (m *NodeReputationQueryStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeReputationQueryStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NodeReputationQueryStatus proto.InternalMessageInfo

func (m *NodeReputationQueryStatus) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *NodeReputationQueryStatus) GetStatus() QueryStatus {
	if m != nil {
		return m.Status
	}
	return QueryStatus_NODE_FOUND
}

func (m *NodeReputationQueryStatus) GetScores() []*FeatureReputation {
	if m != nil {
		return m.Scores
	}
	return nil
}

// NodeReputationUpdate request a feature update with a value for a given node
type NodeReputationUpdate struct {
	NodeId               string         `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	Feature              Feature        `protobuf:"varint,2,opt,name=feature,enum=nodereputation.Feature" json:"feature,omitempty"`
	Value                UpdateRepValue `protobuf:"varint,3,opt,name=value,enum=nodereputation.UpdateRepValue" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NodeReputationUpdate) Reset()         { *m = NodeReputationUpdate{} }
func (m *NodeReputationUpdate) String() string { return proto.CompactTextString(m) }
func (*NodeReputationUpdate) ProtoMessage()    {}
func (*NodeReputationUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{7}
}
func (m *NodeReputationUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeReputationUpdate.Unmarshal(m, b)
}
func (m *NodeReputationUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeReputationUpdate.Marshal(b, m, deterministic)
}
func (dst *NodeReputationUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeReputationUpdate.Merge(dst, src)
}
func (m *NodeReputationUpdate) XXX_Size() int {
	return xxx_messageInfo_NodeReputationUpdate.Size(m)
}
func (m *NodeReputationUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeReputationUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_NodeReputationUpdate proto.InternalMessageInfo

func (m *NodeReputationUpdate) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *NodeReputationUpdate) GetFeature() Feature {
	if m != nil {
		return m.Feature
	}
	return Feature_UPTIME
}

func (m *NodeReputationUpdate) GetValue() UpdateRepValue {
	if m != nil {
		return m.Value
	}
	return UpdateRepValue_NEGATIVE_ONE
}

// NodeReputationUpdataStatus tells if a value was set for a node's feature
type NodeReputationUpdateStatus struct {
	NodeId               string       `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	Feature              Feature      `protobuf:"varint,2,opt,name=feature,enum=nodereputation.Feature" json:"feature,omitempty"`
	Status               UpdateStatus `protobuf:"varint,3,opt,name=status,enum=nodereputation.UpdateStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NodeReputationUpdateStatus) Reset()         { *m = NodeReputationUpdateStatus{} }
func (m *NodeReputationUpdateStatus) String() string { return proto.CompactTextString(m) }
func (*NodeReputationUpdateStatus) ProtoMessage()    {}
func (*NodeReputationUpdateStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{8}
}
func (m *NodeReputationUpdateStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeReputationUpdateStatus.Unmarshal(m, b)
}
func (m *NodeReputationUpdateStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeReputationUpdateStatus.Marshal(b, m, deterministic)
}
func (dst *NodeReputationUpdateStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeReputationUpdateStatus.Merge(dst, src)
}
func (m *NodeReputationUpdateStatus) XXX_Size() int {
	return xxx_messageInfo_NodeReputationUpdateStatus.Size(m)
}
func (m *NodeReputationUpdateStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeReputationUpdateStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NodeReputationUpdateStatus proto.InternalMessageInfo

func (m *NodeReputationUpdateStatus) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *NodeReputationUpdateStatus) GetFeature() Feature {
	if m != nil {
		return m.Feature
	}
	return Feature_UPTIME
}

func (m *NodeReputationUpdateStatus) GetStatus() UpdateStatus {
	if m != nil {
		return m.Status
	}
	return UpdateStatus_UPDATE_SUCCESS
}

// FeatureReputation shows the many (features) to one (node) ratio scores
type FeatureReputation struct {
	MeanReputation       float32  `protobuf:"fixed32,1,opt,name=mean_reputation,json=meanReputation" json:"mean_reputation,omitempty"`
	CurrentReputation    float32  `protobuf:"fixed32,2,opt,name=current_reputation,json=currentReputation" json:"current_reputation,omitempty"`
	Feature              Feature  `protobuf:"varint,3,opt,name=feature,enum=nodereputation.Feature" json:"feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureReputation) Reset()         { *m = FeatureReputation{} }
func (m *FeatureReputation) String() string { return proto.CompactTextString(m) }
func (*FeatureReputation) ProtoMessage()    {}
func (*FeatureReputation) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{9}
}
func (m *FeatureReputation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureReputation.Unmarshal(m, b)
}
func (m *FeatureReputation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureReputation.Marshal(b, m, deterministic)
}
func (dst *FeatureReputation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureReputation.Merge(dst, src)
}
func (m *FeatureReputation) XXX_Size() int {
	return xxx_messageInfo_FeatureReputation.Size(m)
}
func (m *FeatureReputation) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureReputation.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureReputation proto.InternalMessageInfo

func (m *FeatureReputation) GetMeanReputation() float32 {
	if m != nil {
		return m.MeanReputation
	}
	return 0
}

func (m *FeatureReputation) GetCurrentReputation() float32 {
	if m != nil {
		return m.CurrentReputation
	}
	return 0
}

func (m *FeatureReputation) GetFeature() Feature {
	if m != nil {
		return m.Feature
	}
	return Feature_UPTIME
}

type FeatureState struct {
	Feature              string   `protobuf:"bytes,1,opt,name=feature" json:"feature,omitempty"`
	MeanReputation       float32  `protobuf:"fixed32,2,opt,name=mean_reputation,json=meanReputation" json:"mean_reputation,omitempty"`
	CurrentReputation    float32  `protobuf:"fixed32,3,opt,name=current_reputation,json=currentReputation" json:"current_reputation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureState) Reset()         { *m = FeatureState{} }
func (m *FeatureState) String() string { return proto.CompactTextString(m) }
func (*FeatureState) ProtoMessage()    {}
func (*FeatureState) Descriptor() ([]byte, []int) {
	return fileDescriptor_nodereputation_f28b060d4bc86ba6, []int{10}
}
func (m *FeatureState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureState.Unmarshal(m, b)
}
func (m *FeatureState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureState.Marshal(b, m, deterministic)
}
func (dst *FeatureState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureState.Merge(dst, src)
}
func (m *FeatureState) XXX_Size() int {
	return xxx_messageInfo_FeatureState.Size(m)
}
func (m *FeatureState) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureState.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureState proto.InternalMessageInfo

func (m *FeatureState) GetFeature() string {
	if m != nil {
		return m.Feature
	}
	return ""
}

func (m *FeatureState) GetMeanReputation() float32 {
	if m != nil {
		return m.MeanReputation
	}
	return 0
}

func (m *FeatureState) GetCurrentReputation() float32 {
	if m != nil {
		return m.CurrentReputation
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "nodereputation.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "nodereputation.GetResponse")
	proto.RegisterType((*MatchRequest)(nil), "nodereputation.MatchRequest")
	proto.RegisterType((*MatchResponse)(nil), "nodereputation.MatchResponse")
	proto.RegisterType((*UpdateRequest)(nil), "nodereputation.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "nodereputation.UpdateResponse")
	proto.RegisterType((*NodeReputationQueryStatus)(nil), "nodereputation.NodeReputationQueryStatus")
	proto.RegisterType((*NodeReputationUpdate)(nil), "nodereputation.NodeReputationUpdate")
	proto.RegisterType((*NodeReputationUpdateStatus)(nil), "nodereputation.NodeReputationUpdateStatus")
	proto.RegisterType((*FeatureReputation)(nil), "nodereputation.FeatureReputation")
	proto.RegisterType((*FeatureState)(nil), "nodereputation.FeatureState")
	proto.RegisterEnum("nodereputation.QueryStatus", QueryStatus_name, QueryStatus_value)
	proto.RegisterEnum("nodereputation.ConstraintStatus", ConstraintStatus_name, ConstraintStatus_value)
	proto.RegisterEnum("nodereputation.UpdateStatus", UpdateStatus_name, UpdateStatus_value)
	proto.RegisterEnum("nodereputation.Feature", Feature_name, Feature_value)
	proto.RegisterEnum("nodereputation.UpdateRepValue", UpdateRepValue_name, UpdateRepValue_value)
	proto.RegisterEnum("nodereputation.Parameter", Parameter_name, Parameter_value)
	proto.RegisterEnum("nodereputation.BetaStateCols", BetaStateCols_name, BetaStateCols_value)
	proto.RegisterEnum("nodereputation.Operand", Operand_name, Operand_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeReputationClient is the client API for NodeReputation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeReputationClient interface {
	// Get the Reputation score for a given node id(s)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Match nodes to the given constraints
	Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error)
	// Update the given node(s) with the provied values
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type nodeReputationClient struct {
	cc *grpc.ClientConn
}

func NewNodeReputationClient(cc *grpc.ClientConn) NodeReputationClient {
	return &nodeReputationClient{cc}
}

func (c *nodeReputationClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/nodereputation.NodeReputation/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeReputationClient) Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, "/nodereputation.NodeReputation/Match", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeReputationClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/nodereputation.NodeReputation/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NodeReputation service

type NodeReputationServer interface {
	// Get the Reputation score for a given node id(s)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Match nodes to the given constraints
	Match(context.Context, *MatchRequest) (*MatchResponse, error)
	// Update the given node(s) with the provied values
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

func RegisterNodeReputationServer(s *grpc.Server, srv NodeReputationServer) {
	s.RegisterService(&_NodeReputation_serviceDesc, srv)
}

func _NodeReputation_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeReputationServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodereputation.NodeReputation/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeReputationServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeReputation_Match_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeReputationServer).Match(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodereputation.NodeReputation/Match",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeReputationServer).Match(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeReputation_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeReputationServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodereputation.NodeReputation/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeReputationServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeReputation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nodereputation.NodeReputation",
	HandlerType: (*NodeReputationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _NodeReputation_Get_Handler,
		},
		{
			MethodName: "Match",
			Handler:    _NodeReputation_Match_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _NodeReputation_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodereputation.proto",
}

func init() {
	proto.RegisterFile("nodereputation.proto", fileDescriptor_nodereputation_f28b060d4bc86ba6)
}

var fileDescriptor_nodereputation_f28b060d4bc86ba6 = []byte{
	// 965 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0x8d, 0xed, 0x26, 0xd9, 0xdc, 0xb4, 0xa9, 0x3b, 0xdb, 0xd2, 0x8f, 0xdd, 0xae, 0x4a, 0x84,
	0x44, 0x89, 0xc4, 0x4a, 0xdb, 0x05, 0x04, 0x12, 0x42, 0x9a, 0xda, 0x93, 0xd4, 0x92, 0x3f, 0xba,
	0xe3, 0x71, 0x57, 0x0b, 0x0f, 0x23, 0xd3, 0x0c, 0x10, 0xa9, 0x8d, 0x83, 0xed, 0x20, 0x78, 0x40,
	0xe2, 0x85, 0x9f, 0x80, 0xc4, 0x13, 0x4f, 0xfc, 0x2f, 0xfe, 0x0a, 0x1a, 0x7b, 0x92, 0xb8, 0x6e,
	0x83, 0x16, 0x69, 0x1f, 0xef, 0x9d, 0x73, 0xee, 0x3d, 0xf7, 0xcc, 0xe4, 0x3a, 0xb0, 0x3b, 0x4d,
	0xc6, 0x22, 0x15, 0xb3, 0x79, 0x1e, 0xe7, 0x93, 0x64, 0xfa, 0x7c, 0x96, 0x26, 0x79, 0x82, 0x7a,
	0x77, 0xb3, 0xfd, 0x3e, 0xc0, 0x48, 0xe4, 0x54, 0xfc, 0x38, 0x17, 0x59, 0x8e, 0x76, 0xa1, 0x29,
	0xcf, 0xb3, 0x03, 0xed, 0xc4, 0x38, 0xed, 0xd0, 0x32, 0xe8, 0x53, 0xe8, 0x16, 0x98, 0x6c, 0x96,
	0x4c, 0x33, 0x81, 0x2c, 0x68, 0xa7, 0xe2, 0x3a, 0x49, 0xc7, 0x25, 0xac, 0x7b, 0xf6, 0xd1, 0xf3,
	0x5a, 0x2b, 0x3f, 0x19, 0x0b, 0xba, 0x0c, 0x5f, 0xcd, 0x45, 0xfa, 0x4b, 0x98, 0xc7, 0xf9, 0x3c,
	0xa3, 0x0b, 0x66, 0xff, 0x77, 0x0d, 0x36, 0xbd, 0x38, 0xbf, 0xfe, 0xa1, 0xd2, 0xfa, 0x66, 0x72,
	0x3b, 0xc9, 0x0f, 0xb4, 0x13, 0xed, 0xd4, 0xa0, 0x65, 0x80, 0x30, 0x6c, 0x7f, 0x27, 0xe2, 0x7c,
	0x9e, 0x8a, 0x20, 0x1d, 0x8b, 0x74, 0x32, 0xfd, 0xfe, 0x40, 0x3f, 0x31, 0x4e, 0x7b, 0x67, 0xfb,
	0xf5, 0x9e, 0xc3, 0x12, 0x46, 0xeb, 0x78, 0xf4, 0x14, 0x3a, 0xe2, 0xe7, 0xeb, 0x9b, 0xf9, 0x58,
	0x92, 0x8d, 0x62, 0xae, 0x55, 0xa2, 0xcf, 0x61, 0x4b, 0xc9, 0x50, 0xd3, 0x7d, 0x0e, 0xad, 0xac,
	0xd0, 0x5a, 0x08, 0xe9, 0x9d, 0x9d, 0xd4, 0x1b, 0x59, 0xc9, 0x34, 0xcb, 0xd3, 0x78, 0x32, 0xcd,
	0xd5, 0x4c, 0x0a, 0xbf, 0x32, 0x4f, 0xaf, 0x9a, 0xe7, 0xc1, 0x56, 0x34, 0x1b, 0xc7, 0xb9, 0x58,
	0x0c, 0xfa, 0x25, 0xb4, 0xe6, 0x45, 0x42, 0xb9, 0xf7, 0xc1, 0x7f, 0xbb, 0xa7, 0xc8, 0x8a, 0xd3,
	0x67, 0xd0, 0x5b, 0x94, 0x53, 0x82, 0xcf, 0x6b, 0xf5, 0x06, 0x6f, 0x53, 0x6f, 0x21, 0x5d, 0x55,
	0xfd, 0x5b, 0x83, 0xc3, 0xb5, 0x97, 0x86, 0xf6, 0xa1, 0x2d, 0x4b, 0xf2, 0xc9, 0xb8, 0xf0, 0xa4,
	0x43, 0x5b, 0x32, 0x74, 0xc6, 0xe8, 0xe5, 0xd2, 0x2b, 0xbd, 0xf0, 0xea, 0x49, 0xbd, 0x75, 0xf5,
	0xea, 0x17, 0x36, 0x7d, 0x01, 0xad, 0xec, 0x3a, 0x49, 0x45, 0x56, 0x5c, 0x46, 0xf7, 0xec, 0xfd,
	0x75, 0x37, 0xb9, 0xcc, 0x50, 0x45, 0xe8, 0xff, 0xa9, 0xc1, 0xee, 0x43, 0xd3, 0xac, 0x57, 0xf8,
	0x02, 0xda, 0xea, 0x3d, 0x28, 0x89, 0x6b, 0xdf, 0xcd, 0x02, 0x87, 0x3e, 0x81, 0xe6, 0x4f, 0xf1,
	0xcd, 0x5c, 0x1c, 0x18, 0x05, 0xe1, 0x59, 0x9d, 0xb0, 0xb0, 0x7f, 0x76, 0x25, 0x51, 0xb4, 0x04,
	0xf7, 0xff, 0xd2, 0xe0, 0x68, 0xbd, 0xd1, 0xef, 0x58, 0xe0, 0xc2, 0xf5, 0x52, 0xe1, 0xd3, 0x87,
	0x15, 0xde, 0xb5, 0x5d, 0x0a, 0xdc, 0xb9, 0xe7, 0x2c, 0xfa, 0x10, 0xb6, 0x6f, 0x45, 0x3c, 0xe5,
	0x2b, 0x76, 0xa1, 0x4f, 0xa7, 0x3d, 0x99, 0xae, 0x00, 0x3f, 0x06, 0x74, 0x3d, 0x4f, 0x53, 0x31,
	0xcd, 0xab, 0x58, 0xbd, 0xc0, 0xee, 0xa8, 0x93, 0x0a, 0xbc, 0x32, 0x96, 0xf1, 0x76, 0x63, 0xf5,
	0x7f, 0xd3, 0x60, 0x53, 0x25, 0xa5, 0x74, 0x81, 0x0e, 0x56, 0x35, 0x4a, 0xcf, 0x96, 0x0e, 0x3c,
	0xa0, 0x5a, 0xff, 0x1f, 0xaa, 0x8d, 0x35, 0xaa, 0x07, 0x2f, 0xa0, 0x5b, 0x7d, 0xf7, 0x3d, 0x00,
	0x3f, 0xb0, 0x09, 0x1f, 0x06, 0x91, 0x6f, 0x9b, 0x0d, 0x84, 0xa0, 0x57, 0xc4, 0x7e, 0xc0, 0x54,
	0x4e, 0x1b, 0x7c, 0x06, 0x66, 0x7d, 0x21, 0x48, 0x9e, 0xeb, 0x78, 0x0e, 0xe3, 0x1e, 0x21, 0xac,
	0xe4, 0x95, 0xb1, 0x24, 0x16, 0x39, 0x6d, 0xf0, 0x29, 0x6c, 0xde, 0x79, 0x20, 0x08, 0x7a, 0xd1,
	0xa5, 0x8d, 0x19, 0xe1, 0x61, 0x64, 0x59, 0x24, 0x0c, 0xcd, 0x06, 0xda, 0x81, 0x2d, 0x95, 0x1b,
	0x62, 0xc7, 0x25, 0xb2, 0x5d, 0x02, 0x6d, 0xe5, 0x11, 0x02, 0x68, 0x45, 0x97, 0xcc, 0xf1, 0x88,
	0xd9, 0x40, 0x1d, 0x68, 0xe2, 0xc8, 0x76, 0x98, 0xa9, 0xa1, 0x2e, 0xb4, 0x5d, 0xcc, 0x88, 0x6f,
	0xbd, 0x31, 0x75, 0x74, 0x08, 0x7b, 0xd8, 0x0b, 0x22, 0x9f, 0xf1, 0x60, 0xc8, 0x6d, 0xcc, 0x30,
	0x0f, 0x59, 0x40, 0x89, 0x6d, 0x1a, 0xc8, 0x84, 0xcd, 0x21, 0x76, 0x43, 0xc2, 0x2d, 0x17, 0x3b,
	0x5e, 0x68, 0x6e, 0xa0, 0xc7, 0xb0, 0x1d, 0x5e, 0x60, 0x6a, 0x87, 0xdc, 0x0b, 0x6c, 0x67, 0xe8,
	0x10, 0xdb, 0x6c, 0x0e, 0xfe, 0xd0, 0x56, 0x0b, 0xa7, 0x7c, 0xf1, 0x92, 0xe9, 0x93, 0x11, 0x66,
	0xce, 0x15, 0xe1, 0x81, 0x2f, 0xdb, 0xef, 0xc3, 0xe3, 0x65, 0xe6, 0x32, 0x70, 0x7c, 0xc6, 0x87,
	0xce, 0x15, 0x31, 0x35, 0xf4, 0x0c, 0x8e, 0x6a, 0x07, 0xec, 0x35, 0xf1, 0xd9, 0x9b, 0xf2, 0x5c,
	0x47, 0x8f, 0x60, 0xe3, 0x6b, 0x42, 0x03, 0xd3, 0x40, 0x7b, 0xb0, 0x73, 0x1f, 0xb0, 0x21, 0xad,
	0xac, 0x14, 0x6c, 0xa2, 0x36, 0x18, 0xb2, 0x65, 0x6b, 0x60, 0x43, 0xe7, 0x32, 0x4e, 0xe3, 0x5b,
	0x91, 0x8b, 0x14, 0x6d, 0x43, 0x77, 0x14, 0x04, 0x36, 0xa7, 0xc4, 0xc2, 0xae, 0x6b, 0x36, 0x24,
	0xed, 0x1c, 0x2f, 0x63, 0x0d, 0xbd, 0x07, 0xe8, 0x35, 0x71, 0x46, 0x17, 0x8c, 0xdb, 0xc4, 0x0f,
	0x3c, 0xc7, 0xc7, 0x2c, 0xa0, 0xa6, 0x3e, 0xf8, 0x06, 0xb6, 0xce, 0x45, 0x1e, 0x17, 0xef, 0xcd,
	0x4a, 0x6e, 0x32, 0xe9, 0xc1, 0x90, 0x60, 0x16, 0x51, 0xc2, 0x2d, 0xe9, 0x1b, 0xa1, 0x66, 0x03,
	0x1d, 0xc3, 0xa1, 0x15, 0x79, 0x91, 0x5b, 0xce, 0x11, 0x46, 0x1e, 0xa7, 0xe4, 0x32, 0x62, 0x98,
	0x39, 0x81, 0x5f, 0x16, 0xb7, 0x22, 0x4a, 0x89, 0xcf, 0xaa, 0x79, 0x7d, 0xf0, 0x2b, 0xb4, 0x83,
	0x99, 0x48, 0xe3, 0xe9, 0x18, 0x6d, 0xc2, 0x23, 0xf2, 0x2a, 0xc2, 0x2e, 0x67, 0x81, 0xd9, 0x90,
	0x06, 0x8e, 0x28, 0xc1, 0x8c, 0x50, 0xce, 0x2e, 0xb0, 0x2c, 0x71, 0x08, 0x7b, 0xd5, 0x0c, 0x5f,
	0x82, 0x75, 0xb4, 0x05, 0x1d, 0x97, 0x84, 0x61, 0x89, 0x34, 0x64, 0xb3, 0x65, 0xb8, 0x82, 0x6d,
	0x14, 0x97, 0x12, 0xb0, 0x55, 0xa6, 0x79, 0xf6, 0x8f, 0x06, 0xbd, 0xbb, 0x1b, 0x09, 0x7d, 0x05,
	0xc6, 0x48, 0xe4, 0xe8, 0xa8, 0xfe, 0x5b, 0x5c, 0xfd, 0x03, 0x38, 0x7a, 0xf2, 0xe0, 0x99, 0xfa,
	0xd4, 0xd8, 0xd0, 0x2c, 0x3e, 0x96, 0xe8, 0xde, 0xca, 0xa9, 0x7e, 0xca, 0x8f, 0x8e, 0xd7, 0x9c,
	0xaa, 0x2a, 0x23, 0x68, 0xa9, 0xb5, 0x7d, 0xbc, 0x6e, 0xb7, 0x96, 0x75, 0xd6, 0xae, 0xde, 0xb2,
	0xd0, 0xb7, 0xad, 0xe2, 0x2f, 0xcd, 0xcb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x51, 0x75, 0x32,
	0x95, 0xea, 0x08, 0x00, 0x00,
}
