#!/bin/sh
set -euo pipefail

SETUP_PARAMS=""

if [[ -n "${API_KEY:-}" ]]; then
	export STORJ_POINTER_DB_AUTH_API_KEY="${API_KEY}"
  export STORJ_AUDIT_API_KEY="${API_KEY}"
  export STORJ_POINTER_DB_AUTH_API_KEY="${API_KEY}"
  export STORJ_REPAIRER_API_KEY="${API_KEY}"
fi

if [[ -n "${STORJ_DATABASE:-}" ]]; then
  export STORJ_POINTER_DB_DATABASE_URL="${STORJ_DATABASE}"
fi


if [[ -n "${IDENTITY_ADDR:-}" ]]; then
	export STORJ_SERVER_ADDRESS="${IDENTITY_ADDR}"
fi

if [[ ! -f "${CONF_PATH}/config.yaml" ]]; then
	./satellite setup $SETUP_PARAMS
fi

RUN_PARAMS="${RUN_PARAMS:-} --config-dir ${CONF_PATH}"

exec ./satellite run $RUN_PARAMS "$@"
