// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gc.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Filter struct {
	Seed                 uint32   `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	K                    uint32   `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	BitsPerElement       uint32   `protobuf:"varint,3,opt,name=bits_per_element,json=bitsPerElement,proto3" json:"bits_per_element,omitempty"`
	Table                []byte   `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_5502b0b1493f7734, []int{0}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetSeed() uint32 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *Filter) GetK() uint32 {
	if m != nil {
		return m.K
	}
	return 0
}

func (m *Filter) GetBitsPerElement() uint32 {
	if m != nil {
		return m.BitsPerElement
	}
	return 0
}

func (m *Filter) GetTable() []byte {
	if m != nil {
		return m.Table
	}
	return nil
}

type RetainRequest struct {
	CreationDate         *time.Time `protobuf:"bytes,1,opt,name=creation_date,json=creationDate,proto3,stdtime" json:"creation_date,omitempty"`
	Filter               *Filter    `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RetainRequest) Reset()         { *m = RetainRequest{} }
func (m *RetainRequest) String() string { return proto.CompactTextString(m) }
func (*RetainRequest) ProtoMessage()    {}
func (*RetainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5502b0b1493f7734, []int{1}
}
func (m *RetainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetainRequest.Unmarshal(m, b)
}
func (m *RetainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetainRequest.Marshal(b, m, deterministic)
}
func (m *RetainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetainRequest.Merge(m, src)
}
func (m *RetainRequest) XXX_Size() int {
	return xxx_messageInfo_RetainRequest.Size(m)
}
func (m *RetainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetainRequest proto.InternalMessageInfo

func (m *RetainRequest) GetCreationDate() *time.Time {
	if m != nil {
		return m.CreationDate
	}
	return nil
}

func (m *RetainRequest) GetFilter() *Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type RetainResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetainResponse) Reset()         { *m = RetainResponse{} }
func (m *RetainResponse) String() string { return proto.CompactTextString(m) }
func (*RetainResponse) ProtoMessage()    {}
func (*RetainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5502b0b1493f7734, []int{2}
}
func (m *RetainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetainResponse.Unmarshal(m, b)
}
func (m *RetainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetainResponse.Marshal(b, m, deterministic)
}
func (m *RetainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetainResponse.Merge(m, src)
}
func (m *RetainResponse) XXX_Size() int {
	return xxx_messageInfo_RetainResponse.Size(m)
}
func (m *RetainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetainResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Filter)(nil), "gc.Filter")
	proto.RegisterType((*RetainRequest)(nil), "gc.RetainRequest")
	proto.RegisterType((*RetainResponse)(nil), "gc.RetainResponse")
}

func init() { proto.RegisterFile("gc.proto", fileDescriptor_5502b0b1493f7734) }

var fileDescriptor_5502b0b1493f7734 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0x12, 0x22, 0x34, 0xfd, 0x51, 0x6b, 0xb1, 0x88, 0xb2, 0x69, 0x95, 0x55, 0x57,
	0xae, 0x54, 0x6e, 0x50, 0x5a, 0xd8, 0x22, 0x8b, 0x15, 0x9b, 0xca, 0x4e, 0xa7, 0x56, 0xa8, 0x1b,
	0x07, 0x7b, 0xba, 0xe1, 0x14, 0xdc, 0x90, 0xab, 0xa0, 0xda, 0x44, 0x82, 0x9d, 0xdf, 0x9b, 0xf1,
	0x9b, 0xef, 0xc1, 0x9d, 0xa9, 0x45, 0xe7, 0x1d, 0x39, 0x3e, 0x30, 0x75, 0x09, 0xc6, 0x19, 0x97,
	0x74, 0x39, 0x37, 0xce, 0x19, 0x8b, 0xab, 0xa8, 0xf4, 0xe5, 0xb8, 0xa2, 0xe6, 0x8c, 0x81, 0xd4,
	0xb9, 0x4b, 0x0b, 0xd5, 0x3b, 0xe4, 0x4f, 0x8d, 0x25, 0xf4, 0x9c, 0x43, 0x16, 0x10, 0x0f, 0x05,
	0x5b, 0xb0, 0xe5, 0x58, 0xc6, 0x37, 0x1f, 0x01, 0x3b, 0x15, 0x83, 0x68, 0xb0, 0x13, 0x5f, 0xc2,
	0x54, 0x37, 0x14, 0xf6, 0x1d, 0xfa, 0x3d, 0x5a, 0x3c, 0x63, 0x4b, 0xc5, 0x4d, 0x1c, 0x4e, 0xae,
	0xfe, 0x0b, 0xfa, 0x5d, 0x72, 0xf9, 0x3d, 0xdc, 0x92, 0xd2, 0x16, 0x8b, 0x6c, 0xc1, 0x96, 0x23,
	0x99, 0x44, 0xf5, 0x09, 0x63, 0x89, 0xa4, 0x9a, 0x56, 0xe2, 0xc7, 0x05, 0x03, 0xf1, 0x1d, 0x8c,
	0x6b, 0x8f, 0x8a, 0x1a, 0xd7, 0xee, 0x0f, 0x8a, 0x30, 0xde, 0x1e, 0xae, 0x4b, 0x91, 0xa8, 0x45,
	0x4f, 0x2d, 0x5e, 0x7b, 0xea, 0x4d, 0xf6, 0xf5, 0x3d, 0x67, 0x72, 0xd4, 0x7f, 0xdb, 0x2a, 0x42,
	0x5e, 0x41, 0x7e, 0x8c, 0x1d, 0x22, 0xea, 0x70, 0x0d, 0xc2, 0xd4, 0x22, 0xb5, 0x92, 0xbf, 0x93,
	0x6a, 0x0a, 0x93, 0xfe, 0x76, 0xe8, 0x5c, 0x1b, 0x70, 0xbd, 0x85, 0xd9, 0xb3, 0xf2, 0x5a, 0x19,
	0x7c, 0x74, 0xd6, 0x62, 0x7d, 0x8d, 0xe3, 0x2b, 0xc8, 0xd3, 0x1a, 0x9f, 0x5d, 0x43, 0xfe, 0xe1,
	0x96, 0xfc, 0xaf, 0x95, 0x52, 0x36, 0xd9, 0xdb, 0xa0, 0xd3, 0x3a, 0x8f, 0xa4, 0x0f, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x7f, 0x03, 0xfa, 0x01, 0x89, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GarbageCollectionClient is the client API for GarbageCollection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GarbageCollectionClient interface {
	Retain(ctx context.Context, in *RetainRequest, opts ...grpc.CallOption) (*RetainResponse, error)
}

type garbageCollectionClient struct {
	cc *grpc.ClientConn
}

func NewGarbageCollectionClient(cc *grpc.ClientConn) GarbageCollectionClient {
	return &garbageCollectionClient{cc}
}

func (c *garbageCollectionClient) Retain(ctx context.Context, in *RetainRequest, opts ...grpc.CallOption) (*RetainResponse, error) {
	out := new(RetainResponse)
	err := c.cc.Invoke(ctx, "/gc.GarbageCollection/Retain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GarbageCollectionServer is the server API for GarbageCollection service.
type GarbageCollectionServer interface {
	Retain(context.Context, *RetainRequest) (*RetainResponse, error)
}

func RegisterGarbageCollectionServer(s *grpc.Server, srv GarbageCollectionServer) {
	s.RegisterService(&_GarbageCollection_serviceDesc, srv)
}

func _GarbageCollection_Retain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GarbageCollectionServer).Retain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gc.GarbageCollection/Retain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GarbageCollectionServer).Retain(ctx, req.(*RetainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GarbageCollection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gc.GarbageCollection",
	HandlerType: (*GarbageCollectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Retain",
			Handler:    _GarbageCollection_Retain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gc.proto",
}
