// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MetaStreamInfo struct {
	NumberOfSegments     int64    `protobuf:"varint,1,opt,name=number_of_segments,json=numberOfSegments,proto3" json:"number_of_segments,omitempty"`
	SegmentsSize         int64    `protobuf:"varint,2,opt,name=segments_size,json=segmentsSize,proto3" json:"segments_size,omitempty"`
	LastSegmentSize      int64    `protobuf:"varint,3,opt,name=last_segment_size,json=lastSegmentSize,proto3" json:"last_segment_size,omitempty"`
	Metadata             []byte   `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	EncryptionType       int32    `protobuf:"varint,5,opt,name=encryption_type,json=encryptionType,proto3" json:"encryption_type,omitempty"`
	StartingNonce        []byte   `protobuf:"bytes,6,opt,name=starting_nonce,json=startingNonce,proto3" json:"starting_nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaStreamInfo) Reset()         { *m = MetaStreamInfo{} }
func (m *MetaStreamInfo) String() string { return proto.CompactTextString(m) }
func (*MetaStreamInfo) ProtoMessage()    {}
func (*MetaStreamInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_a3eb9d8122c3d860, []int{0}
}
func (m *MetaStreamInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaStreamInfo.Unmarshal(m, b)
}
func (m *MetaStreamInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaStreamInfo.Marshal(b, m, deterministic)
}
func (dst *MetaStreamInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaStreamInfo.Merge(dst, src)
}
func (m *MetaStreamInfo) XXX_Size() int {
	return xxx_messageInfo_MetaStreamInfo.Size(m)
}
func (m *MetaStreamInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaStreamInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MetaStreamInfo proto.InternalMessageInfo

func (m *MetaStreamInfo) GetNumberOfSegments() int64 {
	if m != nil {
		return m.NumberOfSegments
	}
	return 0
}

func (m *MetaStreamInfo) GetSegmentsSize() int64 {
	if m != nil {
		return m.SegmentsSize
	}
	return 0
}

func (m *MetaStreamInfo) GetLastSegmentSize() int64 {
	if m != nil {
		return m.LastSegmentSize
	}
	return 0
}

func (m *MetaStreamInfo) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *MetaStreamInfo) GetEncryptionType() int32 {
	if m != nil {
		return m.EncryptionType
	}
	return 0
}

func (m *MetaStreamInfo) GetStartingNonce() []byte {
	if m != nil {
		return m.StartingNonce
	}
	return nil
}

func init() {
	proto.RegisterType((*MetaStreamInfo)(nil), "pb.MetaStreamInfo")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_meta_a3eb9d8122c3d860) }

var fileDescriptor_meta_a3eb9d8122c3d860 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x46, 0x49, 0x6b, 0x8b, 0x0c, 0xed, 0x56, 0x73, 0x0a, 0x9e, 0x16, 0x45, 0x5c, 0x44, 0xbc,
	0xf8, 0x2b, 0x3c, 0xa8, 0xb0, 0xeb, 0x3d, 0x64, 0xeb, 0x6c, 0x09, 0x98, 0x49, 0x48, 0xc6, 0xc3,
	0xf6, 0xaf, 0x7b, 0x91, 0x4d, 0x37, 0xf6, 0x98, 0xf7, 0x3d, 0x1e, 0x61, 0x00, 0x1c, 0xb2, 0x79,
	0x0e, 0xd1, 0xb3, 0x97, 0x8b, 0xd0, 0xdf, 0xfe, 0x0a, 0xa8, 0xde, 0x90, 0x4d, 0xc7, 0x11, 0x8d,
	0x7b, 0xa5, 0xc1, 0xcb, 0x27, 0x90, 0xf4, 0xe3, 0x7a, 0x8c, 0xda, 0x0f, 0x3a, 0xe1, 0xc1, 0x21,
	0x71, 0x52, 0xa2, 0x16, 0xcd, 0xb2, 0xbd, 0x3a, 0x2d, 0x1f, 0x43, 0x37, 0x73, 0x79, 0x07, 0xdb,
	0xe2, 0xe8, 0x64, 0x8f, 0xa8, 0x16, 0x59, 0xdc, 0x14, 0xd8, 0xd9, 0x23, 0xca, 0x47, 0xb8, 0xfe,
	0x36, 0x89, 0x4b, 0xed, 0x24, 0x2e, 0xb3, 0xb8, 0x9b, 0x86, 0xb9, 0x96, 0xdd, 0x1b, 0xb8, 0x9c,
	0xfe, 0xf8, 0x65, 0xd8, 0xa8, 0x8b, 0x5a, 0x34, 0x9b, 0xf6, 0xff, 0x2d, 0x1f, 0x60, 0x87, 0xb4,
	0x8f, 0x63, 0x60, 0xeb, 0x49, 0xf3, 0x18, 0x50, 0xad, 0x6a, 0xd1, 0xac, 0xda, 0xea, 0x8c, 0x3f,
	0xc7, 0x80, 0xf2, 0x1e, 0xaa, 0xc4, 0x26, 0xb2, 0xa5, 0x83, 0x26, 0x4f, 0x7b, 0x54, 0xeb, 0x9c,
	0xda, 0x16, 0xfa, 0x3e, 0xc1, 0x7e, 0x9d, 0x0f, 0xf1, 0xf2, 0x17, 0x00, 0x00, 0xff, 0xff, 0x6e,
	0xd1, 0xb8, 0xc7, 0x16, 0x01, 0x00, 0x00,
}
