// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metainfo.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Action is an enumeration of all possible executed action on storage node
type Action int32

const (
	Action_INVALID    Action = 0
	Action_PUT        Action = 1
	Action_GET        Action = 2
	Action_GET_AUDIT  Action = 3
	Action_GET_REPAIR Action = 4
	Action_PUT_REPAIR Action = 5
	Action_DELETE     Action = 6
)

var Action_name = map[int32]string{
	0: "INVALID",
	1: "PUT",
	2: "GET",
	3: "GET_AUDIT",
	4: "GET_REPAIR",
	5: "PUT_REPAIR",
	6: "DELETE",
}
var Action_value = map[string]int32{
	"INVALID":    0,
	"PUT":        1,
	"GET":        2,
	"GET_AUDIT":  3,
	"GET_REPAIR": 4,
	"PUT_REPAIR": 5,
	"DELETE":     6,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}
func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{0}
}

// OrderLimit2 is provided by satellite to execute specific action on storage node within some limits
type OrderLimit2 struct {
	// unique serial to avoid replay attacks
	SerialNumber []byte `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	// satellite who issued this order limit allowing orderer to do the specified action
	SatelliteId NodeID `protobuf:"bytes,2,opt,name=satellite_id,json=satelliteId,proto3,customtype=NodeID" json:"satellite_id"`
	// uplink who requested or whom behalf the order limit to do an action
	UplinkId NodeID `protobuf:"bytes,3,opt,name=uplink_id,json=uplinkId,proto3,customtype=NodeID" json:"uplink_id"`
	// storage node who can reclaim the order limit specified by serial
	StorageNodeId NodeID `protobuf:"bytes,4,opt,name=storage_node_id,json=storageNodeId,proto3,customtype=NodeID" json:"storage_node_id"`
	// piece which is allowed to be touched
	PieceId PieceID `protobuf:"bytes,5,opt,name=piece_id,json=pieceId,proto3,customtype=PieceID" json:"piece_id"`
	// limit in bytes how much can be changed
	Limit                int64                `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Action               Action               `protobuf:"varint,7,opt,name=action,proto3,enum=metainfo.Action" json:"action,omitempty"`
	PieceExpiration      *timestamp.Timestamp `protobuf:"bytes,8,opt,name=piece_expiration,json=pieceExpiration,proto3" json:"piece_expiration,omitempty"`
	OrderExpiration      *timestamp.Timestamp `protobuf:"bytes,9,opt,name=order_expiration,json=orderExpiration,proto3" json:"order_expiration,omitempty"`
	SatelliteSignature   []byte               `protobuf:"bytes,10,opt,name=satellite_signature,json=satelliteSignature,proto3" json:"satellite_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderLimit2) Reset()         { *m = OrderLimit2{} }
func (m *OrderLimit2) String() string { return proto.CompactTextString(m) }
func (*OrderLimit2) ProtoMessage()    {}
func (*OrderLimit2) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{0}
}
func (m *OrderLimit2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderLimit2.Unmarshal(m, b)
}
func (m *OrderLimit2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderLimit2.Marshal(b, m, deterministic)
}
func (dst *OrderLimit2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderLimit2.Merge(dst, src)
}
func (m *OrderLimit2) XXX_Size() int {
	return xxx_messageInfo_OrderLimit2.Size(m)
}
func (m *OrderLimit2) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderLimit2.DiscardUnknown(m)
}

var xxx_messageInfo_OrderLimit2 proto.InternalMessageInfo

func (m *OrderLimit2) GetSerialNumber() []byte {
	if m != nil {
		return m.SerialNumber
	}
	return nil
}

func (m *OrderLimit2) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *OrderLimit2) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_INVALID
}

func (m *OrderLimit2) GetPieceExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.PieceExpiration
	}
	return nil
}

func (m *OrderLimit2) GetOrderExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.OrderExpiration
	}
	return nil
}

func (m *OrderLimit2) GetSatelliteSignature() []byte {
	if m != nil {
		return m.SatelliteSignature
	}
	return nil
}

type AddressedOrderLimit struct {
	Limit                *OrderLimit2 `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	StorageNodeAddress   *NodeAddress `protobuf:"bytes,2,opt,name=storage_node_address,json=storageNodeAddress,proto3" json:"storage_node_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddressedOrderLimit) Reset()         { *m = AddressedOrderLimit{} }
func (m *AddressedOrderLimit) String() string { return proto.CompactTextString(m) }
func (*AddressedOrderLimit) ProtoMessage()    {}
func (*AddressedOrderLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{1}
}
func (m *AddressedOrderLimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressedOrderLimit.Unmarshal(m, b)
}
func (m *AddressedOrderLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressedOrderLimit.Marshal(b, m, deterministic)
}
func (dst *AddressedOrderLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressedOrderLimit.Merge(dst, src)
}
func (m *AddressedOrderLimit) XXX_Size() int {
	return xxx_messageInfo_AddressedOrderLimit.Size(m)
}
func (m *AddressedOrderLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressedOrderLimit.DiscardUnknown(m)
}

var xxx_messageInfo_AddressedOrderLimit proto.InternalMessageInfo

func (m *AddressedOrderLimit) GetLimit() *OrderLimit2 {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *AddressedOrderLimit) GetStorageNodeAddress() *NodeAddress {
	if m != nil {
		return m.StorageNodeAddress
	}
	return nil
}

// Order2 is a one step of fullfilling Amount number of bytes from an OrderLimit2 with SerialNumber
type Order2 struct {
	// serial of the order limit that was signed
	SerialNumber []byte `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	// amount to be signed for
	Amount int64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// signature
	UplinkSignature      []byte   `protobuf:"bytes,3,opt,name=uplink_signature,json=uplinkSignature,proto3" json:"uplink_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order2) Reset()         { *m = Order2{} }
func (m *Order2) String() string { return proto.CompactTextString(m) }
func (*Order2) ProtoMessage()    {}
func (*Order2) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{2}
}
func (m *Order2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order2.Unmarshal(m, b)
}
func (m *Order2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order2.Marshal(b, m, deterministic)
}
func (dst *Order2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order2.Merge(dst, src)
}
func (m *Order2) XXX_Size() int {
	return xxx_messageInfo_Order2.Size(m)
}
func (m *Order2) XXX_DiscardUnknown() {
	xxx_messageInfo_Order2.DiscardUnknown(m)
}

var xxx_messageInfo_Order2 proto.InternalMessageInfo

func (m *Order2) GetSerialNumber() []byte {
	if m != nil {
		return m.SerialNumber
	}
	return nil
}

func (m *Order2) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Order2) GetUplinkSignature() []byte {
	if m != nil {
		return m.UplinkSignature
	}
	return nil
}

type PieceHash struct {
	// piece id
	PieceId []byte `protobuf:"bytes,1,opt,name=piece_id,json=pieceId,proto3" json:"piece_id,omitempty"`
	// hash of the piece that was/is uploaded
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// signature either satellite or storage node
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieceHash) Reset()         { *m = PieceHash{} }
func (m *PieceHash) String() string { return proto.CompactTextString(m) }
func (*PieceHash) ProtoMessage()    {}
func (*PieceHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{3}
}
func (m *PieceHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieceHash.Unmarshal(m, b)
}
func (m *PieceHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieceHash.Marshal(b, m, deterministic)
}
func (dst *PieceHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieceHash.Merge(dst, src)
}
func (m *PieceHash) XXX_Size() int {
	return xxx_messageInfo_PieceHash.Size(m)
}
func (m *PieceHash) XXX_DiscardUnknown() {
	xxx_messageInfo_PieceHash.DiscardUnknown(m)
}

var xxx_messageInfo_PieceHash proto.InternalMessageInfo

func (m *PieceHash) GetPieceId() []byte {
	if m != nil {
		return m.PieceId
	}
	return nil
}

func (m *PieceHash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *PieceHash) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type SegmentWriteRequest struct {
	Bucket               []byte   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path                 []byte   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	TotalNodes           int32    `protobuf:"varint,3,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	MaxSegmentSize       int64    `protobuf:"varint,4,opt,name=max_segment_size,json=maxSegmentSize,proto3" json:"max_segment_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentWriteRequest) Reset()         { *m = SegmentWriteRequest{} }
func (m *SegmentWriteRequest) String() string { return proto.CompactTextString(m) }
func (*SegmentWriteRequest) ProtoMessage()    {}
func (*SegmentWriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{4}
}
func (m *SegmentWriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentWriteRequest.Unmarshal(m, b)
}
func (m *SegmentWriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentWriteRequest.Marshal(b, m, deterministic)
}
func (dst *SegmentWriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentWriteRequest.Merge(dst, src)
}
func (m *SegmentWriteRequest) XXX_Size() int {
	return xxx_messageInfo_SegmentWriteRequest.Size(m)
}
func (m *SegmentWriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentWriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentWriteRequest proto.InternalMessageInfo

func (m *SegmentWriteRequest) GetBucket() []byte {
	if m != nil {
		return m.Bucket
	}
	return nil
}

func (m *SegmentWriteRequest) GetPath() []byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *SegmentWriteRequest) GetTotalNodes() int32 {
	if m != nil {
		return m.TotalNodes
	}
	return 0
}

func (m *SegmentWriteRequest) GetMaxSegmentSize() int64 {
	if m != nil {
		return m.MaxSegmentSize
	}
	return 0
}

type SegmentCommitRequest struct {
	Bucket                 []byte       `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path                   []byte       `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Segment                int64        `protobuf:"varint,3,opt,name=segment,proto3" json:"segment,omitempty"`
	StorageNodePiecehashes []*PieceHash `protobuf:"bytes,4,rep,name=storage_node_piecehashes,json=storageNodePiecehashes,proto3" json:"storage_node_piecehashes,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}     `json:"-"`
	XXX_unrecognized       []byte       `json:"-"`
	XXX_sizecache          int32        `json:"-"`
}

func (m *SegmentCommitRequest) Reset()         { *m = SegmentCommitRequest{} }
func (m *SegmentCommitRequest) String() string { return proto.CompactTextString(m) }
func (*SegmentCommitRequest) ProtoMessage()    {}
func (*SegmentCommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{5}
}
func (m *SegmentCommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentCommitRequest.Unmarshal(m, b)
}
func (m *SegmentCommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentCommitRequest.Marshal(b, m, deterministic)
}
func (dst *SegmentCommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentCommitRequest.Merge(dst, src)
}
func (m *SegmentCommitRequest) XXX_Size() int {
	return xxx_messageInfo_SegmentCommitRequest.Size(m)
}
func (m *SegmentCommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentCommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentCommitRequest proto.InternalMessageInfo

func (m *SegmentCommitRequest) GetBucket() []byte {
	if m != nil {
		return m.Bucket
	}
	return nil
}

func (m *SegmentCommitRequest) GetPath() []byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *SegmentCommitRequest) GetSegment() int64 {
	if m != nil {
		return m.Segment
	}
	return 0
}

func (m *SegmentCommitRequest) GetStorageNodePiecehashes() []*PieceHash {
	if m != nil {
		return m.StorageNodePiecehashes
	}
	return nil
}

type SegmentCommitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentCommitResponse) Reset()         { *m = SegmentCommitResponse{} }
func (m *SegmentCommitResponse) String() string { return proto.CompactTextString(m) }
func (*SegmentCommitResponse) ProtoMessage()    {}
func (*SegmentCommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{6}
}
func (m *SegmentCommitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentCommitResponse.Unmarshal(m, b)
}
func (m *SegmentCommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentCommitResponse.Marshal(b, m, deterministic)
}
func (dst *SegmentCommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentCommitResponse.Merge(dst, src)
}
func (m *SegmentCommitResponse) XXX_Size() int {
	return xxx_messageInfo_SegmentCommitResponse.Size(m)
}
func (m *SegmentCommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentCommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentCommitResponse proto.InternalMessageInfo

type SegementDownloadRequest struct {
	Bucket               []byte   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path                 []byte   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Segment              int64    `protobuf:"varint,3,opt,name=segment,proto3" json:"segment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegementDownloadRequest) Reset()         { *m = SegementDownloadRequest{} }
func (m *SegementDownloadRequest) String() string { return proto.CompactTextString(m) }
func (*SegementDownloadRequest) ProtoMessage()    {}
func (*SegementDownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{7}
}
func (m *SegementDownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegementDownloadRequest.Unmarshal(m, b)
}
func (m *SegementDownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegementDownloadRequest.Marshal(b, m, deterministic)
}
func (dst *SegementDownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegementDownloadRequest.Merge(dst, src)
}
func (m *SegementDownloadRequest) XXX_Size() int {
	return xxx_messageInfo_SegementDownloadRequest.Size(m)
}
func (m *SegementDownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SegementDownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SegementDownloadRequest proto.InternalMessageInfo

func (m *SegementDownloadRequest) GetBucket() []byte {
	if m != nil {
		return m.Bucket
	}
	return nil
}

func (m *SegementDownloadRequest) GetPath() []byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *SegementDownloadRequest) GetSegment() int64 {
	if m != nil {
		return m.Segment
	}
	return 0
}

type SegementDownloadResponse struct {
	AddressedLimits      []*AddressedOrderLimit `protobuf:"bytes,1,rep,name=addressed_limits,json=addressedLimits,proto3" json:"addressed_limits,omitempty"`
	Pointer              *Pointer               `protobuf:"bytes,2,opt,name=pointer,proto3" json:"pointer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SegementDownloadResponse) Reset()         { *m = SegementDownloadResponse{} }
func (m *SegementDownloadResponse) String() string { return proto.CompactTextString(m) }
func (*SegementDownloadResponse) ProtoMessage()    {}
func (*SegementDownloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{8}
}
func (m *SegementDownloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegementDownloadResponse.Unmarshal(m, b)
}
func (m *SegementDownloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegementDownloadResponse.Marshal(b, m, deterministic)
}
func (dst *SegementDownloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegementDownloadResponse.Merge(dst, src)
}
func (m *SegementDownloadResponse) XXX_Size() int {
	return xxx_messageInfo_SegementDownloadResponse.Size(m)
}
func (m *SegementDownloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SegementDownloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SegementDownloadResponse proto.InternalMessageInfo

func (m *SegementDownloadResponse) GetAddressedLimits() []*AddressedOrderLimit {
	if m != nil {
		return m.AddressedLimits
	}
	return nil
}

func (m *SegementDownloadResponse) GetPointer() *Pointer {
	if m != nil {
		return m.Pointer
	}
	return nil
}

type SegmentDeleteRequest struct {
	Bucket               []byte   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path                 []byte   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Segment              int64    `protobuf:"varint,3,opt,name=segment,proto3" json:"segment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentDeleteRequest) Reset()         { *m = SegmentDeleteRequest{} }
func (m *SegmentDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*SegmentDeleteRequest) ProtoMessage()    {}
func (*SegmentDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{9}
}
func (m *SegmentDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentDeleteRequest.Unmarshal(m, b)
}
func (m *SegmentDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentDeleteRequest.Marshal(b, m, deterministic)
}
func (dst *SegmentDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentDeleteRequest.Merge(dst, src)
}
func (m *SegmentDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_SegmentDeleteRequest.Size(m)
}
func (m *SegmentDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentDeleteRequest proto.InternalMessageInfo

func (m *SegmentDeleteRequest) GetBucket() []byte {
	if m != nil {
		return m.Bucket
	}
	return nil
}

func (m *SegmentDeleteRequest) GetPath() []byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *SegmentDeleteRequest) GetSegment() int64 {
	if m != nil {
		return m.Segment
	}
	return 0
}

type OrderLimitResponse struct {
	AddressedLimits      []*AddressedOrderLimit `protobuf:"bytes,1,rep,name=addressed_limits,json=addressedLimits,proto3" json:"addressed_limits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OrderLimitResponse) Reset()         { *m = OrderLimitResponse{} }
func (m *OrderLimitResponse) String() string { return proto.CompactTextString(m) }
func (*OrderLimitResponse) ProtoMessage()    {}
func (*OrderLimitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{10}
}
func (m *OrderLimitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderLimitResponse.Unmarshal(m, b)
}
func (m *OrderLimitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderLimitResponse.Marshal(b, m, deterministic)
}
func (dst *OrderLimitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderLimitResponse.Merge(dst, src)
}
func (m *OrderLimitResponse) XXX_Size() int {
	return xxx_messageInfo_OrderLimitResponse.Size(m)
}
func (m *OrderLimitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderLimitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderLimitResponse proto.InternalMessageInfo

func (m *OrderLimitResponse) GetAddressedLimits() []*AddressedOrderLimit {
	if m != nil {
		return m.AddressedLimits
	}
	return nil
}

type ListSegmentsRequest struct {
	Bucket               []byte   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix               string   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	StartAfter           string   `protobuf:"bytes,3,opt,name=start_after,json=startAfter,proto3" json:"start_after,omitempty"`
	EndBefore            string   `protobuf:"bytes,4,opt,name=end_before,json=endBefore,proto3" json:"end_before,omitempty"`
	Recursive            bool     `protobuf:"varint,5,opt,name=recursive,proto3" json:"recursive,omitempty"`
	Limit                int32    `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	MetaFlags            uint32   `protobuf:"fixed32,7,opt,name=meta_flags,json=metaFlags,proto3" json:"meta_flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSegmentsRequest) Reset()         { *m = ListSegmentsRequest{} }
func (m *ListSegmentsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSegmentsRequest) ProtoMessage()    {}
func (*ListSegmentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{11}
}
func (m *ListSegmentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSegmentsRequest.Unmarshal(m, b)
}
func (m *ListSegmentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSegmentsRequest.Marshal(b, m, deterministic)
}
func (dst *ListSegmentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSegmentsRequest.Merge(dst, src)
}
func (m *ListSegmentsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSegmentsRequest.Size(m)
}
func (m *ListSegmentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSegmentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSegmentsRequest proto.InternalMessageInfo

func (m *ListSegmentsRequest) GetBucket() []byte {
	if m != nil {
		return m.Bucket
	}
	return nil
}

func (m *ListSegmentsRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *ListSegmentsRequest) GetStartAfter() string {
	if m != nil {
		return m.StartAfter
	}
	return ""
}

func (m *ListSegmentsRequest) GetEndBefore() string {
	if m != nil {
		return m.EndBefore
	}
	return ""
}

func (m *ListSegmentsRequest) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

func (m *ListSegmentsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListSegmentsRequest) GetMetaFlags() uint32 {
	if m != nil {
		return m.MetaFlags
	}
	return 0
}

type ListSegmentsResponse struct {
	Items                []*ListSegmentsResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	More                 bool                         `protobuf:"varint,2,opt,name=more,proto3" json:"more,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ListSegmentsResponse) Reset()         { *m = ListSegmentsResponse{} }
func (m *ListSegmentsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSegmentsResponse) ProtoMessage()    {}
func (*ListSegmentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{12}
}
func (m *ListSegmentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSegmentsResponse.Unmarshal(m, b)
}
func (m *ListSegmentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSegmentsResponse.Marshal(b, m, deterministic)
}
func (dst *ListSegmentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSegmentsResponse.Merge(dst, src)
}
func (m *ListSegmentsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSegmentsResponse.Size(m)
}
func (m *ListSegmentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSegmentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSegmentsResponse proto.InternalMessageInfo

func (m *ListSegmentsResponse) GetItems() []*ListSegmentsResponse_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListSegmentsResponse) GetMore() bool {
	if m != nil {
		return m.More
	}
	return false
}

type ListSegmentsResponse_Item struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Pointer              *Pointer `protobuf:"bytes,2,opt,name=pointer,proto3" json:"pointer,omitempty"`
	IsPrefix             bool     `protobuf:"varint,3,opt,name=is_prefix,json=isPrefix,proto3" json:"is_prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSegmentsResponse_Item) Reset()         { *m = ListSegmentsResponse_Item{} }
func (m *ListSegmentsResponse_Item) String() string { return proto.CompactTextString(m) }
func (*ListSegmentsResponse_Item) ProtoMessage()    {}
func (*ListSegmentsResponse_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_metainfo_f76717fd38f6a75f, []int{12, 0}
}
func (m *ListSegmentsResponse_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSegmentsResponse_Item.Unmarshal(m, b)
}
func (m *ListSegmentsResponse_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSegmentsResponse_Item.Marshal(b, m, deterministic)
}
func (dst *ListSegmentsResponse_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSegmentsResponse_Item.Merge(dst, src)
}
func (m *ListSegmentsResponse_Item) XXX_Size() int {
	return xxx_messageInfo_ListSegmentsResponse_Item.Size(m)
}
func (m *ListSegmentsResponse_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSegmentsResponse_Item.DiscardUnknown(m)
}

var xxx_messageInfo_ListSegmentsResponse_Item proto.InternalMessageInfo

func (m *ListSegmentsResponse_Item) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ListSegmentsResponse_Item) GetPointer() *Pointer {
	if m != nil {
		return m.Pointer
	}
	return nil
}

func (m *ListSegmentsResponse_Item) GetIsPrefix() bool {
	if m != nil {
		return m.IsPrefix
	}
	return false
}

func init() {
	proto.RegisterType((*OrderLimit2)(nil), "metainfo.OrderLimit2")
	proto.RegisterType((*AddressedOrderLimit)(nil), "metainfo.AddressedOrderLimit")
	proto.RegisterType((*Order2)(nil), "metainfo.Order2")
	proto.RegisterType((*PieceHash)(nil), "metainfo.PieceHash")
	proto.RegisterType((*SegmentWriteRequest)(nil), "metainfo.SegmentWriteRequest")
	proto.RegisterType((*SegmentCommitRequest)(nil), "metainfo.SegmentCommitRequest")
	proto.RegisterType((*SegmentCommitResponse)(nil), "metainfo.SegmentCommitResponse")
	proto.RegisterType((*SegementDownloadRequest)(nil), "metainfo.SegementDownloadRequest")
	proto.RegisterType((*SegementDownloadResponse)(nil), "metainfo.SegementDownloadResponse")
	proto.RegisterType((*SegmentDeleteRequest)(nil), "metainfo.SegmentDeleteRequest")
	proto.RegisterType((*OrderLimitResponse)(nil), "metainfo.OrderLimitResponse")
	proto.RegisterType((*ListSegmentsRequest)(nil), "metainfo.ListSegmentsRequest")
	proto.RegisterType((*ListSegmentsResponse)(nil), "metainfo.ListSegmentsResponse")
	proto.RegisterType((*ListSegmentsResponse_Item)(nil), "metainfo.ListSegmentsResponse.Item")
	proto.RegisterEnum("metainfo.Action", Action_name, Action_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetainfoClient is the client API for Metainfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetainfoClient interface {
	CreateSegment(ctx context.Context, in *SegmentWriteRequest, opts ...grpc.CallOption) (*OrderLimitResponse, error)
	CommitSegment(ctx context.Context, in *SegmentCommitRequest, opts ...grpc.CallOption) (*SegmentCommitResponse, error)
	DownloadSegment(ctx context.Context, in *SegementDownloadRequest, opts ...grpc.CallOption) (*SegementDownloadRequest, error)
	DeleteSegment(ctx context.Context, in *SegmentDeleteRequest, opts ...grpc.CallOption) (*OrderLimitResponse, error)
	ListSegment(ctx context.Context, in *ListSegmentsRequest, opts ...grpc.CallOption) (*ListSegmentsResponse, error)
}

type metainfoClient struct {
	cc *grpc.ClientConn
}

func NewMetainfoClient(cc *grpc.ClientConn) MetainfoClient {
	return &metainfoClient{cc}
}

func (c *metainfoClient) CreateSegment(ctx context.Context, in *SegmentWriteRequest, opts ...grpc.CallOption) (*OrderLimitResponse, error) {
	out := new(OrderLimitResponse)
	err := c.cc.Invoke(ctx, "/metainfo.Metainfo/CreateSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metainfoClient) CommitSegment(ctx context.Context, in *SegmentCommitRequest, opts ...grpc.CallOption) (*SegmentCommitResponse, error) {
	out := new(SegmentCommitResponse)
	err := c.cc.Invoke(ctx, "/metainfo.Metainfo/CommitSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metainfoClient) DownloadSegment(ctx context.Context, in *SegementDownloadRequest, opts ...grpc.CallOption) (*SegementDownloadRequest, error) {
	out := new(SegementDownloadRequest)
	err := c.cc.Invoke(ctx, "/metainfo.Metainfo/DownloadSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metainfoClient) DeleteSegment(ctx context.Context, in *SegmentDeleteRequest, opts ...grpc.CallOption) (*OrderLimitResponse, error) {
	out := new(OrderLimitResponse)
	err := c.cc.Invoke(ctx, "/metainfo.Metainfo/DeleteSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metainfoClient) ListSegment(ctx context.Context, in *ListSegmentsRequest, opts ...grpc.CallOption) (*ListSegmentsResponse, error) {
	out := new(ListSegmentsResponse)
	err := c.cc.Invoke(ctx, "/metainfo.Metainfo/ListSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetainfoServer is the server API for Metainfo service.
type MetainfoServer interface {
	CreateSegment(context.Context, *SegmentWriteRequest) (*OrderLimitResponse, error)
	CommitSegment(context.Context, *SegmentCommitRequest) (*SegmentCommitResponse, error)
	DownloadSegment(context.Context, *SegementDownloadRequest) (*SegementDownloadRequest, error)
	DeleteSegment(context.Context, *SegmentDeleteRequest) (*OrderLimitResponse, error)
	ListSegment(context.Context, *ListSegmentsRequest) (*ListSegmentsResponse, error)
}

func RegisterMetainfoServer(s *grpc.Server, srv MetainfoServer) {
	s.RegisterService(&_Metainfo_serviceDesc, srv)
}

func _Metainfo_CreateSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetainfoServer).CreateSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metainfo.Metainfo/CreateSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetainfoServer).CreateSegment(ctx, req.(*SegmentWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metainfo_CommitSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetainfoServer).CommitSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metainfo.Metainfo/CommitSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetainfoServer).CommitSegment(ctx, req.(*SegmentCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metainfo_DownloadSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegementDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetainfoServer).DownloadSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metainfo.Metainfo/DownloadSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetainfoServer).DownloadSegment(ctx, req.(*SegementDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metainfo_DeleteSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetainfoServer).DeleteSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metainfo.Metainfo/DeleteSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetainfoServer).DeleteSegment(ctx, req.(*SegmentDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metainfo_ListSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetainfoServer).ListSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metainfo.Metainfo/ListSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetainfoServer).ListSegment(ctx, req.(*ListSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Metainfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "metainfo.Metainfo",
	HandlerType: (*MetainfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSegment",
			Handler:    _Metainfo_CreateSegment_Handler,
		},
		{
			MethodName: "CommitSegment",
			Handler:    _Metainfo_CommitSegment_Handler,
		},
		{
			MethodName: "DownloadSegment",
			Handler:    _Metainfo_DownloadSegment_Handler,
		},
		{
			MethodName: "DeleteSegment",
			Handler:    _Metainfo_DeleteSegment_Handler,
		},
		{
			MethodName: "ListSegment",
			Handler:    _Metainfo_ListSegment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metainfo.proto",
}

func init() { proto.RegisterFile("metainfo.proto", fileDescriptor_metainfo_f76717fd38f6a75f) }

var fileDescriptor_metainfo_f76717fd38f6a75f = []byte{
	// 1065 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xee, 0x66, 0xfd, 0x7b, 0x5c, 0xc7, 0x66, 0x92, 0xb6, 0xc6, 0x34, 0x4d, 0xd8, 0xde, 0x98,
	0x16, 0x39, 0xc2, 0x48, 0x48, 0x5c, 0x3a, 0xb1, 0x69, 0x2d, 0x39, 0xc1, 0x9a, 0x38, 0x14, 0x21,
	0xc4, 0x6a, 0x9d, 0x3d, 0x76, 0x46, 0xf5, 0xfe, 0xb0, 0x33, 0x86, 0xa8, 0x2f, 0xc0, 0x0d, 0x57,
	0x3c, 0x01, 0xf7, 0xbc, 0x08, 0x17, 0x3c, 0x00, 0xe2, 0xa2, 0x6f, 0xc1, 0x3d, 0x9a, 0xd9, 0xd9,
	0x1f, 0x37, 0x0e, 0x81, 0xaa, 0x77, 0x73, 0xce, 0x9c, 0xdf, 0xef, 0x7c, 0x67, 0x76, 0x61, 0xdb,
	0x43, 0xe1, 0x30, 0x7f, 0x1e, 0x74, 0xc3, 0x28, 0x10, 0x01, 0xa9, 0x24, 0x72, 0x1b, 0x16, 0xc1,
	0x42, 0x6b, 0xdb, 0xfb, 0x8b, 0x20, 0x58, 0x2c, 0xf1, 0x50, 0x49, 0xb3, 0xd5, 0xfc, 0x50, 0x30,
	0x0f, 0xb9, 0x70, 0xbc, 0x50, 0x1b, 0x80, 0x1f, 0xb8, 0xa8, 0xcf, 0x8d, 0x30, 0x60, 0xbe, 0xc0,
	0xc8, 0x9d, 0xc5, 0x0a, 0xeb, 0x6f, 0x13, 0x6a, 0x5f, 0x46, 0x2e, 0x46, 0x63, 0xe6, 0x31, 0xd1,
	0x23, 0x8f, 0xa1, 0xce, 0x31, 0x62, 0xce, 0xd2, 0xf6, 0x57, 0xde, 0x0c, 0xa3, 0x96, 0x71, 0x60,
	0x74, 0xee, 0xd2, 0xbb, 0xb1, 0xf2, 0x54, 0xe9, 0xc8, 0x27, 0x70, 0x97, 0x3b, 0x02, 0x97, 0x4b,
	0x26, 0xd0, 0x66, 0x6e, 0x6b, 0x4b, 0xda, 0x1c, 0x6d, 0xff, 0xfe, 0x7a, 0xff, 0xce, 0x5f, 0xaf,
	0xf7, 0x4b, 0xa7, 0x81, 0x8b, 0xa3, 0x01, 0xad, 0xa5, 0x36, 0x23, 0x97, 0x3c, 0x85, 0xea, 0x2a,
	0x5c, 0x32, 0xff, 0xa5, 0xb4, 0x37, 0x37, 0xda, 0x57, 0x62, 0x83, 0x91, 0x4b, 0x3e, 0x83, 0x06,
	0x17, 0x41, 0xe4, 0x2c, 0xd0, 0x96, 0xb5, 0x4b, 0x97, 0xc2, 0x46, 0x97, 0xba, 0x36, 0x53, 0xa2,
	0x4b, 0x9e, 0x40, 0x25, 0x64, 0x78, 0xa1, 0x1c, 0x8a, 0xca, 0xa1, 0xa1, 0x1d, 0xca, 0x13, 0xa9,
	0x1f, 0x0d, 0x68, 0x59, 0x19, 0x8c, 0x5c, 0xb2, 0x0b, 0xc5, 0xa5, 0x6c, 0xb9, 0x55, 0x3a, 0x30,
	0x3a, 0x26, 0x8d, 0x05, 0xd2, 0x81, 0x92, 0x73, 0x21, 0x58, 0xe0, 0xb7, 0xca, 0x07, 0x46, 0x67,
	0xbb, 0xd7, 0xec, 0xa6, 0x33, 0xe8, 0x2b, 0x3d, 0xd5, 0xf7, 0x64, 0x08, 0xcd, 0x38, 0x17, 0x5e,
	0x85, 0x2c, 0x72, 0x94, 0x4f, 0xe5, 0xc0, 0xe8, 0xd4, 0x7a, 0xed, 0x6e, 0x3c, 0x91, 0x6e, 0x32,
	0x91, 0xee, 0x34, 0x99, 0x08, 0x6d, 0x28, 0x9f, 0x61, 0xea, 0x22, 0xc3, 0x04, 0x12, 0xfe, 0x7c,
	0x98, 0xea, 0xed, 0x61, 0x94, 0x4f, 0x2e, 0xcc, 0x21, 0xec, 0x64, 0x13, 0xe1, 0x6c, 0xe1, 0x3b,
	0x62, 0x15, 0x61, 0x0b, 0xd4, 0xf0, 0x48, 0x7a, 0x75, 0x96, 0xdc, 0x58, 0x3f, 0x19, 0xb0, 0xd3,
	0x77, 0xdd, 0x08, 0x39, 0x47, 0x37, 0x23, 0x00, 0x79, 0x9a, 0xc0, 0x62, 0xa8, 0x22, 0xee, 0x65,
	0xfd, 0xe7, 0x58, 0x92, 0xa0, 0x75, 0x0c, 0xbb, 0x6b, 0x73, 0x72, 0xe2, 0x80, 0x8a, 0x0f, 0xb5,
	0xde, 0x7b, 0x5d, 0x45, 0x3c, 0x39, 0x1b, 0x9d, 0x89, 0x92, 0xdc, 0xbc, 0xb4, 0xce, 0x0a, 0xa1,
	0xa4, 0x42, 0xff, 0x47, 0xee, 0xdd, 0x87, 0x92, 0xe3, 0x05, 0x2b, 0x5f, 0xa8, 0x2c, 0x26, 0xd5,
	0x12, 0xf9, 0x08, 0x9a, 0x9a, 0x60, 0x59, 0xfb, 0x8a, 0x67, 0xb4, 0x11, 0xeb, 0xb3, 0xde, 0xbf,
	0x86, 0xaa, 0xa2, 0xc3, 0x73, 0x87, 0x5f, 0x92, 0xf7, 0x73, 0x9c, 0x89, 0xf3, 0xa5, 0x14, 0x21,
	0x50, 0xb8, 0x74, 0xf8, 0x65, 0x4c, 0x6f, 0xaa, 0xce, 0xe4, 0x21, 0x54, 0xdf, 0x8c, 0x9f, 0x29,
	0xac, 0x9f, 0x0d, 0xd8, 0x39, 0xc3, 0x85, 0x87, 0xbe, 0x78, 0x11, 0x31, 0x81, 0x14, 0xbf, 0x5f,
	0x21, 0x17, 0xb2, 0xe8, 0xd9, 0xea, 0xe2, 0x25, 0x0a, 0x9d, 0x42, 0x4b, 0x32, 0x43, 0xe8, 0x88,
	0x34, 0x83, 0x3c, 0x93, 0x7d, 0xa8, 0x89, 0x40, 0x48, 0x10, 0x02, 0x17, 0xb9, 0xca, 0x51, 0xa4,
	0xa0, 0x54, 0x12, 0x36, 0x4e, 0x3a, 0xd0, 0xf4, 0x9c, 0x2b, 0x9b, 0xc7, 0x79, 0x6c, 0xce, 0x5e,
	0xa1, 0x5a, 0x0f, 0x93, 0x6e, 0x7b, 0xce, 0x95, 0x4e, 0x7f, 0xc6, 0x5e, 0xa1, 0xf5, 0x9b, 0x01,
	0xbb, 0x5a, 0x3e, 0x0e, 0x3c, 0x8f, 0x89, 0xb7, 0xa9, 0xa7, 0x05, 0x65, 0x9d, 0x4a, 0xd5, 0x62,
	0xd2, 0x44, 0x24, 0x27, 0xd0, 0x5a, 0x1b, 0xbf, 0xc2, 0x4d, 0xa2, 0x84, 0xbc, 0x55, 0x38, 0x30,
	0x3b, 0xb5, 0xde, 0x4e, 0x46, 0x9f, 0x14, 0x71, 0x7a, 0x3f, 0x47, 0x82, 0x49, 0xe6, 0x62, 0x3d,
	0x80, 0x7b, 0x6f, 0x14, 0xcb, 0xc3, 0xc0, 0xe7, 0x68, 0xd9, 0xf0, 0xe0, 0x0c, 0x17, 0x28, 0x6f,
	0x06, 0xc1, 0x8f, 0xfe, 0x32, 0x70, 0xdc, 0x77, 0xda, 0x88, 0xf5, 0x8b, 0x01, 0xad, 0xeb, 0x19,
	0xe2, 0xec, 0xe4, 0x39, 0x34, 0x9d, 0x64, 0x51, 0x6c, 0xc5, 0x7b, 0xde, 0x32, 0x54, 0x77, 0x7b,
	0xb9, 0xc7, 0xe1, 0xfa, 0x2a, 0xd1, 0x46, 0xea, 0xa6, 0x64, 0x4e, 0x3e, 0x86, 0xb2, 0x7e, 0x7e,
	0xf5, 0x86, 0x90, 0x6e, 0xf6, 0x1c, 0x4f, 0xe2, 0x13, 0x4d, 0x4c, 0xac, 0x6f, 0xd3, 0xd9, 0x0d,
	0x70, 0x89, 0x6f, 0xc7, 0xa5, 0x9b, 0x5b, 0xfe, 0x0e, 0x48, 0xae, 0xd4, 0x77, 0xde, 0xab, 0xf5,
	0xa7, 0x01, 0x3b, 0x63, 0xc6, 0x85, 0x6e, 0x81, 0xdf, 0x56, 0xfd, 0x7d, 0x28, 0x85, 0x11, 0xce,
	0xd9, 0x95, 0xaa, 0xbf, 0x4a, 0xb5, 0x24, 0xb7, 0x81, 0x0b, 0x27, 0x12, 0xb6, 0x33, 0x97, 0xb8,
	0x99, 0xea, 0x12, 0x94, 0xaa, 0x2f, 0x35, 0x64, 0x0f, 0x00, 0x7d, 0xd7, 0x9e, 0xe1, 0x3c, 0x88,
	0xe2, 0x3d, 0xa8, 0xd2, 0x2a, 0xfa, 0xee, 0x91, 0x52, 0xc8, 0x7d, 0x8d, 0xf0, 0x62, 0x15, 0x71,
	0xf6, 0x03, 0xaa, 0x6f, 0x42, 0x85, 0x66, 0x8a, 0xf5, 0x8f, 0x40, 0x31, 0x79, 0xd6, 0xf6, 0x00,
	0x64, 0xb3, 0xf6, 0x7c, 0xe9, 0x2c, 0xb8, 0xfa, 0x10, 0x94, 0x69, 0x55, 0x6a, 0xbe, 0x90, 0x0a,
	0xeb, 0x0f, 0x03, 0x76, 0xd7, 0x5b, 0xd3, 0xe8, 0x7d, 0x0e, 0x45, 0x26, 0xd0, 0x4b, 0x20, 0x7b,
	0x9c, 0x41, 0xb6, 0xc9, 0xbc, 0x3b, 0x12, 0xe8, 0xd1, 0xd8, 0x43, 0x0e, 0xcf, 0x93, 0xf5, 0x6f,
	0xa9, 0x0a, 0xd5, 0xb9, 0x8d, 0x50, 0x90, 0x26, 0xe9, 0x60, 0x0d, 0xd5, 0x5b, 0x3c, 0xd8, 0xff,
	0x45, 0x25, 0xf2, 0x01, 0x54, 0x19, 0xb7, 0x35, 0xbe, 0xa6, 0x4a, 0x51, 0x61, 0x7c, 0xa2, 0xe4,
	0x27, 0x33, 0x28, 0xc5, 0x9f, 0x36, 0x52, 0x83, 0xf2, 0xe8, 0xf4, 0xab, 0xfe, 0x78, 0x34, 0x68,
	0xde, 0x21, 0x65, 0x30, 0x27, 0xe7, 0xd3, 0xa6, 0x21, 0x0f, 0xcf, 0x86, 0xd3, 0xe6, 0x16, 0xa9,
	0x43, 0xf5, 0xd9, 0x70, 0x6a, 0xf7, 0xcf, 0x07, 0xa3, 0x69, 0xd3, 0x24, 0xdb, 0x00, 0x52, 0xa4,
	0xc3, 0x49, 0x7f, 0x44, 0x9b, 0x05, 0x29, 0x4f, 0xce, 0x53, 0xb9, 0x48, 0x00, 0x4a, 0x83, 0xe1,
	0x78, 0x38, 0x1d, 0x36, 0x4b, 0xbd, 0x5f, 0x4d, 0xa8, 0x9c, 0x68, 0x30, 0xc8, 0x18, 0xea, 0xc7,
	0x11, 0x3a, 0x02, 0x35, 0x22, 0x24, 0xc7, 0xad, 0x0d, 0x8f, 0x67, 0xfb, 0xe1, 0xa6, 0x6f, 0x50,
	0x0a, 0xfa, 0x04, 0xea, 0xf1, 0x73, 0x91, 0x44, 0x7b, 0x74, 0x2d, 0xda, 0xda, 0xdb, 0xd7, 0xde,
	0xbf, 0xf1, 0x5e, 0x47, 0x7c, 0x01, 0x8d, 0xe4, 0x11, 0x48, 0x62, 0x7e, 0xb8, 0xe6, 0xb3, 0xe9,
	0x25, 0x6a, 0xdf, 0x6e, 0x42, 0x4e, 0xa0, 0x1e, 0xaf, 0xf2, 0xcd, 0xa5, 0xae, 0xad, 0xfa, 0x2d,
	0x9d, 0x8f, 0xa1, 0x96, 0xe3, 0x55, 0x1e, 0xc5, 0x0d, 0x8b, 0xd7, 0x7e, 0xf4, 0xef, 0x6c, 0x3c,
	0x2a, 0x7c, 0xb3, 0x15, 0xce, 0x66, 0x25, 0xf5, 0xb3, 0xf1, 0xe9, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x81, 0xd8, 0x4f, 0x97, 0x7b, 0x0a, 0x00, 0x00,
}
