// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: piecestore.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/duration"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type BandwidthAction int32

const (
	BandwidthAction_PUT        BandwidthAction = 0
	BandwidthAction_GET        BandwidthAction = 1
	BandwidthAction_GET_AUDIT  BandwidthAction = 2
	BandwidthAction_GET_REPAIR BandwidthAction = 3
	BandwidthAction_PUT_REPAIR BandwidthAction = 4
)

var BandwidthAction_name = map[int32]string{
	0: "PUT",
	1: "GET",
	2: "GET_AUDIT",
	3: "GET_REPAIR",
	4: "PUT_REPAIR",
}

var BandwidthAction_value = map[string]int32{
	"PUT":        0,
	"GET":        1,
	"GET_AUDIT":  2,
	"GET_REPAIR": 3,
	"PUT_REPAIR": 4,
}

func (x BandwidthAction) String() string {
	return proto.EnumName(BandwidthAction_name, int32(x))
}

func (BandwidthAction) EnumDescriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{0}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{0}
>>>>>>> 683988d7... fix merge
}

type PayerBandwidthAllocation struct {
	SatelliteId          NodeID          `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3,customtype=NodeID" json:"satellite_id"`
	UplinkId             NodeID          `protobuf:"bytes,2,opt,name=uplink_id,json=uplinkId,proto3,customtype=NodeID" json:"uplink_id"`
	MaxSize              int64           `protobuf:"varint,3,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	ExpirationUnixSec    int64           `protobuf:"varint,4,opt,name=expiration_unix_sec,json=expirationUnixSec,proto3" json:"expiration_unix_sec,omitempty"`
	SerialNumber         string          `protobuf:"bytes,5,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Action               BandwidthAction `protobuf:"varint,6,opt,name=action,proto3,enum=piecestoreroutes.BandwidthAction" json:"action,omitempty"`
	CreatedUnixSec       int64           `protobuf:"varint,7,opt,name=created_unix_sec,json=createdUnixSec,proto3" json:"created_unix_sec,omitempty"`
	Certs                [][]byte        `protobuf:"bytes,8,rep,name=certs,proto3" json:"certs,omitempty"`
	Signature            []byte          `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	StorageNodeIds       []NodeID        `protobuf:"bytes,10,rep,name=storage_node_ids,json=storageNodeIds,proto3,customtype=NodeID" json:"storage_node_ids"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PayerBandwidthAllocation) Reset()         { *m = PayerBandwidthAllocation{} }
func (m *PayerBandwidthAllocation) String() string { return proto.CompactTextString(m) }
func (*PayerBandwidthAllocation) ProtoMessage()    {}
func (*PayerBandwidthAllocation) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{0}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{0}
>>>>>>> 683988d7... fix merge
}
func (m *PayerBandwidthAllocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayerBandwidthAllocation.Unmarshal(m, b)
}
func (m *PayerBandwidthAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayerBandwidthAllocation.Marshal(b, m, deterministic)
}
func (m *PayerBandwidthAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayerBandwidthAllocation.Merge(m, src)
}
func (m *PayerBandwidthAllocation) XXX_Size() int {
	return xxx_messageInfo_PayerBandwidthAllocation.Size(m)
}
func (m *PayerBandwidthAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_PayerBandwidthAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_PayerBandwidthAllocation proto.InternalMessageInfo

func (m *PayerBandwidthAllocation) GetMaxSize() int64 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *PayerBandwidthAllocation) GetExpirationUnixSec() int64 {
	if m != nil {
		return m.ExpirationUnixSec
	}
	return 0
}

func (m *PayerBandwidthAllocation) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *PayerBandwidthAllocation) GetAction() BandwidthAction {
	if m != nil {
		return m.Action
	}
	return BandwidthAction_PUT
}

func (m *PayerBandwidthAllocation) GetCreatedUnixSec() int64 {
	if m != nil {
		return m.CreatedUnixSec
	}
	return 0
}

func (m *PayerBandwidthAllocation) GetCerts() [][]byte {
	if m != nil {
		return m.Certs
	}
	return nil
}

func (m *PayerBandwidthAllocation) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type RenterBandwidthAllocation struct {
	PayerAllocation      PayerBandwidthAllocation `protobuf:"bytes,1,opt,name=payer_allocation,json=payerAllocation,proto3" json:"payer_allocation"`
	Total                int64                    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	StorageNodeId        NodeID                   `protobuf:"bytes,3,opt,name=storage_node_id,json=storageNodeId,proto3,customtype=NodeID" json:"storage_node_id"`
	Certs                [][]byte                 `protobuf:"bytes,4,rep,name=certs,proto3" json:"certs,omitempty"`
	Signature            []byte                   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RenterBandwidthAllocation) Reset()         { *m = RenterBandwidthAllocation{} }
func (m *RenterBandwidthAllocation) String() string { return proto.CompactTextString(m) }
func (*RenterBandwidthAllocation) ProtoMessage()    {}
func (*RenterBandwidthAllocation) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{1}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{1}
>>>>>>> 683988d7... fix merge
}
func (m *RenterBandwidthAllocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenterBandwidthAllocation.Unmarshal(m, b)
}
func (m *RenterBandwidthAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenterBandwidthAllocation.Marshal(b, m, deterministic)
}
func (m *RenterBandwidthAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenterBandwidthAllocation.Merge(m, src)
}
func (m *RenterBandwidthAllocation) XXX_Size() int {
	return xxx_messageInfo_RenterBandwidthAllocation.Size(m)
}
func (m *RenterBandwidthAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_RenterBandwidthAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_RenterBandwidthAllocation proto.InternalMessageInfo

func (m *RenterBandwidthAllocation) GetPayerAllocation() PayerBandwidthAllocation {
	if m != nil {
		return m.PayerAllocation
	}
	return PayerBandwidthAllocation{}
}

func (m *RenterBandwidthAllocation) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RenterBandwidthAllocation) GetCerts() [][]byte {
	if m != nil {
		return m.Certs
	}
	return nil
}

func (m *RenterBandwidthAllocation) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type PieceStore struct {
	BandwidthAllocation  *RenterBandwidthAllocation `protobuf:"bytes,1,opt,name=bandwidth_allocation,json=bandwidthAllocation,proto3" json:"bandwidth_allocation,omitempty"`
	PieceData            *PieceStore_PieceData      `protobuf:"bytes,2,opt,name=piece_data,json=pieceData,proto3" json:"piece_data,omitempty"`
	Authorization        *SignedMessage             `protobuf:"bytes,3,opt,name=authorization,proto3" json:"authorization,omitempty"` // Deprecated: Do not use.
	SignedHash           *SignedHash                `protobuf:"bytes,4,opt,name=signed_hash,json=signedHash,proto3" json:"signed_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PieceStore) Reset()         { *m = PieceStore{} }
func (m *PieceStore) String() string { return proto.CompactTextString(m) }
func (*PieceStore) ProtoMessage()    {}
func (*PieceStore) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{2}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{2}
>>>>>>> 683988d7... fix merge
}
func (m *PieceStore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieceStore.Unmarshal(m, b)
}
func (m *PieceStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieceStore.Marshal(b, m, deterministic)
}
func (m *PieceStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieceStore.Merge(m, src)
}
func (m *PieceStore) XXX_Size() int {
	return xxx_messageInfo_PieceStore.Size(m)
}
func (m *PieceStore) XXX_DiscardUnknown() {
	xxx_messageInfo_PieceStore.DiscardUnknown(m)
}

var xxx_messageInfo_PieceStore proto.InternalMessageInfo

func (m *PieceStore) GetBandwidthAllocation() *RenterBandwidthAllocation {
	if m != nil {
		return m.BandwidthAllocation
	}
	return nil
}

func (m *PieceStore) GetPieceData() *PieceStore_PieceData {
	if m != nil {
		return m.PieceData
	}
	return nil
}

// Deprecated: Do not use.
func (m *PieceStore) GetAuthorization() *SignedMessage {
	if m != nil {
		return m.Authorization
	}
	return nil
}

func (m *PieceStore) GetSignedHash() *SignedHash {
	if m != nil {
		return m.SignedHash
	}
	return nil
}

type PieceStore_PieceData struct {
	// TODO: may want to use customtype and fixed-length byte slice
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpirationUnixSec    int64    `protobuf:"varint,2,opt,name=expiration_unix_sec,json=expirationUnixSec,proto3" json:"expiration_unix_sec,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieceStore_PieceData) Reset()         { *m = PieceStore_PieceData{} }
func (m *PieceStore_PieceData) String() string { return proto.CompactTextString(m) }
func (*PieceStore_PieceData) ProtoMessage()    {}
func (*PieceStore_PieceData) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{2, 0}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{2, 0}
>>>>>>> 683988d7... fix merge
}
func (m *PieceStore_PieceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieceStore_PieceData.Unmarshal(m, b)
}
func (m *PieceStore_PieceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieceStore_PieceData.Marshal(b, m, deterministic)
}
func (m *PieceStore_PieceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieceStore_PieceData.Merge(m, src)
}
func (m *PieceStore_PieceData) XXX_Size() int {
	return xxx_messageInfo_PieceStore_PieceData.Size(m)
}
func (m *PieceStore_PieceData) XXX_DiscardUnknown() {
	xxx_messageInfo_PieceStore_PieceData.DiscardUnknown(m)
}

var xxx_messageInfo_PieceStore_PieceData proto.InternalMessageInfo

func (m *PieceStore_PieceData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PieceStore_PieceData) GetExpirationUnixSec() int64 {
	if m != nil {
		return m.ExpirationUnixSec
	}
	return 0
}

func (m *PieceStore_PieceData) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type PieceId struct {
	// TODO: may want to use customtype and fixed-length byte slice
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Authorization        *SignedMessage `protobuf:"bytes,2,opt,name=authorization,proto3" json:"authorization,omitempty"` // Deprecated: Do not use.
	SatelliteId          NodeID         `protobuf:"bytes,3,opt,name=satellite_id,json=satelliteId,proto3,customtype=NodeID" json:"satellite_id"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PieceId) Reset()         { *m = PieceId{} }
func (m *PieceId) String() string { return proto.CompactTextString(m) }
func (*PieceId) ProtoMessage()    {}
func (*PieceId) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{3}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{3}
>>>>>>> 683988d7... fix merge
}
func (m *PieceId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieceId.Unmarshal(m, b)
}
func (m *PieceId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieceId.Marshal(b, m, deterministic)
}
func (m *PieceId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieceId.Merge(m, src)
}
func (m *PieceId) XXX_Size() int {
	return xxx_messageInfo_PieceId.Size(m)
}
func (m *PieceId) XXX_DiscardUnknown() {
	xxx_messageInfo_PieceId.DiscardUnknown(m)
}

var xxx_messageInfo_PieceId proto.InternalMessageInfo

func (m *PieceId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Deprecated: Do not use.
func (m *PieceId) GetAuthorization() *SignedMessage {
	if m != nil {
		return m.Authorization
	}
	return nil
}

type PieceSummary struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PieceSize            int64    `protobuf:"varint,2,opt,name=piece_size,json=pieceSize,proto3" json:"piece_size,omitempty"`
	ExpirationUnixSec    int64    `protobuf:"varint,3,opt,name=expiration_unix_sec,json=expirationUnixSec,proto3" json:"expiration_unix_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieceSummary) Reset()         { *m = PieceSummary{} }
func (m *PieceSummary) String() string { return proto.CompactTextString(m) }
func (*PieceSummary) ProtoMessage()    {}
func (*PieceSummary) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{4}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{4}
>>>>>>> 683988d7... fix merge
}
func (m *PieceSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieceSummary.Unmarshal(m, b)
}
func (m *PieceSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieceSummary.Marshal(b, m, deterministic)
}
func (m *PieceSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieceSummary.Merge(m, src)
}
func (m *PieceSummary) XXX_Size() int {
	return xxx_messageInfo_PieceSummary.Size(m)
}
func (m *PieceSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_PieceSummary.DiscardUnknown(m)
}

var xxx_messageInfo_PieceSummary proto.InternalMessageInfo

func (m *PieceSummary) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PieceSummary) GetPieceSize() int64 {
	if m != nil {
		return m.PieceSize
	}
	return 0
}

func (m *PieceSummary) GetExpirationUnixSec() int64 {
	if m != nil {
		return m.ExpirationUnixSec
	}
	return 0
}

type PieceRetrieval struct {
	BandwidthAllocation  *RenterBandwidthAllocation `protobuf:"bytes,1,opt,name=bandwidth_allocation,json=bandwidthAllocation,proto3" json:"bandwidth_allocation,omitempty"`
	PieceData            *PieceRetrieval_PieceData  `protobuf:"bytes,2,opt,name=piece_data,json=pieceData,proto3" json:"piece_data,omitempty"`
	Authorization        *SignedMessage             `protobuf:"bytes,3,opt,name=authorization,proto3" json:"authorization,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PieceRetrieval) Reset()         { *m = PieceRetrieval{} }
func (m *PieceRetrieval) String() string { return proto.CompactTextString(m) }
func (*PieceRetrieval) ProtoMessage()    {}
func (*PieceRetrieval) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{5}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{5}
>>>>>>> 683988d7... fix merge
}
func (m *PieceRetrieval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieceRetrieval.Unmarshal(m, b)
}
func (m *PieceRetrieval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieceRetrieval.Marshal(b, m, deterministic)
}
func (m *PieceRetrieval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieceRetrieval.Merge(m, src)
}
func (m *PieceRetrieval) XXX_Size() int {
	return xxx_messageInfo_PieceRetrieval.Size(m)
}
func (m *PieceRetrieval) XXX_DiscardUnknown() {
	xxx_messageInfo_PieceRetrieval.DiscardUnknown(m)
}

var xxx_messageInfo_PieceRetrieval proto.InternalMessageInfo

func (m *PieceRetrieval) GetBandwidthAllocation() *RenterBandwidthAllocation {
	if m != nil {
		return m.BandwidthAllocation
	}
	return nil
}

func (m *PieceRetrieval) GetPieceData() *PieceRetrieval_PieceData {
	if m != nil {
		return m.PieceData
	}
	return nil
}

// Deprecated: Do not use.
func (m *PieceRetrieval) GetAuthorization() *SignedMessage {
	if m != nil {
		return m.Authorization
	}
	return nil
}

type PieceRetrieval_PieceData struct {
	// TODO: may want to use customtype and fixed-length byte slice
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PieceSize            int64    `protobuf:"varint,2,opt,name=piece_size,json=pieceSize,proto3" json:"piece_size,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieceRetrieval_PieceData) Reset()         { *m = PieceRetrieval_PieceData{} }
func (m *PieceRetrieval_PieceData) String() string { return proto.CompactTextString(m) }
func (*PieceRetrieval_PieceData) ProtoMessage()    {}
func (*PieceRetrieval_PieceData) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{5, 0}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{5, 0}
>>>>>>> 683988d7... fix merge
}
func (m *PieceRetrieval_PieceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieceRetrieval_PieceData.Unmarshal(m, b)
}
func (m *PieceRetrieval_PieceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieceRetrieval_PieceData.Marshal(b, m, deterministic)
}
func (m *PieceRetrieval_PieceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieceRetrieval_PieceData.Merge(m, src)
}
func (m *PieceRetrieval_PieceData) XXX_Size() int {
	return xxx_messageInfo_PieceRetrieval_PieceData.Size(m)
}
func (m *PieceRetrieval_PieceData) XXX_DiscardUnknown() {
	xxx_messageInfo_PieceRetrieval_PieceData.DiscardUnknown(m)
}

var xxx_messageInfo_PieceRetrieval_PieceData proto.InternalMessageInfo

func (m *PieceRetrieval_PieceData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PieceRetrieval_PieceData) GetPieceSize() int64 {
	if m != nil {
		return m.PieceSize
	}
	return 0
}

func (m *PieceRetrieval_PieceData) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type PieceRetrievalStream struct {
	PieceSize            int64    `protobuf:"varint,1,opt,name=piece_size,json=pieceSize,proto3" json:"piece_size,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieceRetrievalStream) Reset()         { *m = PieceRetrievalStream{} }
func (m *PieceRetrievalStream) String() string { return proto.CompactTextString(m) }
func (*PieceRetrievalStream) ProtoMessage()    {}
func (*PieceRetrievalStream) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{6}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{6}
>>>>>>> 683988d7... fix merge
}
func (m *PieceRetrievalStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieceRetrievalStream.Unmarshal(m, b)
}
func (m *PieceRetrievalStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieceRetrievalStream.Marshal(b, m, deterministic)
}
func (m *PieceRetrievalStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieceRetrievalStream.Merge(m, src)
}
func (m *PieceRetrievalStream) XXX_Size() int {
	return xxx_messageInfo_PieceRetrievalStream.Size(m)
}
func (m *PieceRetrievalStream) XXX_DiscardUnknown() {
	xxx_messageInfo_PieceRetrievalStream.DiscardUnknown(m)
}

var xxx_messageInfo_PieceRetrievalStream proto.InternalMessageInfo

func (m *PieceRetrievalStream) GetPieceSize() int64 {
	if m != nil {
		return m.PieceSize
	}
	return 0
}

func (m *PieceRetrievalStream) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type PieceDelete struct {
	// TODO: may want to use customtype and fixed-length byte slice
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Authorization        *SignedMessage `protobuf:"bytes,3,opt,name=authorization,proto3" json:"authorization,omitempty"` // Deprecated: Do not use.
	SatelliteId          NodeID         `protobuf:"bytes,4,opt,name=satellite_id,json=satelliteId,proto3,customtype=NodeID" json:"satellite_id"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PieceDelete) Reset()         { *m = PieceDelete{} }
func (m *PieceDelete) String() string { return proto.CompactTextString(m) }
func (*PieceDelete) ProtoMessage()    {}
func (*PieceDelete) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{7}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{7}
>>>>>>> 683988d7... fix merge
}
func (m *PieceDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieceDelete.Unmarshal(m, b)
}
func (m *PieceDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieceDelete.Marshal(b, m, deterministic)
}
func (m *PieceDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieceDelete.Merge(m, src)
}
func (m *PieceDelete) XXX_Size() int {
	return xxx_messageInfo_PieceDelete.Size(m)
}
func (m *PieceDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_PieceDelete.DiscardUnknown(m)
}

var xxx_messageInfo_PieceDelete proto.InternalMessageInfo

func (m *PieceDelete) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Deprecated: Do not use.
func (m *PieceDelete) GetAuthorization() *SignedMessage {
	if m != nil {
		return m.Authorization
	}
	return nil
}

type PieceDeleteSummary struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieceDeleteSummary) Reset()         { *m = PieceDeleteSummary{} }
func (m *PieceDeleteSummary) String() string { return proto.CompactTextString(m) }
func (*PieceDeleteSummary) ProtoMessage()    {}
func (*PieceDeleteSummary) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{8}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{8}
>>>>>>> 683988d7... fix merge
}
func (m *PieceDeleteSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieceDeleteSummary.Unmarshal(m, b)
}
func (m *PieceDeleteSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieceDeleteSummary.Marshal(b, m, deterministic)
}
func (m *PieceDeleteSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieceDeleteSummary.Merge(m, src)
}
func (m *PieceDeleteSummary) XXX_Size() int {
	return xxx_messageInfo_PieceDeleteSummary.Size(m)
}
func (m *PieceDeleteSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_PieceDeleteSummary.DiscardUnknown(m)
}

var xxx_messageInfo_PieceDeleteSummary proto.InternalMessageInfo

func (m *PieceDeleteSummary) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PieceStoreSummary struct {
	Message              string      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TotalReceived        int64       `protobuf:"varint,2,opt,name=total_received,json=totalReceived,proto3" json:"total_received,omitempty"`
	SignedHash           *SignedHash `protobuf:"bytes,3,opt,name=signed_hash,json=signedHash,proto3" json:"signed_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PieceStoreSummary) Reset()         { *m = PieceStoreSummary{} }
func (m *PieceStoreSummary) String() string { return proto.CompactTextString(m) }
func (*PieceStoreSummary) ProtoMessage()    {}
func (*PieceStoreSummary) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{9}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{9}
>>>>>>> 683988d7... fix merge
}
func (m *PieceStoreSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieceStoreSummary.Unmarshal(m, b)
}
func (m *PieceStoreSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieceStoreSummary.Marshal(b, m, deterministic)
}
func (m *PieceStoreSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieceStoreSummary.Merge(m, src)
}
func (m *PieceStoreSummary) XXX_Size() int {
	return xxx_messageInfo_PieceStoreSummary.Size(m)
}
func (m *PieceStoreSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_PieceStoreSummary.DiscardUnknown(m)
}

var xxx_messageInfo_PieceStoreSummary proto.InternalMessageInfo

func (m *PieceStoreSummary) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PieceStoreSummary) GetTotalReceived() int64 {
	if m != nil {
		return m.TotalReceived
	}
	return 0
}

func (m *PieceStoreSummary) GetSignedHash() *SignedHash {
	if m != nil {
		return m.SignedHash
	}
	return nil
}

<<<<<<< HEAD
=======
type StatsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsReq) Reset()         { *m = StatsReq{} }
func (m *StatsReq) String() string { return proto.CompactTextString(m) }
func (*StatsReq) ProtoMessage()    {}
func (*StatsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{10}
}
func (m *StatsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsReq.Unmarshal(m, b)
}
func (m *StatsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsReq.Marshal(b, m, deterministic)
}
func (dst *StatsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsReq.Merge(dst, src)
}
func (m *StatsReq) XXX_Size() int {
	return xxx_messageInfo_StatsReq.Size(m)
}
func (m *StatsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsReq.DiscardUnknown(m)
}

var xxx_messageInfo_StatsReq proto.InternalMessageInfo

type StatSummary struct {
	UsedSpace            int64    `protobuf:"varint,1,opt,name=used_space,json=usedSpace,proto3" json:"used_space,omitempty"`
	AvailableSpace       int64    `protobuf:"varint,2,opt,name=available_space,json=availableSpace,proto3" json:"available_space,omitempty"`
	UsedBandwidth        int64    `protobuf:"varint,3,opt,name=used_bandwidth,json=usedBandwidth,proto3" json:"used_bandwidth,omitempty"`
	AvailableBandwidth   int64    `protobuf:"varint,4,opt,name=available_bandwidth,json=availableBandwidth,proto3" json:"available_bandwidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatSummary) Reset()         { *m = StatSummary{} }
func (m *StatSummary) String() string { return proto.CompactTextString(m) }
func (*StatSummary) ProtoMessage()    {}
func (*StatSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{11}
}
func (m *StatSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatSummary.Unmarshal(m, b)
}
func (m *StatSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatSummary.Marshal(b, m, deterministic)
}
func (dst *StatSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatSummary.Merge(dst, src)
}
func (m *StatSummary) XXX_Size() int {
	return xxx_messageInfo_StatSummary.Size(m)
}
func (m *StatSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_StatSummary.DiscardUnknown(m)
}

var xxx_messageInfo_StatSummary proto.InternalMessageInfo

func (m *StatSummary) GetUsedSpace() int64 {
	if m != nil {
		return m.UsedSpace
	}
	return 0
}

func (m *StatSummary) GetAvailableSpace() int64 {
	if m != nil {
		return m.AvailableSpace
	}
	return 0
}

func (m *StatSummary) GetUsedBandwidth() int64 {
	if m != nil {
		return m.UsedBandwidth
	}
	return 0
}

func (m *StatSummary) GetAvailableBandwidth() int64 {
	if m != nil {
		return m.AvailableBandwidth
	}
	return 0
}

>>>>>>> 683988d7... fix merge
type SignedMessage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedMessage) Reset()         { *m = SignedMessage{} }
func (m *SignedMessage) String() string { return proto.CompactTextString(m) }
func (*SignedMessage) ProtoMessage()    {}
func (*SignedMessage) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{10}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{12}
>>>>>>> 683988d7... fix merge
}
func (m *SignedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedMessage.Unmarshal(m, b)
}
func (m *SignedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedMessage.Marshal(b, m, deterministic)
}
func (m *SignedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedMessage.Merge(m, src)
}
func (m *SignedMessage) XXX_Size() int {
	return xxx_messageInfo_SignedMessage.Size(m)
}
func (m *SignedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignedMessage proto.InternalMessageInfo

func (m *SignedMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignedMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedMessage) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

<<<<<<< HEAD
=======
type DashboardReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DashboardReq) Reset()         { *m = DashboardReq{} }
func (m *DashboardReq) String() string { return proto.CompactTextString(m) }
func (*DashboardReq) ProtoMessage()    {}
func (*DashboardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{13}
}
func (m *DashboardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashboardReq.Unmarshal(m, b)
}
func (m *DashboardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashboardReq.Marshal(b, m, deterministic)
}
func (dst *DashboardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardReq.Merge(dst, src)
}
func (m *DashboardReq) XXX_Size() int {
	return xxx_messageInfo_DashboardReq.Size(m)
}
func (m *DashboardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardReq.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardReq proto.InternalMessageInfo

type DashboardStats struct {
	NodeId               string             `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeConnections      int64              `protobuf:"varint,2,opt,name=node_connections,json=nodeConnections,proto3" json:"node_connections,omitempty"`
	BootstrapAddress     string             `protobuf:"bytes,3,opt,name=bootstrap_address,json=bootstrapAddress,proto3" json:"bootstrap_address,omitempty"`
	InternalAddress      string             `protobuf:"bytes,4,opt,name=internal_address,json=internalAddress,proto3" json:"internal_address,omitempty"`
	ExternalAddress      string             `protobuf:"bytes,5,opt,name=external_address,json=externalAddress,proto3" json:"external_address,omitempty"`
	Stats                *StatSummary       `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	Connection           bool               `protobuf:"varint,7,opt,name=connection,proto3" json:"connection,omitempty"`
	Uptime               *duration.Duration `protobuf:"bytes,8,opt,name=uptime,proto3" json:"uptime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DashboardStats) Reset()         { *m = DashboardStats{} }
func (m *DashboardStats) String() string { return proto.CompactTextString(m) }
func (*DashboardStats) ProtoMessage()    {}
func (*DashboardStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{14}
}
func (m *DashboardStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashboardStats.Unmarshal(m, b)
}
func (m *DashboardStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashboardStats.Marshal(b, m, deterministic)
}
func (dst *DashboardStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardStats.Merge(dst, src)
}
func (m *DashboardStats) XXX_Size() int {
	return xxx_messageInfo_DashboardStats.Size(m)
}
func (m *DashboardStats) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardStats.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardStats proto.InternalMessageInfo

func (m *DashboardStats) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *DashboardStats) GetNodeConnections() int64 {
	if m != nil {
		return m.NodeConnections
	}
	return 0
}

func (m *DashboardStats) GetBootstrapAddress() string {
	if m != nil {
		return m.BootstrapAddress
	}
	return ""
}

func (m *DashboardStats) GetInternalAddress() string {
	if m != nil {
		return m.InternalAddress
	}
	return ""
}

func (m *DashboardStats) GetExternalAddress() string {
	if m != nil {
		return m.ExternalAddress
	}
	return ""
}

func (m *DashboardStats) GetStats() *StatSummary {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *DashboardStats) GetConnection() bool {
	if m != nil {
		return m.Connection
	}
	return false
}

func (m *DashboardStats) GetUptime() *duration.Duration {
	if m != nil {
		return m.Uptime
	}
	return nil
}

>>>>>>> 683988d7... fix merge
type SignedHash struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Certs                [][]byte `protobuf:"bytes,2,rep,name=certs,proto3" json:"certs,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedHash) Reset()         { *m = SignedHash{} }
func (m *SignedHash) String() string { return proto.CompactTextString(m) }
func (*SignedHash) ProtoMessage()    {}
func (*SignedHash) Descriptor() ([]byte, []int) {
<<<<<<< HEAD
	return fileDescriptor_569d535d76469daf, []int{11}
=======
	return fileDescriptor_piecestore_b981cf737b0da58b, []int{15}
>>>>>>> 683988d7... fix merge
}
func (m *SignedHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedHash.Unmarshal(m, b)
}
func (m *SignedHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedHash.Marshal(b, m, deterministic)
}
func (m *SignedHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedHash.Merge(m, src)
}
func (m *SignedHash) XXX_Size() int {
	return xxx_messageInfo_SignedHash.Size(m)
}
func (m *SignedHash) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedHash.DiscardUnknown(m)
}

var xxx_messageInfo_SignedHash proto.InternalMessageInfo

func (m *SignedHash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *SignedHash) GetCerts() [][]byte {
	if m != nil {
		return m.Certs
	}
	return nil
}

func (m *SignedHash) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterEnum("piecestoreroutes.BandwidthAction", BandwidthAction_name, BandwidthAction_value)
	proto.RegisterType((*PayerBandwidthAllocation)(nil), "piecestoreroutes.PayerBandwidthAllocation")
	proto.RegisterType((*RenterBandwidthAllocation)(nil), "piecestoreroutes.RenterBandwidthAllocation")
	proto.RegisterType((*PieceStore)(nil), "piecestoreroutes.PieceStore")
	proto.RegisterType((*PieceStore_PieceData)(nil), "piecestoreroutes.PieceStore.PieceData")
	proto.RegisterType((*PieceId)(nil), "piecestoreroutes.PieceId")
	proto.RegisterType((*PieceSummary)(nil), "piecestoreroutes.PieceSummary")
	proto.RegisterType((*PieceRetrieval)(nil), "piecestoreroutes.PieceRetrieval")
	proto.RegisterType((*PieceRetrieval_PieceData)(nil), "piecestoreroutes.PieceRetrieval.PieceData")
	proto.RegisterType((*PieceRetrievalStream)(nil), "piecestoreroutes.PieceRetrievalStream")
	proto.RegisterType((*PieceDelete)(nil), "piecestoreroutes.PieceDelete")
	proto.RegisterType((*PieceDeleteSummary)(nil), "piecestoreroutes.PieceDeleteSummary")
	proto.RegisterType((*PieceStoreSummary)(nil), "piecestoreroutes.PieceStoreSummary")
	proto.RegisterType((*SignedMessage)(nil), "piecestoreroutes.SignedMessage")
	proto.RegisterType((*SignedHash)(nil), "piecestoreroutes.SignedHash")
}

func init() { proto.RegisterFile("piecestore.proto", fileDescriptor_569d535d76469daf) }

var fileDescriptor_569d535d76469daf = []byte{
	// 968 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xdb, 0xc6,
	0x13, 0x37, 0x49, 0x7d, 0x58, 0x23, 0x4b, 0x56, 0x36, 0xc6, 0x1f, 0xb4, 0xe0, 0xc4, 0xfa, 0x33,
	0x6d, 0x20, 0x38, 0x80, 0xd3, 0xaa, 0x40, 0x81, 0x1e, 0x7a, 0xb0, 0x60, 0x23, 0x15, 0x8a, 0x3a,
	0xc2, 0x4a, 0xbe, 0xa4, 0x40, 0xd9, 0x15, 0x39, 0x96, 0x16, 0xa1, 0x48, 0x81, 0x5c, 0xa6, 0xb2,
	0xaf, 0x7d, 0x84, 0x1e, 0x7a, 0xe8, 0xb5, 0x0f, 0xd3, 0x17, 0xe8, 0x25, 0x87, 0x3c, 0x48, 0x4f,
	0x05, 0x77, 0x29, 0xc9, 0xfa, 0xa0, 0x84, 0x16, 0xcd, 0x6d, 0x67, 0x76, 0x38, 0xfb, 0x9b, 0xf9,
	0xcd, 0x07, 0xa1, 0x36, 0xe1, 0xe8, 0x60, 0x24, 0x82, 0x10, 0xcf, 0x27, 0x61, 0x20, 0x02, 0xf2,
	0x40, 0x13, 0x06, 0xb1, 0xc0, 0xa8, 0x0e, 0xc3, 0x60, 0x18, 0xa8, 0xdb, 0xfa, 0xd3, 0x61, 0x10,
	0x0c, 0x3d, 0x7c, 0x29, 0xa5, 0x41, 0x7c, 0xfb, 0xd2, 0x8d, 0x43, 0x26, 0x78, 0xe0, 0xab, 0x7b,
	0xeb, 0x67, 0x03, 0xcc, 0x2e, 0xbb, 0xc3, 0xb0, 0xcd, 0x7c, 0xf7, 0x27, 0xee, 0x8a, 0xd1, 0x85,
	0xe7, 0x05, 0x8e, 0x34, 0x21, 0x9f, 0xc3, 0x41, 0xc4, 0x04, 0x7a, 0x1e, 0x17, 0x68, 0x73, 0xd7,
	0xd4, 0x1a, 0x5a, 0xf3, 0xa0, 0x5d, 0xfd, 0xe3, 0xc3, 0xe9, 0xde, 0xfb, 0x0f, 0xa7, 0x85, 0xeb,
	0xc0, 0xc5, 0xce, 0x25, 0x2d, 0xcf, 0x6d, 0x3a, 0x2e, 0x79, 0x01, 0xa5, 0x78, 0xe2, 0x71, 0xff,
	0x6d, 0x62, 0xaf, 0x6f, 0xb4, 0xdf, 0x57, 0x06, 0x1d, 0x97, 0x1c, 0xc3, 0xfe, 0x98, 0x4d, 0xed,
	0x88, 0xdf, 0xa3, 0x69, 0x34, 0xb4, 0xa6, 0x41, 0x8b, 0x63, 0x36, 0xed, 0xf1, 0x7b, 0x24, 0xe7,
	0xf0, 0x18, 0xa7, 0x13, 0xae, 0xb0, 0xda, 0xb1, 0xcf, 0xa7, 0x76, 0x84, 0x8e, 0x99, 0x93, 0x56,
	0x8f, 0x16, 0x57, 0x37, 0x3e, 0x9f, 0xf6, 0xd0, 0x21, 0xcf, 0xa0, 0x12, 0x61, 0xc8, 0x99, 0x67,
	0xfb, 0xf1, 0x78, 0x80, 0xa1, 0x99, 0x6f, 0x68, 0xcd, 0x12, 0x3d, 0x50, 0xca, 0x6b, 0xa9, 0x23,
	0x5f, 0x41, 0x81, 0x39, 0xc9, 0x57, 0x66, 0xa1, 0xa1, 0x35, 0xab, 0xad, 0xff, 0x9f, 0xaf, 0xe6,
	0xee, 0x7c, 0x91, 0x06, 0x69, 0x48, 0xd3, 0x0f, 0x48, 0x13, 0x6a, 0x4e, 0x88, 0x4c, 0xa0, 0xbb,
	0x00, 0x53, 0x94, 0x60, 0xaa, 0xa9, 0x7e, 0x86, 0xe4, 0x08, 0xf2, 0x0e, 0x86, 0x22, 0x32, 0xf7,
	0x1b, 0x46, 0xf3, 0x80, 0x2a, 0x81, 0x9c, 0x40, 0x29, 0xe2, 0x43, 0x9f, 0x89, 0x38, 0x44, 0xb3,
	0x94, 0xe4, 0x85, 0x2e, 0x14, 0xd6, 0x5f, 0x1a, 0x1c, 0x53, 0xf4, 0xc5, 0x66, 0x1a, 0xbe, 0x87,
	0xda, 0x24, 0xa1, 0xc8, 0x66, 0x73, 0x9d, 0xa4, 0xa2, 0xdc, 0x3a, 0x5b, 0x0f, 0x20, 0x8b, 0xcc,
	0x76, 0x2e, 0xa1, 0x81, 0x1e, 0x4a, 0x4f, 0x0f, 0x9c, 0x1f, 0x41, 0x5e, 0x04, 0x82, 0x79, 0x92,
	0x2c, 0x83, 0x2a, 0x81, 0x7c, 0x09, 0x87, 0x89, 0x53, 0x36, 0x44, 0xdb, 0x0f, 0x5c, 0x49, 0xbe,
	0xb1, 0x91, 0xcc, 0x4a, 0x6a, 0x26, 0x45, 0x77, 0x11, 0x7c, 0x2e, 0x33, 0xf8, 0xfc, 0x6a, 0xf0,
	0xbf, 0x1b, 0x00, 0xdd, 0x24, 0x8c, 0x5e, 0x12, 0x06, 0xf9, 0x01, 0x8e, 0x06, 0x33, 0xf8, 0xeb,
	0x11, 0xbf, 0x58, 0x8f, 0x38, 0x33, 0x71, 0xf4, 0xf1, 0x60, 0x43, 0x36, 0xaf, 0x00, 0xa4, 0x0b,
	0xdb, 0x65, 0x82, 0xc9, 0xa8, 0xcb, 0xad, 0xe7, 0x1b, 0xf2, 0x38, 0x47, 0xa4, 0x8e, 0x97, 0x4c,
	0x30, 0x5a, 0x9a, 0xcc, 0x8e, 0xa4, 0x03, 0x15, 0x16, 0x8b, 0x51, 0x10, 0xf2, 0x7b, 0x85, 0xcf,
	0x90, 0x9e, 0x4e, 0xd7, 0x3d, 0xf5, 0xf8, 0xd0, 0x47, 0xf7, 0x3b, 0x8c, 0x22, 0x36, 0xc4, 0xb6,
	0x6e, 0x6a, 0x74, 0xf9, 0x4b, 0xf2, 0x35, 0x94, 0x23, 0x69, 0x63, 0x8f, 0x58, 0x34, 0x92, 0x35,
	0x5e, 0x6e, 0x9d, 0x64, 0x39, 0xfa, 0x86, 0x45, 0x23, 0x0a, 0xd1, 0xfc, 0x5c, 0x47, 0x28, 0xcd,
	0x11, 0x92, 0x2a, 0xe8, 0x69, 0xa3, 0x96, 0xa8, 0xce, 0xdd, 0xac, 0x3e, 0xd2, 0xb3, 0xfa, 0xc8,
	0x84, 0xa2, 0x13, 0xf8, 0x02, 0x7d, 0xa1, 0x08, 0xa7, 0x33, 0xd1, 0xfa, 0x55, 0x83, 0xa2, 0x7c,
	0xa7, 0xe3, 0xae, 0xbd, 0xb2, 0x96, 0x0c, 0xfd, 0x5f, 0x27, 0x63, 0x75, 0xe6, 0x18, 0x3b, 0x67,
	0x8e, 0x35, 0x86, 0x03, 0xc5, 0x56, 0x3c, 0x1e, 0xb3, 0xf0, 0x6e, 0x0d, 0xdd, 0x93, 0x19, 0xe3,
	0x72, 0xd0, 0xa8, 0xd0, 0x15, 0x93, 0xdb, 0x46, 0x8d, 0x91, 0x91, 0x22, 0xeb, 0xbd, 0x0e, 0x55,
	0xf9, 0x1e, 0x45, 0x11, 0x72, 0x7c, 0xc7, 0xbc, 0x8f, 0x5e, 0xb3, 0x9d, 0x0d, 0x35, 0x7b, 0x96,
	0x51, 0xb3, 0x73, 0x54, 0x1f, 0xbb, 0x6e, 0xeb, 0x74, 0x5b, 0xe1, 0xed, 0x48, 0xfa, 0xff, 0xa0,
	0x10, 0xdc, 0xde, 0x46, 0x28, 0xd2, 0x3c, 0xa7, 0x92, 0xf5, 0x1a, 0x8e, 0x96, 0xa3, 0xe8, 0x89,
	0x10, 0xd9, 0x78, 0xc5, 0x9d, 0xb6, 0xea, 0xee, 0x41, 0xd9, 0xea, 0xcb, 0x65, 0xfb, 0x9b, 0x06,
	0x65, 0x85, 0x12, 0x3d, 0x14, 0xb8, 0xbb, 0x74, 0x8d, 0xff, 0xac, 0x74, 0x73, 0xbb, 0x4b, 0xf7,
	0x1c, 0xc8, 0x03, 0x70, 0xb3, 0x02, 0x36, 0xa1, 0x38, 0x56, 0xcf, 0xa4, 0x40, 0x67, 0xa2, 0xf5,
	0x8b, 0x06, 0x8f, 0x16, 0x93, 0x69, 0xa7, 0x3d, 0xf9, 0x14, 0xaa, 0x72, 0xa0, 0xdb, 0x21, 0x3a,
	0xc8, 0xdf, 0xa1, 0x9b, 0x32, 0x51, 0x91, 0x5a, 0x9a, 0x2a, 0x57, 0x27, 0x90, 0xf1, 0xcf, 0x26,
	0x90, 0xf5, 0x23, 0x54, 0x96, 0x92, 0x43, 0x08, 0xe4, 0x64, 0xa5, 0xca, 0x1f, 0x06, 0x2a, 0xcf,
	0xcb, 0x4b, 0x40, 0x5f, 0x59, 0x02, 0x92, 0xdf, 0x78, 0xe0, 0x71, 0xc7, 0x7e, 0x8b, 0x77, 0xe9,
	0xe8, 0x29, 0x29, 0xcd, 0xb7, 0x78, 0x67, 0xf5, 0x01, 0x16, 0x6f, 0x27, 0xee, 0x25, 0xce, 0xd4,
	0x7d, 0x72, 0x5e, 0x6c, 0x1e, 0x3d, 0x73, 0xf3, 0x18, 0x2b, 0x8f, 0x9e, 0x51, 0x38, 0x5c, 0xd9,
	0xf7, 0xa4, 0x08, 0x46, 0xf7, 0xa6, 0x5f, 0xdb, 0x4b, 0x0e, 0xaf, 0xae, 0xfa, 0x35, 0x8d, 0x54,
	0xa0, 0xf4, 0xea, 0xaa, 0x6f, 0x5f, 0xdc, 0x5c, 0x76, 0xfa, 0x35, 0x9d, 0x54, 0x01, 0x12, 0x91,
	0x5e, 0x75, 0x2f, 0x3a, 0xb4, 0x66, 0x24, 0x72, 0xf7, 0x66, 0x2e, 0xe7, 0x5a, 0x7f, 0xea, 0x50,
	0x5b, 0x30, 0x44, 0x65, 0xde, 0xc8, 0x25, 0xe4, 0xa5, 0x8e, 0x1c, 0x67, 0x34, 0x6d, 0xc7, 0xad,
	0x3f, 0xcd, 0xda, 0x41, 0x8a, 0x64, 0x6b, 0x8f, 0xbc, 0x81, 0xfd, 0xb4, 0x2d, 0x90, 0x34, 0x76,
	0x75, 0x7f, 0xfd, 0xf9, 0x2e, 0x0b, 0xd5, 0x59, 0xd6, 0x5e, 0x53, 0xfb, 0x4c, 0x23, 0xd7, 0x90,
	0x57, 0xeb, 0xf7, 0x64, 0xdb, 0x2a, 0xac, 0x3f, 0xdb, 0x76, 0x3b, 0x47, 0xda, 0xd4, 0xc8, 0x6b,
	0x28, 0xa4, 0x0d, 0xf7, 0x24, 0xe3, 0x13, 0x75, 0x5d, 0xff, 0x64, 0xeb, 0xf5, 0xdc, 0x65, 0x3b,
	0xf7, 0x46, 0x9f, 0x0c, 0x06, 0x05, 0xf9, 0xd7, 0xfa, 0xc5, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xba, 0xef, 0xb1, 0x53, 0x07, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PieceStoreRoutesClient is the client API for PieceStoreRoutes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PieceStoreRoutesClient interface {
	Piece(ctx context.Context, in *PieceId, opts ...grpc.CallOption) (*PieceSummary, error)
	Retrieve(ctx context.Context, opts ...grpc.CallOption) (PieceStoreRoutes_RetrieveClient, error)
	Store(ctx context.Context, opts ...grpc.CallOption) (PieceStoreRoutes_StoreClient, error)
	Delete(ctx context.Context, in *PieceDelete, opts ...grpc.CallOption) (*PieceDeleteSummary, error)
}

type pieceStoreRoutesClient struct {
	cc *grpc.ClientConn
}

func NewPieceStoreRoutesClient(cc *grpc.ClientConn) PieceStoreRoutesClient {
	return &pieceStoreRoutesClient{cc}
}

func (c *pieceStoreRoutesClient) Piece(ctx context.Context, in *PieceId, opts ...grpc.CallOption) (*PieceSummary, error) {
	out := new(PieceSummary)
	err := c.cc.Invoke(ctx, "/piecestoreroutes.PieceStoreRoutes/Piece", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pieceStoreRoutesClient) Retrieve(ctx context.Context, opts ...grpc.CallOption) (PieceStoreRoutes_RetrieveClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PieceStoreRoutes_serviceDesc.Streams[0], "/piecestoreroutes.PieceStoreRoutes/Retrieve", opts...)
	if err != nil {
		return nil, err
	}
	x := &pieceStoreRoutesRetrieveClient{stream}
	return x, nil
}

type PieceStoreRoutes_RetrieveClient interface {
	Send(*PieceRetrieval) error
	Recv() (*PieceRetrievalStream, error)
	grpc.ClientStream
}

type pieceStoreRoutesRetrieveClient struct {
	grpc.ClientStream
}

func (x *pieceStoreRoutesRetrieveClient) Send(m *PieceRetrieval) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pieceStoreRoutesRetrieveClient) Recv() (*PieceRetrievalStream, error) {
	m := new(PieceRetrievalStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pieceStoreRoutesClient) Store(ctx context.Context, opts ...grpc.CallOption) (PieceStoreRoutes_StoreClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PieceStoreRoutes_serviceDesc.Streams[1], "/piecestoreroutes.PieceStoreRoutes/Store", opts...)
	if err != nil {
		return nil, err
	}
	x := &pieceStoreRoutesStoreClient{stream}
	return x, nil
}

type PieceStoreRoutes_StoreClient interface {
	Send(*PieceStore) error
	CloseAndRecv() (*PieceStoreSummary, error)
	grpc.ClientStream
}

type pieceStoreRoutesStoreClient struct {
	grpc.ClientStream
}

func (x *pieceStoreRoutesStoreClient) Send(m *PieceStore) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pieceStoreRoutesStoreClient) CloseAndRecv() (*PieceStoreSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PieceStoreSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pieceStoreRoutesClient) Delete(ctx context.Context, in *PieceDelete, opts ...grpc.CallOption) (*PieceDeleteSummary, error) {
	out := new(PieceDeleteSummary)
	err := c.cc.Invoke(ctx, "/piecestoreroutes.PieceStoreRoutes/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PieceStoreRoutesServer is the server API for PieceStoreRoutes service.
type PieceStoreRoutesServer interface {
	Piece(context.Context, *PieceId) (*PieceSummary, error)
	Retrieve(PieceStoreRoutes_RetrieveServer) error
	Store(PieceStoreRoutes_StoreServer) error
	Delete(context.Context, *PieceDelete) (*PieceDeleteSummary, error)
}

func RegisterPieceStoreRoutesServer(s *grpc.Server, srv PieceStoreRoutesServer) {
	s.RegisterService(&_PieceStoreRoutes_serviceDesc, srv)
}

func _PieceStoreRoutes_Piece_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PieceId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PieceStoreRoutesServer).Piece(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/piecestoreroutes.PieceStoreRoutes/Piece",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PieceStoreRoutesServer).Piece(ctx, req.(*PieceId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PieceStoreRoutes_Retrieve_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PieceStoreRoutesServer).Retrieve(&pieceStoreRoutesRetrieveServer{stream})
}

type PieceStoreRoutes_RetrieveServer interface {
	Send(*PieceRetrievalStream) error
	Recv() (*PieceRetrieval, error)
	grpc.ServerStream
}

type pieceStoreRoutesRetrieveServer struct {
	grpc.ServerStream
}

func (x *pieceStoreRoutesRetrieveServer) Send(m *PieceRetrievalStream) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pieceStoreRoutesRetrieveServer) Recv() (*PieceRetrieval, error) {
	m := new(PieceRetrieval)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PieceStoreRoutes_Store_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PieceStoreRoutesServer).Store(&pieceStoreRoutesStoreServer{stream})
}

type PieceStoreRoutes_StoreServer interface {
	SendAndClose(*PieceStoreSummary) error
	Recv() (*PieceStore, error)
	grpc.ServerStream
}

type pieceStoreRoutesStoreServer struct {
	grpc.ServerStream
}

func (x *pieceStoreRoutesStoreServer) SendAndClose(m *PieceStoreSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pieceStoreRoutesStoreServer) Recv() (*PieceStore, error) {
	m := new(PieceStore)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PieceStoreRoutes_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PieceDelete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PieceStoreRoutesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/piecestoreroutes.PieceStoreRoutes/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PieceStoreRoutesServer).Delete(ctx, req.(*PieceDelete))
	}
	return interceptor(ctx, in, info, handler)
}

var _PieceStoreRoutes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "piecestoreroutes.PieceStoreRoutes",
	HandlerType: (*PieceStoreRoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Piece",
			Handler:    _PieceStoreRoutes_Piece_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PieceStoreRoutes_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Retrieve",
			Handler:       _PieceStoreRoutes_Retrieve_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Store",
			Handler:       _PieceStoreRoutes_Store_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "piecestore.proto",
}
<<<<<<< HEAD
=======

func init() { proto.RegisterFile("piecestore.proto", fileDescriptor_piecestore_b981cf737b0da58b) }

var fileDescriptor_piecestore_b981cf737b0da58b = []byte{
	// 1255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x92, 0xdb, 0x44,
	0x10, 0x5e, 0x49, 0xfe, 0x6d, 0xaf, 0x7f, 0x32, 0xd9, 0x02, 0xad, 0x2b, 0x9b, 0x18, 0x85, 0x04,
	0x93, 0x54, 0x39, 0xc9, 0xa6, 0x8a, 0x82, 0x03, 0x87, 0x5d, 0xbc, 0x15, 0x5c, 0x14, 0xc9, 0x32,
	0xde, 0xbd, 0x84, 0x2a, 0xc4, 0xd8, 0x9a, 0x78, 0x55, 0x91, 0x25, 0xa3, 0x19, 0x85, 0xdd, 0xbc,
	0x06, 0x07, 0x0e, 0x5c, 0xb9, 0xf2, 0x08, 0xdc, 0x79, 0x86, 0x1c, 0xc2, 0x1b, 0xf0, 0x00, 0x9c,
	0xa8, 0x99, 0xd1, 0x8f, 0xff, 0x64, 0x17, 0x14, 0xb9, 0xcd, 0xf4, 0x7c, 0xd3, 0xea, 0xfe, 0xfa,
	0x9b, 0x56, 0x43, 0x6b, 0xe6, 0xd2, 0x31, 0x65, 0x3c, 0x08, 0x69, 0x6f, 0x16, 0x06, 0x3c, 0x40,
	0x73, 0x96, 0x30, 0x88, 0x38, 0x65, 0x6d, 0x98, 0x04, 0x93, 0x40, 0x9d, 0xb6, 0x6f, 0x4e, 0x82,
	0x60, 0xe2, 0xd1, 0x07, 0x72, 0x37, 0x8a, 0x5e, 0x3c, 0x70, 0xa2, 0x90, 0x70, 0x37, 0xf0, 0xd5,
	0xb9, 0xf5, 0xbb, 0x01, 0xe6, 0x29, 0xb9, 0xa2, 0xe1, 0x31, 0xf1, 0x9d, 0x1f, 0x5d, 0x87, 0x5f,
	0x1c, 0x79, 0x5e, 0x30, 0x96, 0x10, 0xf4, 0x08, 0x76, 0x19, 0xe1, 0xd4, 0xf3, 0x5c, 0x4e, 0x6d,
	0xd7, 0x31, 0xb5, 0x8e, 0xd6, 0xdd, 0x3d, 0x6e, 0xfc, 0xf1, 0xf6, 0xd6, 0xce, 0x9b, 0xb7, 0xb7,
	0x4a, 0x4f, 0x03, 0x87, 0x0e, 0xfa, 0xb8, 0x96, 0x62, 0x06, 0x0e, 0xba, 0x0f, 0xd5, 0x68, 0xe6,
	0xb9, 0xfe, 0x4b, 0x81, 0xd7, 0xd7, 0xe2, 0x2b, 0x0a, 0x30, 0x70, 0xd0, 0x3e, 0x54, 0xa6, 0xe4,
	0xd2, 0x66, 0xee, 0x6b, 0x6a, 0x1a, 0x1d, 0xad, 0x6b, 0xe0, 0xf2, 0x94, 0x5c, 0x0e, 0xdd, 0xd7,
	0x14, 0xf5, 0xe0, 0x3a, 0xbd, 0x9c, 0xb9, 0x2a, 0x56, 0x3b, 0xf2, 0xdd, 0x4b, 0x9b, 0xd1, 0xb1,
	0x59, 0x90, 0xa8, 0x6b, 0xd9, 0xd1, 0xb9, 0xef, 0x5e, 0x0e, 0xe9, 0x18, 0xdd, 0x86, 0x3a, 0xa3,
	0xa1, 0x4b, 0x3c, 0xdb, 0x8f, 0xa6, 0x23, 0x1a, 0x9a, 0xc5, 0x8e, 0xd6, 0xad, 0xe2, 0x5d, 0x65,
	0x7c, 0x2a, 0x6d, 0xe8, 0x33, 0x28, 0x91, 0xb1, 0xb8, 0x65, 0x96, 0x3a, 0x5a, 0xb7, 0x71, 0xf8,
	0x41, 0x6f, 0x99, 0xbb, 0x5e, 0x46, 0x83, 0x04, 0xe2, 0xf8, 0x02, 0xea, 0x42, 0x6b, 0x1c, 0x52,
	0xc2, 0xa9, 0x93, 0x05, 0x53, 0x96, 0xc1, 0x34, 0x62, 0x7b, 0x12, 0xc9, 0x1e, 0x14, 0xc7, 0x34,
	0xe4, 0xcc, 0xac, 0x74, 0x8c, 0xee, 0x2e, 0x56, 0x1b, 0x74, 0x03, 0xaa, 0xcc, 0x9d, 0xf8, 0x84,
	0x47, 0x21, 0x35, 0xab, 0x82, 0x17, 0x9c, 0x19, 0xd0, 0xa7, 0xd0, 0x12, 0x41, 0x90, 0x09, 0xb5,
	0xfd, 0xc0, 0x11, 0x5c, 0x33, 0x13, 0xc4, 0xf5, 0x15, 0xf2, 0x1a, 0x31, 0x4e, 0x6e, 0x1d, 0x66,
	0xfd, 0xad, 0xc1, 0x3e, 0xa6, 0x3e, 0x5f, 0x5f, 0xc0, 0x6f, 0xa1, 0x35, 0x13, 0xc5, 0xb5, 0x49,
	0x6a, 0x93, 0x45, 0xac, 0x1d, 0xde, 0x5b, 0x4d, 0x3d, 0x4f, 0x06, 0xc7, 0x05, 0x11, 0x03, 0x6e,
	0x4a, 0x4f, 0x73, 0xce, 0xf7, 0xa0, 0xc8, 0x03, 0x4e, 0x3c, 0x59, 0x66, 0x03, 0xab, 0x0d, 0xfa,
	0x04, 0x9a, 0x4b, 0xa9, 0xc8, 0xd2, 0xae, 0x66, 0x52, 0x5f, 0xc8, 0x24, 0xa3, 0xad, 0x90, 0x4b,
	0x5b, 0x71, 0x89, 0x36, 0xeb, 0x57, 0x03, 0xe0, 0x54, 0xa4, 0x31, 0x14, 0x69, 0xa0, 0xef, 0x60,
	0x6f, 0x94, 0x84, 0xbf, 0x9a, 0xf1, 0xfd, 0xd5, 0x8c, 0x73, 0x89, 0xc3, 0xd7, 0x47, 0x6b, 0xd8,
	0x3c, 0x01, 0x90, 0x2e, 0x6c, 0x87, 0x70, 0x22, 0xb3, 0xae, 0x1d, 0xde, 0x5d, 0xc3, 0x63, 0x1a,
	0x91, 0x5a, 0xf6, 0x09, 0x27, 0xb8, 0x3a, 0x4b, 0x96, 0x68, 0x00, 0x75, 0x12, 0xf1, 0x8b, 0x20,
	0x74, 0x5f, 0xab, 0xf8, 0x0c, 0xe9, 0xe9, 0xd6, 0xaa, 0xa7, 0xa1, 0x3b, 0xf1, 0xa9, 0xf3, 0x35,
	0x65, 0x8c, 0x4c, 0xe8, 0xb1, 0x6e, 0x6a, 0x78, 0xf1, 0x26, 0xfa, 0x1c, 0x6a, 0x4c, 0x62, 0xec,
	0x0b, 0xc2, 0x2e, 0xe4, 0xeb, 0xa8, 0x1d, 0xde, 0xc8, 0x73, 0xf4, 0x25, 0x61, 0x17, 0x18, 0x58,
	0xba, 0x6e, 0x53, 0xa8, 0xa6, 0x11, 0xa2, 0x06, 0xe8, 0xf1, 0x13, 0xaf, 0x62, 0xdd, 0x75, 0xf2,
	0x5e, 0xa0, 0x9e, 0xf7, 0x02, 0x4d, 0x28, 0x8f, 0x03, 0x9f, 0x53, 0x9f, 0xab, 0x82, 0xe3, 0x64,
	0x6b, 0xfd, 0xac, 0x41, 0x59, 0x7e, 0x67, 0xe0, 0xac, 0x7c, 0x65, 0x85, 0x0c, 0xfd, 0x3f, 0x93,
	0xb1, 0xdc, 0xad, 0x8c, 0xad, 0xdd, 0xca, 0x9a, 0xc2, 0xae, 0xaa, 0x56, 0x34, 0x9d, 0x92, 0xf0,
	0x6a, 0x25, 0xba, 0x83, 0xa4, 0xe2, 0xb2, 0x45, 0xa9, 0xd4, 0x55, 0x25, 0x37, 0x35, 0x29, 0x23,
	0x87, 0x22, 0xeb, 0x8d, 0x0e, 0x0d, 0xf9, 0x3d, 0x4c, 0x79, 0xe8, 0xd2, 0x57, 0xc4, 0x7b, 0xe7,
	0x9a, 0x1d, 0xac, 0xd1, 0xec, 0xbd, 0x1c, 0xcd, 0xa6, 0x51, 0xbd, 0x6b, 0xdd, 0xb6, 0xf1, 0x26,
	0xe1, 0x6d, 0x21, 0xfd, 0x3d, 0x28, 0x05, 0x2f, 0x5e, 0x30, 0xca, 0x63, 0x9e, 0xe3, 0x9d, 0xf5,
	0x0c, 0xf6, 0x16, 0xb3, 0x18, 0xf2, 0x90, 0x92, 0xe9, 0x92, 0x3b, 0x6d, 0xd9, 0xdd, 0x9c, 0x6c,
	0xf5, 0x45, 0xd9, 0xfe, 0xa2, 0x41, 0x4d, 0x45, 0x49, 0x3d, 0xca, 0xe9, 0x76, 0xe9, 0x1a, 0xff,
	0x9b, 0x74, 0x0b, 0xdb, 0xa5, 0xdb, 0x03, 0x34, 0x17, 0x5c, 0x22, 0x60, 0x13, 0xca, 0x53, 0xf5,
	0x99, 0x38, 0xd0, 0x64, 0x6b, 0xfd, 0xa4, 0xc1, 0xb5, 0xac, 0x33, 0x6d, 0xc5, 0xa3, 0x3b, 0xd0,
	0x90, 0x0d, 0xdd, 0x0e, 0xe9, 0x98, 0xba, 0xaf, 0xa8, 0x13, 0x57, 0xa2, 0x2e, 0xad, 0x38, 0x36,
	0x2e, 0x77, 0x20, 0xe3, 0xdf, 0x75, 0x20, 0x0b, 0xa0, 0x32, 0xe4, 0x84, 0x33, 0x4c, 0x7f, 0xb0,
	0x7e, 0xd3, 0xa0, 0x26, 0x36, 0x49, 0x6c, 0x07, 0x00, 0x11, 0xa3, 0x8e, 0xcd, 0x66, 0x64, 0x9c,
	0x16, 0x4e, 0x58, 0x86, 0xc2, 0x80, 0x3e, 0x82, 0x26, 0x79, 0x45, 0x5c, 0x8f, 0x8c, 0x3c, 0x1a,
	0x63, 0x54, 0x84, 0x8d, 0xd4, 0xac, 0x80, 0x77, 0xa0, 0x21, 0xfd, 0xa4, 0xcf, 0x23, 0x16, 0x4e,
	0x5d, 0x58, 0xd3, 0x87, 0x84, 0x1e, 0xc0, 0xf5, 0xcc, 0x5f, 0x86, 0x55, 0x13, 0x07, 0x4a, 0x8f,
	0xd2, 0x0b, 0xd6, 0xf7, 0x50, 0x5f, 0x28, 0x2c, 0x42, 0x50, 0x90, 0xaf, 0x4c, 0x8e, 0x49, 0x58,
	0xae, 0x17, 0x7f, 0x60, 0xfa, 0xf2, 0x7f, 0x5f, 0x68, 0x33, 0x1a, 0x79, 0xee, 0xd8, 0x7e, 0x49,
	0xaf, 0xe2, 0xb6, 0x59, 0x55, 0x96, 0xaf, 0xe8, 0x95, 0xd5, 0x80, 0xdd, 0x3e, 0x61, 0x17, 0xa3,
	0x80, 0x84, 0x8e, 0x60, 0xe8, 0x4f, 0x1d, 0x1a, 0xa9, 0x41, 0xf2, 0x86, 0xde, 0x87, 0x72, 0xf2,
	0x9b, 0x55, 0x05, 0x2c, 0xf9, 0xea, 0x7f, 0xfa, 0x31, 0xb4, 0xe4, 0xc1, 0x38, 0xf0, 0x7d, 0x2a,
	0x67, 0x18, 0x16, 0xf3, 0xd3, 0x14, 0xf6, 0x2f, 0x32, 0x33, 0xba, 0x0f, 0xd7, 0x46, 0x41, 0xc0,
	0x19, 0x0f, 0xc9, 0xcc, 0x26, 0x8e, 0x13, 0x52, 0xc6, 0x64, 0x30, 0x55, 0xdc, 0x4a, 0x0f, 0x8e,
	0x94, 0x5d, 0xf8, 0x75, 0x45, 0x07, 0xf2, 0x89, 0x97, 0x62, 0x0b, 0x12, 0xdb, 0x4c, 0xec, 0x73,
	0x50, 0x7a, 0xb9, 0x04, 0x55, 0x63, 0x59, 0x33, 0xb1, 0x27, 0xd0, 0xc7, 0x50, 0x64, 0x22, 0x1f,
	0x39, 0x98, 0xd5, 0x0e, 0x0f, 0xd6, 0x08, 0x28, 0x53, 0x06, 0x56, 0x58, 0x74, 0x13, 0x20, 0xcb,
	0x4e, 0x4e, 0x63, 0x15, 0x3c, 0x67, 0x41, 0x8f, 0xa0, 0x14, 0xcd, 0xb8, 0x3b, 0xa5, 0x66, 0x45,
	0x7a, 0xdd, 0xef, 0xa9, 0x61, 0xb8, 0x97, 0x0c, 0xc3, 0xbd, 0x7e, 0x3c, 0x0c, 0xe3, 0x18, 0x68,
	0x9d, 0x01, 0x64, 0x4a, 0x15, 0x05, 0x95, 0xaa, 0x8e, 0x0b, 0x2a, 0xd6, 0xd9, 0x9c, 0xa2, 0xe7,
	0xce, 0x29, 0xc6, 0x52, 0x99, 0xef, 0x61, 0x68, 0x2e, 0xcd, 0x95, 0xa8, 0x0c, 0xc6, 0xe9, 0xf9,
	0x59, 0x6b, 0x47, 0x2c, 0x9e, 0x9c, 0x9c, 0xb5, 0x34, 0x54, 0x87, 0xea, 0x93, 0x93, 0x33, 0xfb,
	0xe8, 0xbc, 0x3f, 0x38, 0x6b, 0xe9, 0xa8, 0x01, 0x20, 0xb6, 0xf8, 0xe4, 0xf4, 0x68, 0x80, 0x5b,
	0x86, 0xd8, 0x9f, 0x9e, 0xa7, 0xfb, 0xc2, 0xe1, 0x5f, 0x06, 0xb4, 0xb2, 0xf7, 0x8c, 0x25, 0x49,
	0xa8, 0x0f, 0x45, 0x69, 0x43, 0xfb, 0x39, 0x2d, 0x7e, 0xe0, 0xb4, 0x6f, 0xe6, 0x4d, 0x2c, 0x8a,
	0x5c, 0x6b, 0x07, 0x3d, 0x87, 0x4a, 0xdc, 0x44, 0x29, 0xea, 0x6c, 0xfb, 0x57, 0xb4, 0xef, 0x6e,
	0x43, 0xa8, 0x3e, 0x6c, 0xed, 0x74, 0xb5, 0x87, 0x1a, 0x7a, 0x0a, 0x45, 0x35, 0xac, 0xdd, 0xd8,
	0x34, 0x38, 0xb5, 0x6f, 0x6f, 0x3a, 0x4d, 0x23, 0xed, 0x6a, 0xe8, 0x19, 0x94, 0xe2, 0xf6, 0x7c,
	0x90, 0x73, 0x45, 0x1d, 0xb7, 0x3f, 0xdc, 0x78, 0x9c, 0x25, 0xdf, 0x17, 0x01, 0x0a, 0x75, 0xb5,
	0xd7, 0x6b, 0x50, 0xb4, 0xaa, 0xf6, 0x66, 0x7d, 0x5a, 0x3b, 0xe8, 0x1b, 0xa8, 0xa6, 0x0f, 0x15,
	0xad, 0x61, 0x7c, 0xfe, 0x59, 0xb7, 0x3b, 0x1b, 0xce, 0xe5, 0x27, 0xad, 0x9d, 0x87, 0xda, 0x71,
	0xe1, 0xb9, 0x3e, 0x1b, 0x8d, 0x4a, 0x52, 0xbb, 0x8f, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xbd,
	0x34, 0x2c, 0xc4, 0x08, 0x0e, 0x00, 0x00,
}
>>>>>>> 683988d7... fix merge
